"""adaptive learning engine: profiles, patterns, recommendations, sessions

Revision ID: 28003658254e
Revises: 6a21be1edd1a
Create Date: 2026-08-18 14:05:54.578366

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "28003658254e"
down_revision: str | None = "6a21be1edd1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_sessions",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("goal", sa.String(length=50), nullable=True),
        sa.Column("recommended_focus", sa.JSON(), nullable=True),
        sa.Column("exercises_completed", sa.Integer(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_sessions_user_id"), "learning_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "mistake_patterns",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("canonical_label", sa.String(length=255), nullable=False),
        sa.Column("description_vi", sa.String(length=1000), nullable=False),
        sa.Column("examples", sa.JSON(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("recent_evidence_count", sa.Integer(), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mistake_patterns_user_id"), "mistake_patterns", ["user_id"], unique=False
    )
    op.create_table(
        "learning_recommendations",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("exercise_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("strategy", sa.String(length=32), nullable=False),
        sa.Column("exercise_type", sa.String(length=32), nullable=False),
        sa.Column("topic", sa.String(length=100), nullable=False),
        sa.Column("register", sa.String(length=16), nullable=False),
        sa.Column("jlpt_level", sa.String(length=8), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("target_length", sa.String(length=32), nullable=False),
        sa.Column("focus_skills", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("explanation", sa.String(length=2000), nullable=True),
        sa.Column("evidence_ids", sa.JSON(), nullable=True),
        sa.Column("skill_before", sa.JSON(), nullable=True),
        sa.Column("skill_after", sa.JSON(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("recommendation_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_recommendations_exercise_id"),
        "learning_recommendations",
        ["exercise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_recommendations_user_id"),
        "learning_recommendations",
        ["user_id"],
        unique=False,
    )
    op.add_column("learner_profiles", sa.Column("goal", sa.String(length=50), nullable=True))
    op.add_column("learner_profiles", sa.Column("target_jlpt", sa.String(length=8), nullable=True))
    op.add_column("learner_profiles", sa.Column("daily_target", sa.Integer(), nullable=False))
    op.add_column("learner_profiles", sa.Column("preferred_registers", sa.JSON(), nullable=True))
    op.add_column("learner_profiles", sa.Column("preferred_topics", sa.JSON(), nullable=True))
    op.add_column(
        "learner_profiles", sa.Column("evaluations_since_synthesis", sa.Integer(), nullable=False)
    )
    op.add_column(
        "learner_profiles", sa.Column("profile_version", sa.String(length=32), nullable=False)
    )
    op.alter_column(
        "learner_profiles",
        "user_id",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "learner_profiles",
        "user_id",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36),
        nullable=False,
    )
    op.drop_column("learner_profiles", "profile_version")
    op.drop_column("learner_profiles", "evaluations_since_synthesis")
    op.drop_column("learner_profiles", "preferred_topics")
    op.drop_column("learner_profiles", "preferred_registers")
    op.drop_column("learner_profiles", "daily_target")
    op.drop_column("learner_profiles", "target_jlpt")
    op.drop_column("learner_profiles", "goal")
    op.drop_index(
        op.f("ix_learning_recommendations_user_id"), table_name="learning_recommendations"
    )
    op.drop_index(
        op.f("ix_learning_recommendations_exercise_id"), table_name="learning_recommendations"
    )
    op.drop_table("learning_recommendations")
    op.drop_index(op.f("ix_mistake_patterns_user_id"), table_name="mistake_patterns")
    op.drop_table("mistake_patterns")
    op.drop_index(op.f("ix_learning_sessions_user_id"), table_name="learning_sessions")
    op.drop_table("learning_sessions")
    # ### end Alembic commands ###
