"""interactive writing simulation

Revision ID: fea5679e6ecd
Revises: a7e4b2c9d1f3
Create Date: 2026-08-18 22:59:31.299783

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fea5679e6ecd"
down_revision: str | None = "a7e4b2c9d1f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_sessions",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("scenario_id", sa.String(length=36), nullable=False),
        sa.Column("simulation_type", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("register", sa.String(length=16), nullable=False),
        sa.Column("jlpt_level", sa.String(length=8), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("pressure_condition", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resolution", sa.String(length=32), nullable=True),
        sa.Column("max_turns", sa.Integer(), nullable=False),
        sa.Column("current_turn", sa.Integer(), nullable=False),
        sa.Column("objective_vi", sa.Text(), nullable=False),
        sa.Column("persona", sa.JSON(), nullable=True),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scenario_id"], ["writing_scenarios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_sessions_scenario_id"),
        "simulation_sessions",
        ["scenario_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulation_sessions_simulation_type"),
        "simulation_sessions",
        ["simulation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulation_sessions_user_id"), "simulation_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "simulation_turns",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=16), nullable=False),
        sa.Column("turn_type", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("turn_metadata", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["simulation_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "turn_number", name="uq_simulation_turn_number"),
    )
    op.create_index(
        op.f("ix_simulation_turns_session_id"), "simulation_turns", ["session_id"], unique=False
    )
    op.create_table(
        "simulation_evaluations",
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("scores", sa.JSON(), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=False),
        sa.Column("strengths", sa.JSON(), nullable=False),
        sa.Column("issues", sa.JSON(), nullable=False),
        sa.Column("corrections", sa.JSON(), nullable=True),
        sa.Column("feedback_vi", sa.Text(), nullable=True),
        sa.Column("evaluation_version", sa.String(length=64), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["turn_id"], ["simulation_turns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_simulation_evaluations_turn_id"),
        "simulation_evaluations",
        ["turn_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_simulation_evaluations_turn_id"), table_name="simulation_evaluations")
    op.drop_table("simulation_evaluations")
    op.drop_index(op.f("ix_simulation_turns_session_id"), table_name="simulation_turns")
    op.drop_table("simulation_turns")
    op.drop_index(op.f("ix_simulation_sessions_user_id"), table_name="simulation_sessions")
    op.drop_index(op.f("ix_simulation_sessions_simulation_type"), table_name="simulation_sessions")
    op.drop_index(op.f("ix_simulation_sessions_scenario_id"), table_name="simulation_sessions")
    op.drop_table("simulation_sessions")
    # ### end Alembic commands ###
