"""exercise generation metadata

Revision ID: 94f554b08578
Revises: 95ac7b968251
Create Date: 2026-08-18 07:14:49.321319

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "94f554b08578"
down_revision: str | None = "95ac7b968251"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercises",
        sa.Column(
            "exercise_type",
            sa.Enum(
                "SENTENCE_TRANSLATION",
                "MULTI_SENTENCE_TRANSLATION",
                "PARAGRAPH_TRANSLATION",
                "FREE_WRITING",
                "REGISTER_CHALLENGE",
                name="exercisetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
    )
    op.add_column("exercises", sa.Column("topic", sa.String(length=100), nullable=False))
    op.add_column("exercises", sa.Column("subtopic", sa.String(length=100), nullable=True))
    op.add_column("exercises", sa.Column("context", sa.Text(), nullable=False))
    op.add_column("exercises", sa.Column("prompt_vi", sa.Text(), nullable=False))
    op.add_column("exercises", sa.Column("prompt_vi_hash", sa.String(length=64), nullable=False))
    op.add_column(
        "exercises",
        sa.Column(
            "target_length",
            sa.Enum(
                "SHORT_SENTENCE",
                "SENTENCE",
                "MULTI_SENTENCE",
                "PARAGRAPH",
                "LONG_WRITING",
                name="targetlength",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "exercises",
        sa.Column(
            "register",
            sa.Enum(
                "CASUAL",
                "POLITE",
                "BUSINESS",
                "MIXED",
                name="register",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "exercises",
        sa.Column(
            "jlpt_level",
            sa.Enum("N5", "N4", "N3", "N2", "N1", name="jlptlevel", native_enum=False, length=8),
            nullable=False,
        ),
    )
    op.add_column("exercises", sa.Column("grammar_complexity", sa.Integer(), nullable=False))
    op.add_column("exercises", sa.Column("vocabulary_complexity", sa.Integer(), nullable=False))
    op.add_column("exercises", sa.Column("context_complexity", sa.Integer(), nullable=False))
    op.add_column("exercises", sa.Column("naturalness_target", sa.Integer(), nullable=False))
    op.add_column("exercises", sa.Column("generation_metadata", sa.JSON(), nullable=True))
    op.alter_column(
        "exercises",
        "user_id",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36),
        nullable=True,
    )
    op.create_index(
        op.f("ix_exercises_prompt_vi_hash"), "exercises", ["prompt_vi_hash"], unique=False
    )
    op.drop_column("exercises", "source_text")
    op.drop_column("exercises", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercises",
        sa.Column("type", mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32), nullable=False),
    )
    op.add_column(
        "exercises",
        sa.Column("source_text", mysql.TEXT(collation="utf8mb4_unicode_ci"), nullable=False),
    )
    op.drop_index(op.f("ix_exercises_prompt_vi_hash"), table_name="exercises")
    op.alter_column(
        "exercises",
        "user_id",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36),
        nullable=False,
    )
    op.drop_column("exercises", "generation_metadata")
    op.drop_column("exercises", "naturalness_target")
    op.drop_column("exercises", "context_complexity")
    op.drop_column("exercises", "vocabulary_complexity")
    op.drop_column("exercises", "grammar_complexity")
    op.drop_column("exercises", "jlpt_level")
    op.drop_column("exercises", "register")
    op.drop_column("exercises", "target_length")
    op.drop_column("exercises", "prompt_vi_hash")
    op.drop_column("exercises", "prompt_vi")
    op.drop_column("exercises", "context")
    op.drop_column("exercises", "subtopic")
    op.drop_column("exercises", "topic")
    op.drop_column("exercises", "exercise_type")
    # ### end Alembic commands ###
