"""initial schema

Revision ID: 95ac7b968251
Revises:
Create Date: 2026-08-18 06:04:37.280641

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "95ac7b968251"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_provider_configs",
        sa.Column("provider_name", sa.String(length=50), nullable=False),
        sa.Column("api_key", sa.String(length=500), nullable=True),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_provider_configs_provider_name"),
        "ai_provider_configs",
        ["provider_name"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "ai_model_configs",
        sa.Column("provider_config_id", sa.String(length=36), nullable=False),
        sa.Column("model_name", sa.String(length=200), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=True),
        sa.Column("default_temperature", sa.Float(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_config_id"], ["ai_provider_configs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_model_configs_provider_config_id"),
        "ai_model_configs",
        ["provider_config_id"],
        unique=False,
    )
    op.create_table(
        "exercises",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "TRANSLATION",
                "FREE_WRITING",
                "CHALLENGE",
                name="exercisetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", name="exercisestatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exercises_user_id"), "exercises", ["user_id"], unique=False)
    op.create_table(
        "learner_profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("native_language", sa.String(length=10), nullable=False),
        sa.Column("target_level", sa.String(length=20), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column("adaptive_state", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learner_profiles_user_id"), "learner_profiles", ["user_id"], unique=True
    )
    op.create_table(
        "vocabulary",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("term", sa.String(length=100), nullable=False),
        sa.Column("reading", sa.String(length=200), nullable=True),
        sa.Column("meaning", sa.Text(), nullable=False),
        sa.Column("example_sentence", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW", "LEARNING", "MASTERED", name="vocabularystatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vocabulary_user_id"), "vocabulary", ["user_id"], unique=False)
    op.create_table(
        "exercise_attempts",
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("submitted_text", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "IN_PROGRESS",
                "SUBMITTED",
                "REVIEWED",
                name="attemptstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exercise_attempts_exercise_id"), "exercise_attempts", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_attempts_user_id"), "exercise_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "writing_feedback",
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("overall_score", sa.Integer(), nullable=True),
        sa.Column("naturalness_score", sa.Integer(), nullable=True),
        sa.Column("grammar_notes", sa.Text(), nullable=True),
        sa.Column("vocabulary_notes", sa.Text(), nullable=True),
        sa.Column("semantic_notes", sa.Text(), nullable=True),
        sa.Column("correct_rewrite", sa.Text(), nullable=True),
        sa.Column("natural_rewrite", sa.Text(), nullable=True),
        sa.Column("native_rewrite", sa.Text(), nullable=True),
        sa.Column("raw_analysis", sa.JSON(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["exercise_attempts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_writing_feedback_attempt_id"), "writing_feedback", ["attempt_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_writing_feedback_attempt_id"), table_name="writing_feedback")
    op.drop_table("writing_feedback")
    op.drop_index(op.f("ix_exercise_attempts_user_id"), table_name="exercise_attempts")
    op.drop_index(op.f("ix_exercise_attempts_exercise_id"), table_name="exercise_attempts")
    op.drop_table("exercise_attempts")
    op.drop_index(op.f("ix_vocabulary_user_id"), table_name="vocabulary")
    op.drop_table("vocabulary")
    op.drop_index(op.f("ix_learner_profiles_user_id"), table_name="learner_profiles")
    op.drop_table("learner_profiles")
    op.drop_index(op.f("ix_exercises_user_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_ai_model_configs_provider_config_id"), table_name="ai_model_configs")
    op.drop_table("ai_model_configs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_ai_provider_configs_provider_name"), table_name="ai_provider_configs")
    op.drop_table("ai_provider_configs")
    # ### end Alembic commands ###
