"""vocabulary bank: entries + user state + discoveries

Revision ID: 6a21be1edd1a
Revises: 138d1e52a583
Create Date: 2026-08-18 10:01:43.665113

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "6a21be1edd1a"
down_revision: str | None = "138d1e52a583"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vocabulary_entries",
        sa.Column("expression", sa.String(length=100), nullable=False),
        sa.Column("normalized_expression", sa.String(length=255), nullable=False),
        sa.Column("reading", sa.String(length=200), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "WORD",
                "EXPRESSION",
                "COLLOCATION",
                name="vocabularytype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("meaning_vi", sa.Text(), nullable=False),
        sa.Column("part_of_speech", sa.String(length=50), nullable=True),
        sa.Column("estimated_jlpt_level", sa.String(length=8), nullable=True),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("register", sa.String(length=20), nullable=True),
        sa.Column("usage_context", sa.String(length=100), nullable=True),
        sa.Column("example_sentence", sa.Text(), nullable=False),
        sa.Column("natural_alternatives", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "HIGH", "MEDIUM", "LOW", name="vocabularyconfidence", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vocabulary_entries_normalized_expression"),
        "vocabulary_entries",
        ["normalized_expression"],
        unique=True,
    )
    op.create_table(
        "user_vocabulary",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("discovered_count", sa.Integer(), nullable=False),
        sa.Column("seen_count", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("incorrect_count", sa.Integer(), nullable=False),
        sa.Column("correct_usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "familiarity",
            sa.Enum(
                "NEW",
                "LEARNING",
                "FAMILIAR",
                "STRONG",
                name="vocabularyfamiliarity",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("source_exercise_id", sa.String(length=36), nullable=True),
        sa.Column("user_expression", sa.String(length=200), nullable=True),
        sa.Column("learning_reason", sa.Text(), nullable=False),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entry_id"], ["vocabulary_entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_attempt_id"], ["exercise_attempts.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["source_exercise_id"], ["exercises.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "entry_id", name="uq_user_vocabulary_entry"),
    )
    op.create_index(
        op.f("ix_user_vocabulary_entry_id"), "user_vocabulary", ["entry_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_vocabulary_user_id"), "user_vocabulary", ["user_id"], unique=False
    )
    op.create_table(
        "vocabulary_discoveries",
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "USER_ANSWER",
                "AI_CORRECTION",
                "AI_NATURAL",
                "AI_NATIVE",
                "AI_REGISTER_VARIANT",
                "AI_EXPLANATION",
                name="vocabularysourcetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("user_expression", sa.String(length=200), nullable=True),
        sa.Column("learning_reason", sa.Text(), nullable=False),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.Column("example_sentence", sa.Text(), nullable=True),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["attempt_id"], ["exercise_attempts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entry_id"], ["vocabulary_entries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vocabulary_discoveries_attempt_id"),
        "vocabulary_discoveries",
        ["attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vocabulary_discoveries_entry_id"),
        "vocabulary_discoveries",
        ["entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vocabulary_discoveries_exercise_id"),
        "vocabulary_discoveries",
        ["exercise_id"],
        unique=False,
    )
    op.drop_constraint("vocabulary_ibfk_1", "vocabulary", type_="foreignkey")
    op.drop_table("vocabulary")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vocabulary",
        sa.Column(
            "user_id", mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36), nullable=False
        ),
        sa.Column(
            "term", mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100), nullable=False
        ),
        sa.Column(
            "reading", mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=200), nullable=True
        ),
        sa.Column("meaning", mysql.TEXT(collation="utf8mb4_unicode_ci"), nullable=False),
        sa.Column("example_sentence", mysql.TEXT(collation="utf8mb4_unicode_ci"), nullable=True),
        sa.Column(
            "status", mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32), nullable=False
        ),
        sa.Column("id", mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=36), nullable=False),
        sa.Column(
            "created_at", mysql.DATETIME(), server_default=sa.text("(now())"), nullable=False
        ),
        sa.Column(
            "updated_at", mysql.DATETIME(), server_default=sa.text("(now())"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("vocabulary_ibfk_1"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_vocabulary_user_id"), "vocabulary", ["user_id"], unique=False)
    op.drop_index(
        op.f("ix_vocabulary_discoveries_exercise_id"), table_name="vocabulary_discoveries"
    )
    op.drop_index(op.f("ix_vocabulary_discoveries_entry_id"), table_name="vocabulary_discoveries")
    op.drop_index(op.f("ix_vocabulary_discoveries_attempt_id"), table_name="vocabulary_discoveries")
    op.drop_table("vocabulary_discoveries")
    op.drop_index(op.f("ix_user_vocabulary_user_id"), table_name="user_vocabulary")
    op.drop_index(op.f("ix_user_vocabulary_entry_id"), table_name="user_vocabulary")
    op.drop_table("user_vocabulary")
    op.drop_index(
        op.f("ix_vocabulary_entries_normalized_expression"), table_name="vocabulary_entries"
    )
    op.drop_table("vocabulary_entries")
    # ### end Alembic commands ###
