# -*- coding: utf-8 -*-
"""Sonkeigo data definitions (99 entries total across 5 formulas):
1. sonkeigo_irregular: 25 entries
2. sonkeigo_o_ni_naru: 20 entries
3. sonkeigo_passive: 18 entries
4. sonkeigo_go_ni_naru: 18 entries
5. sonkeigo_kudasai: 18 entries
"""

from __future__ import annotations

# Helper dictionary representation so it can easily be serialized into KeigoWordEntry
SONKEIGO_IRREGULAR_DATA = [
    {
        "source_word": "する",
        "source_reading": "する",
        "meaning_vi": "làm (đối tác / cấp trên làm)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "なさる",
        "canonical_reading": "なさる",
        "acceptable_variants": ["なさる", "なさいます", "なさって", "なされる", "なされます"],
        "triplet_sonkeigo": "なさる",
        "triplet_kenjougo": "いたす",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Dạng tôn kính đặc biệt của する, dùng khi nói về hành động làm của sếp hoặc đối tác.",
        "example_ja": "社長は何時頃ご出社なさいますか。",
        "example_vi": "Giám đốc khoảng mấy giờ thì đến công ty ạ?",
    },
    {
        "source_word": "行く",
        "source_reading": "いく",
        "meaning_vi": "đi (đối tác / cấp trên đi)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "いらっしゃる",
        "canonical_reading": "いらっしゃる",
        "acceptable_variants": ["いらっしゃる", "いらっしゃいます", "おいでになる", "おいでになります", "いらして"],
        "triplet_sonkeigo": "いらっしゃる",
        "triplet_kenjougo": "参る",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ bất quy tắc chung của 行く・来る・居る.",
        "example_ja": "明日はどちらへいらっしゃいますか。",
        "example_vi": "Ngày mai ngài đi đâu vậy ạ?",
    },
    {
        "source_word": "来る",
        "source_reading": "くる",
        "meaning_vi": "đến (đối tác / cấp trên đến)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "いらっしゃる",
        "canonical_reading": "いらっしゃる",
        "acceptable_variants": ["いらっしゃる", "いらっしゃいます", "お越しになる", "お越しになります", "お見えになる", "お見えになります"],
        "triplet_sonkeigo": "いらっしゃる",
        "triplet_kenjougo": "参る",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ chỉ hành động đến của khách hoặc đối tác.",
        "example_ja": "山田部長がいらっしゃいました。",
        "example_vi": "Trưởng phòng Yamada đã đến rồi ạ.",
    },
    {
        "source_word": "居る",
        "source_reading": "いる",
        "meaning_vi": "ở / có mặt (đối tác / cấp trên có mặt)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "いらっしゃる",
        "canonical_reading": "いらっしゃる",
        "acceptable_variants": ["いらっしゃる", "いらっしゃいます", "おいでになる", "おいでになります"],
        "triplet_sonkeigo": "いらっしゃる",
        "triplet_kenjougo": "おる",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Dạng tôn kính ngữ đặc biệt chỉ sự hiện diện, có mặt của cấp trên.",
        "example_ja": "鈴木様は今、お席にいらっしゃいますか。",
        "example_vi": "Ngài Suzuki hiện có đang ở bàn làm việc không ạ?",
    },
    {
        "source_word": "行く(おいで)",
        "source_reading": "いく",
        "meaning_vi": "đi (cách nói trang nhã)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "おいでになる",
        "canonical_reading": "おいでになる",
        "acceptable_variants": ["おいでになる", "おいでになる", "おいでになります", "おいでになって"],
        "triplet_sonkeigo": "おいでになる",
        "triplet_kenjougo": "参る",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Biến thể tôn kính rất trang nhã của 行く/来る/いる.",
        "example_ja": "会場へはおいでになりますか。",
        "example_vi": "Ngài có đến hội trường không ạ?",
    },
    {
        "source_word": "来る(お越し)",
        "source_reading": "くる",
        "meaning_vi": "đến / ghé qua (trang trọng)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お越しになる",
        "canonical_reading": "おこしになる",
        "acceptable_variants": ["お越しになる", "おこしになる", "お越しになります", "おこしになります", "お越しいただき"],
        "triplet_sonkeigo": "お越しになる",
        "triplet_kenjougo": "参る",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Dùng cực kỳ phổ biến trong tiếp đón khách hàng và đối tác đến công ty.",
        "example_ja": "わざわざ遠方よりお越しになり、ありがとうございます。",
        "example_vi": "Cảm ơn quý khách đã cất công từ xa đến đây ạ.",
    },
    {
        "source_word": "来る(お見え)",
        "source_reading": "くる",
        "meaning_vi": "xuất hiện / đến nơi",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お見えになる",
        "canonical_reading": "おみえになる",
        "acceptable_variants": ["お見えになる", "おみえになる", "お見えになります", "おみえになります", "お見えになりました"],
        "triplet_sonkeigo": "お見えになる",
        "triplet_kenjougo": "参る",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thường dùng để thông báo khách đã tới sảnh hoặc văn phòng.",
        "example_ja": "お客様がお見えになりました。",
        "example_vi": "Quý khách đã tới rồi ạ.",
    },
    {
        "source_word": "言う",
        "source_reading": "いう",
        "meaning_vi": "nói (cấp trên / khách hàng nói)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "おっしゃる",
        "canonical_reading": "おっしゃる",
        "acceptable_variants": ["おっしゃる", "おっしゃいます", "おっしゃって", "言われる", "言われます"],
        "triplet_sonkeigo": "おっしゃる",
        "triplet_kenjougo": "申す",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ đặc biệt của 言う, chỉ lời nói của người bề trên.",
        "example_ja": "部長は何とおっしゃいましたか。",
        "example_vi": "Trưởng phòng đã nói điều gì thế ạ?",
    },
    {
        "source_word": "食べる",
        "source_reading": "たべる",
        "meaning_vi": "ăn (mời sếp / khách ăn)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "召し上がる",
        "canonical_reading": "めしあがる",
        "acceptable_variants": ["召し上がる", "めしあがる", "召し上がります", "めしあがります", "召し上がって"],
        "triplet_sonkeigo": "召し上がる",
        "triplet_kenjougo": "いただく",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 食べる và 飲む.",
        "example_ja": "どうぞ温かいうちに召し上がってください。",
        "example_vi": "Xin mời ngài dùng bữa khi còn nóng ạ.",
    },
    {
        "source_word": "飲む",
        "source_reading": "のむ",
        "meaning_vi": "uống (mời sếp / khách uống)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "召し上がる",
        "canonical_reading": "めしあがる",
        "acceptable_variants": ["召し上がる", "めしあがる", "召し上がります", "めしあがります"],
        "triplet_sonkeigo": "召し上がる",
        "triplet_kenjougo": "いただく",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của cả ăn và uống.",
        "example_ja": "お茶を召し上がりますか。",
        "example_vi": "Ngài có dùng trà không ạ?",
    },
    {
        "source_word": "見る",
        "source_reading": "みる",
        "meaning_vi": "xem / nhìn (khách / sếp xem)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご覧になる",
        "canonical_reading": "ごらんになる",
        "acceptable_variants": ["ご覧になる", "ごらんになる", "ご覧になります", "ごらんになります", "ご覧になって"],
        "triplet_sonkeigo": "ご覧になる",
        "triplet_kenjougo": "拝見する",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 見る.",
        "example_ja": "こちらの資料をご覧になりましたか。",
        "example_vi": "Ngài đã xem tài liệu này chưa ạ?",
    },
    {
        "source_word": "知る",
        "source_reading": "しる",
        "meaning_vi": "biết (đối tác / sếp biết)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご存知だ",
        "canonical_reading": "ごぞんじだ",
        "acceptable_variants": ["ご存知だ", "ごぞんじだ", "ご存知です", "ごぞんじです", "ご存知でいらっしゃる", "ご存じです"],
        "triplet_sonkeigo": "ご存知だ",
        "triplet_kenjougo": "存じる",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 知っている.",
        "example_ja": "その件はすでにご存知ですか。",
        "example_vi": "Ngài đã biết chuyện đó chưa ạ?",
    },
    {
        "source_word": "くれる",
        "source_reading": "くれる",
        "meaning_vi": "cho / tặng (người trên tặng mình)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "くださる",
        "canonical_reading": "くださる",
        "acceptable_variants": ["くださる", "くださいます", "くださって", "くださいました"],
        "triplet_sonkeigo": "くださる",
        "triplet_kenjougo": "いただく",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của くれる (ai đó cho mình cái gì).",
        "example_ja": "先生が本をくださいました。",
        "example_vi": "Thầy giáo đã tặng sách cho tôi ạ.",
    },
    {
        "source_word": "寝る",
        "source_reading": "ねる",
        "meaning_vi": "ngủ / nghỉ ngơi",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お休みになる",
        "canonical_reading": "おやすみになる",
        "acceptable_variants": ["お休みになる", "おやすみになる", "お休みになります", "おやすみになります"],
        "triplet_sonkeigo": "お休みになる",
        "triplet_kenjougo": None,
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 寝る.",
        "example_ja": "部長はもうお休みになりました。",
        "example_vi": "Trưởng phòng đã đi nghỉ rồi ạ.",
    },
    {
        "source_word": "着る",
        "source_reading": "きる",
        "meaning_vi": "mặc (quần áo / áo khoác)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お召しになる",
        "canonical_reading": "おめしになる",
        "acceptable_variants": ["お召しになる", "おめしになる", "お召しになります", "おめしになります"],
        "triplet_sonkeigo": "お召しになる",
        "triplet_kenjougo": None,
        "category": "sonkeigo_irregular",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ đặc biệt của 着る (mặc đồ).",
        "example_ja": "素敵なコートをお召しになっていますね。",
        "example_vi": "Ngài đang mặc chiếc áo khoác đẹp quá ạ.",
    },
    {
        "source_word": "死ぬ",
        "source_reading": "しぬ",
        "meaning_vi": "qua đời / mất",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お亡くなりになる",
        "canonical_reading": "おなくなりになる",
        "acceptable_variants": ["お亡くなりになる", "おなくなりになる", "お亡くなりになります", "お亡くなりになりました"],
        "triplet_sonkeigo": "お亡くなりになる",
        "triplet_kenjougo": None,
        "category": "sonkeigo_irregular",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Cách nói trang trọng, tránh né từ 死ぬ khi nói về người đã khuất.",
        "example_ja": "会長は先月、お亡くなりになりました。",
        "example_vi": "Chủ tịch đã qua đời vào tháng trước ạ.",
    },
    {
        "source_word": "会う",
        "source_reading": "あう",
        "meaning_vi": "gặp gỡ (sếp / khách gặp ai)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お会いになる",
        "canonical_reading": "おあいになる",
        "acceptable_variants": ["お会いになる", "おあいになる", "お会いになります", "おあいになります"],
        "triplet_sonkeigo": "お会いになる",
        "triplet_kenjougo": "お目にかかる",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 会う (chú ý phân biệt với khiêm nhường お目にかかる).",
        "example_ja": "社長はすでにその方とお会いになりました。",
        "example_vi": "Giám đốc đã gặp vị đó rồi ạ.",
    },
    {
        "source_word": "座る",
        "source_reading": "すわる",
        "meaning_vi": "ngồi xuống ghế",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お掛けになる",
        "canonical_reading": "おかけになる",
        "acceptable_variants": ["お掛けになる", "おかけになる", "お掛けになります", "おかけになります"],
        "triplet_sonkeigo": "お掛けになる",
        "triplet_kenjougo": None,
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ chuẩn của 座る trong công sở.",
        "example_ja": "どうぞソファにお掛けになってお待ちください。",
        "example_vi": "Xin mời ngài ngồi ghế sofa đợi một lát ạ.",
    },
    {
        "source_word": "買う",
        "source_reading": "かう",
        "meaning_vi": "mua sắm (khách hàng mua)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お求めになる",
        "canonical_reading": "おもとめになる",
        "acceptable_variants": ["お求めになる", "おもとめになる", "お求めになります", "おもとめになります", "お買い求めになる"],
        "triplet_sonkeigo": "お求めになる",
        "triplet_kenjougo": None,
        "category": "sonkeigo_irregular",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ thương mại chuẩn khi khách hàng mua hàng hóa.",
        "example_ja": "どちらの商品をお求めになりますか。",
        "example_vi": "Quý khách chọn mua sản phẩm nào ạ?",
    },
    {
        "source_word": "聞く",
        "source_reading": "きく",
        "meaning_vi": "nghe / hỏi (sếp hỏi thăm)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お聞きになる",
        "canonical_reading": "おききになる",
        "acceptable_variants": ["お聞きになる", "おききになる", "お聞きになります", "おききになります", "お尋ねになる"],
        "triplet_sonkeigo": "お聞きになる",
        "triplet_kenjougo": "伺う",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi sếp hỏi hoặc lắng nghe.",
        "example_ja": "そのニュースをお聞きになりましたか。",
        "example_vi": "Ngài đã nghe tin tức đó chưa ạ?",
    },
    {
        "source_word": "考える",
        "source_reading": "かんがえる",
        "meaning_vi": "suy nghĩ / cân nhắc",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お考えになる",
        "canonical_reading": "おかんがえになる",
        "acceptable_variants": ["お考えになる", "おかんがえになる", "お考えになります", "おかんがえになります"],
        "triplet_sonkeigo": "お考えになる",
        "triplet_kenjougo": "存じ上げる",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi cấp trên hoặc đối tác cân nhắc suy nghĩ.",
        "example_ja": "今後の計画についてどうお考えになりますか。",
        "example_vi": "Ngài suy nghĩ thế nào về kế hoạch sắp tới ạ?",
    },
    {
        "source_word": "思う",
        "source_reading": "おもう",
        "meaning_vi": "nghĩ rằng / cảm thấy",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お思いになる",
        "canonical_reading": "おおもいになる",
        "acceptable_variants": ["お思いになる", "おおもいになる", "お思いになります", "おおもいになります", "思し召す"],
        "triplet_sonkeigo": "お思いになる",
        "triplet_kenjougo": "存じる",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 思う.",
        "example_ja": "その点についてどうお思いになりますか。",
        "example_vi": "Ngài cảm thấy thế nào về điểm đó ạ?",
    },
    {
        "source_word": "分かる",
        "source_reading": "わかる",
        "meaning_vi": "hiểu / nắm rõ",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お分かりになる",
        "canonical_reading": "おわかりになる",
        "acceptable_variants": ["お分かりになる", "おわかりになる", "お分かりになります", "おわかりになります", "ご理解になる"],
        "triplet_sonkeigo": "お分かりになる",
        "triplet_kenjougo": "承知する",
        "category": "sonkeigo_irregular",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Dùng khi hỏi sếp hoặc khách hàng đã hiểu nội dung chưa.",
        "example_ja": "使い方はお分かりになりましたでしょうか。",
        "example_vi": "Ngài đã hiểu cách sử dụng chưa ạ?",
    },
    {
        "source_word": "気に入る",
        "source_reading": "きにいる",
        "meaning_vi": "vừa ý / hài lòng (khách thích)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お気に召す",
        "canonical_reading": "おきにめす",
        "acceptable_variants": ["お気に召す", "おきにめす", "お気に召します", "おきにめします"],
        "triplet_sonkeigo": "お気に召す",
        "triplet_kenjougo": None,
        "category": "sonkeigo_irregular",
        "jlpt_level": "N2",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ cổ điển rất quý phái, dùng nhiều trong ngành dịch vụ cao cấp.",
        "example_ja": "料理はお気に召しましたでしょうか。",
        "example_vi": "Các món ăn có vừa miệng quý khách không ạ?",
    },
    {
        "source_word": "風邪を引く",
        "source_reading": "かぜをひく",
        "meaning_vi": "bị cảm lạnh",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お風邪を召す",
        "canonical_reading": "おかぜをめす",
        "acceptable_variants": ["お風邪を召す", "おかぜをめす", "お風邪を召します", "お風邪を召されました"],
        "triplet_sonkeigo": "お風邪を召す",
        "triplet_kenjougo": None,
        "category": "sonkeigo_irregular",
        "jlpt_level": "N2",
        "formula_id": "sonkeigo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Cách nói tôn kính trang nhã khi người trên bị cảm sốt.",
        "example_ja": "お風邪を召されませんようご自愛ください。",
        "example_vi": "Xin ngài hãy giữ gìn sức khỏe kẻo bị cảm lạnh ạ.",
    },
]

# 2. sonkeigo_o_ni_naru: 20 entries
SONKEIGO_O_NI_NARU_DATA = [
    {
        "source_word": "書く",
        "source_reading": "かく",
        "meaning_vi": "viết (sếp / khách viết)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お書きになる",
        "canonical_reading": "おかきになる",
        "acceptable_variants": ["お書きになる", "おかきになる", "お書きになります", "おかきになります"],
        "triplet_sonkeigo": "お書きになる",
        "triplet_kenjougo": "お書きする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Công thức tôn kính quy tắc chuẩn nhất: お + Động từ nhóm 1 & 2 thể Masu bỏ Masu + になる.",
        "example_ja": "先生はこちらの用紙にお書きになります。",
        "example_vi": "Thầy giáo sẽ viết vào tờ giấy này ạ.",
    },
    {
        "source_word": "読む",
        "source_reading": "よむ",
        "meaning_vi": "đọc (khách / sếp đọc)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お読みになる",
        "canonical_reading": "およみになる",
        "acceptable_variants": ["お読みになる", "およみになる", "お読みになります", "およみになります"],
        "triplet_sonkeigo": "お読みになる",
        "triplet_kenjougo": "拝読する",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Công thức お + stem + になる cho 読む.",
        "example_ja": "その本をお読みになりましたか。",
        "example_vi": "Ngài đã đọc cuốn sách đó chưa ạ?",
    },
    {
        "source_word": "待つ",
        "source_reading": "まつ",
        "meaning_vi": "chờ đợi",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お待ちになる",
        "canonical_reading": "おまちになる",
        "acceptable_variants": ["お待ちになる", "おまちになる", "お待ちになります", "おまちになります"],
        "triplet_sonkeigo": "お待ちになる",
        "triplet_kenjougo": "お待ちする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Công thức お + stem + になる cho 待つ.",
        "example_ja": "ロビーでお待ちになりますか。",
        "example_vi": "Ngài sẽ chờ ở sảnh chứ ạ?",
    },
    {
        "source_word": "使う",
        "source_reading": "つかう",
        "meaning_vi": "sử dụng",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お使いになる",
        "canonical_reading": "おつかいになる",
        "acceptable_variants": ["お使いになる", "おつかいになる", "お使いになります", "おつかいになります"],
        "triplet_sonkeigo": "お使いになる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 使う.",
        "example_ja": "どちらのパソコンをお使いになりますか。",
        "example_vi": "Ngài sử dụng chiếc máy tính nào ạ?",
    },
    {
        "source_word": "帰る",
        "source_reading": "かえる",
        "meaning_vi": "về nhà / về công ty",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お帰りになる",
        "canonical_reading": "おかえりになる",
        "acceptable_variants": ["お帰りになる", "おかえりになる", "お帰りになります", "おかえりになります"],
        "triplet_sonkeigo": "お帰りになる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ chỉ hành động về của sếp.",
        "example_ja": "部長は先ほどお帰りになりました。",
        "example_vi": "Trưởng phòng vừa mới về rồi ạ.",
    },
    {
        "source_word": "話す",
        "source_reading": "はなす",
        "meaning_vi": "nói chuyện / trò chuyện",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お話しになる",
        "canonical_reading": "おはなしになる",
        "acceptable_variants": ["お話しになる", "おはなしになる", "お話しになります", "おはなしになります"],
        "triplet_sonkeigo": "お話しになる",
        "triplet_kenjougo": "お話しする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 話す.",
        "example_ja": "社長が詳しくお話しになりました。",
        "example_vi": "Giám đốc đã nói chuyện rất chi tiết ạ.",
    },
    {
        "source_word": "決める",
        "source_reading": "きめる",
        "meaning_vi": "quyết định",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お決めになる",
        "canonical_reading": "おきめになる",
        "acceptable_variants": ["お決めになる", "おきめになる", "お決めになります", "おきめになります"],
        "triplet_sonkeigo": "お決めになる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 決める.",
        "example_ja": "日程はお決めになりましたか。",
        "example_vi": "Ngài đã quyết định ngày giờ chưa ạ?",
    },
    {
        "source_word": "泊まる",
        "source_reading": "とまる",
        "meaning_vi": "nghỉ trọ / qua đêm",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お泊まりになる",
        "canonical_reading": "おとまりになる",
        "acceptable_variants": ["お泊まりになる", "おとまりになる", "お泊まりになります", "おとまりになります"],
        "triplet_sonkeigo": "お泊まりになる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 泊まる trong khách sạn.",
        "example_ja": "本日はどちらにお泊まりになりますか。",
        "example_vi": "Hôm nay ngài sẽ nghỉ trọ ở đâu ạ?",
    },
    {
        "source_word": "呼ぶ",
        "source_reading": "よぶ",
        "meaning_vi": "gọi điện / gọi ai đó",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お呼びになる",
        "canonical_reading": "およびになる",
        "acceptable_variants": ["お呼びになる", "およびになる", "お呼びになります", "およびになります"],
        "triplet_sonkeigo": "お呼びになる",
        "triplet_kenjougo": "お呼びする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi sếp gọi ai đó vào phòng.",
        "example_ja": "部長が田中君をお呼びになりました。",
        "example_vi": "Trưởng phòng đã gọi cậu Tanaka vào ạ.",
    },
    {
        "source_word": "送る",
        "source_reading": "おくる",
        "meaning_vi": "gửi (hàng hóa / email)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お送りになる",
        "canonical_reading": "おおくりになる",
        "acceptable_variants": ["お送りになる", "おおくりになる", "お送りになります", "おおくりになります"],
        "triplet_sonkeigo": "お送りになる",
        "triplet_kenjougo": "お送りする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi đối tác gửi tài liệu.",
        "example_ja": "資料はメールでお送りになりますか。",
        "example_vi": "Ngài sẽ gửi tài liệu qua email chứ ạ?",
    },
    {
        "source_word": "届ける",
        "source_reading": "とどける",
        "meaning_vi": "chuyển phát / đem tới",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お届けになる",
        "canonical_reading": "おとどけになる",
        "acceptable_variants": ["お届けになる", "おとどけになる", "お届けになります", "おとどけになります"],
        "triplet_sonkeigo": "お届けになる",
        "triplet_kenjougo": "お届けする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 届ける.",
        "example_ja": "書類をご自身でお届けになりますか。",
        "example_vi": "Ngài sẽ đích thân đem tài liệu tới ạ?",
    },
    {
        "source_word": "探す",
        "source_reading": "さがす",
        "meaning_vi": "tìm kiếm",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お探しになる",
        "canonical_reading": "おさがしになる",
        "acceptable_variants": ["お探しになる", "おさがしになる", "お探しになります", "おさがしになります"],
        "triplet_sonkeigo": "お探しになる",
        "triplet_kenjougo": "お探しする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi khách tìm kiếm đồ gì đó.",
        "example_ja": "何をお探しになりますか。",
        "example_vi": "Ngài đang tìm món đồ gì vậy ạ?",
    },
    {
        "source_word": "取る",
        "source_reading": "とる",
        "meaning_vi": "lấy / cầm",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お取りになる",
        "canonical_reading": "おとりになる",
        "acceptable_variants": ["お取りになる", "おとりになる", "お取りになります", "おとりになります"],
        "triplet_sonkeigo": "お取りになる",
        "triplet_kenjougo": "お取りする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 取る.",
        "example_ja": "パンフレットをお取りになりましたか。",
        "example_vi": "Ngài đã lấy cuốn tài liệu giới thiệu chưa ạ?",
    },
    {
        "source_word": "買う(quy tắc)",
        "source_reading": "かう",
        "meaning_vi": "mua hàng (dạng theo quy tắc)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お買いになる",
        "canonical_reading": "おかいになる",
        "acceptable_variants": ["お買いになる", "おかいになる", "お買いになります", "おかいになります"],
        "triplet_sonkeigo": "お買いになる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ quy tắc của 買う.",
        "example_ja": "どちらの車をお買いになりますか。",
        "example_vi": "Ngài sẽ mua chiếc xe nào ạ?",
    },
    {
        "source_word": "渡す",
        "source_reading": "わたす",
        "meaning_vi": "trao / đưa cho ai",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お渡しになる",
        "canonical_reading": "おわたしになる",
        "acceptable_variants": ["お渡しになる", "おわたしになる", "お渡しになります", "おわたしになります"],
        "triplet_sonkeigo": "お渡しになる",
        "triplet_kenjougo": "お渡しする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 渡す.",
        "example_ja": "名刺をお渡しになりましたか。",
        "example_vi": "Ngài đã trao danh thiếp chưa ạ?",
    },
    {
        "source_word": "調べる",
        "source_reading": "しらべる",
        "meaning_vi": "tra cứu / điều tra",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お調べになる",
        "canonical_reading": "おしらべになる",
        "acceptable_variants": ["お調べになる", "おしらべになる", "お調べになります", "おしらべになります"],
        "triplet_sonkeigo": "お調べになる",
        "triplet_kenjougo": "お調べする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 調べる.",
        "example_ja": "先生が事前にお調べになりました。",
        "example_vi": "Thầy giáo đã tra cứu trước rồi ạ.",
    },
    {
        "source_word": "楽しむ",
        "source_reading": "たのしむ",
        "meaning_vi": "thưởng thức / tận hưởng",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お楽しみになる",
        "canonical_reading": "おたのしみになる",
        "acceptable_variants": ["お楽しみになる", "おたのしみになる", "お楽しみになります", "おたのしみになります"],
        "triplet_sonkeigo": "お楽しみになる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 楽しむ.",
        "example_ja": "日本の旅をお楽しみになりましたか。",
        "example_vi": "Ngài đã tận hưởng chuyến đi Nhật Bản chứ ạ?",
    },
    {
        "source_word": "歩く",
        "source_reading": "あるく",
        "meaning_vi": "đi bộ",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お歩きになる",
        "canonical_reading": "おあるきになる",
        "acceptable_variants": ["お歩きになる", "おあるきになる", "お歩きになります", "おあるきになります"],
        "triplet_sonkeigo": "お歩きになる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 歩く.",
        "example_ja": "駅までお歩きになりますか。",
        "example_vi": "Ngài sẽ đi bộ ra ga chứ ạ?",
    },
    {
        "source_word": "急ぐ",
        "source_reading": "いそぐ",
        "meaning_vi": "vội vã / gấp gáp",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お急ぎになる",
        "canonical_reading": "おいそぎになる",
        "acceptable_variants": ["お急ぎになる", "おいそぎになる", "お急ぎになります", "おいそぎになります"],
        "triplet_sonkeigo": "お急ぎになる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 急ぐ.",
        "example_ja": "なぜそんなにお急ぎになりますか。",
        "example_vi": "Sao ngài lại vội vàng thế ạ?",
    },
    {
        "source_word": "手伝う",
        "source_reading": "てつだう",
        "meaning_vi": "giúp đỡ (sếp giúp việc gì đó)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お手伝いになる",
        "canonical_reading": "おてつだいになる",
        "acceptable_variants": ["お手伝いになる", "おてつだいになる", "お手伝いになります", "おてつだいになります"],
        "triplet_sonkeigo": "お手伝いになる",
        "triplet_kenjougo": "お手伝いする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_o_ni_naru",
        "formula": "お + V(stem) + になる / になります",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi cấp trên chủ động giúp một việc.",
        "example_ja": "先生もお手伝いになりました。",
        "example_vi": "Thầy giáo cũng đã tham gia giúp đỡ ạ.",
    },
]

# 3. sonkeigo_passive: 18 entries
SONKEIGO_PASSIVE_DATA = [
    {
        "source_word": "書く(bị động)",
        "source_reading": "かく",
        "meaning_vi": "viết (tôn kính thể bị động nhẹ nhàng)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "書かれる",
        "canonical_reading": "かかれる",
        "acceptable_variants": ["書かれる", "かかれる", "書かれます", "かかれます"],
        "triplet_sonkeigo": "書かれる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Dạng bị động (受身形) dùng làm tôn kính ngữ với mức độ tôn trọng nhẹ hơn お〜になる, rất tự nhiên trong văn nói hàng ngày.",
        "example_ja": "部長がこの報告書を書かれました。",
        "example_vi": "Trưởng phòng đã viết bản báo cáo này ạ.",
    },
    {
        "source_word": "読む(bị động)",
        "source_reading": "よむ",
        "meaning_vi": "đọc (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "読まれる",
        "canonical_reading": "よまれる",
        "acceptable_variants": ["読まれる", "よまれる", "読まれます", "よまれます"],
        "triplet_sonkeigo": "読まれる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 読む.",
        "example_ja": "社長は毎日新聞を読まれます。",
        "example_vi": "Giám đốc mỗi ngày đều đọc báo ạ.",
    },
    {
        "source_word": "待つ(bị động)",
        "source_reading": "まつ",
        "meaning_vi": "chờ đợi (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "待たれる",
        "canonical_reading": "またれる",
        "acceptable_variants": ["待たれる", "またれる", "待たれます", "またれます"],
        "triplet_sonkeigo": "待たれる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 待つ.",
        "example_ja": "ロビーで待たれますか。",
        "example_vi": "Ngài đợi ở sảnh phải không ạ?",
    },
    {
        "source_word": "使う(bị động)",
        "source_reading": "つかう",
        "meaning_vi": "sử dụng (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "使われる",
        "canonical_reading": "つかわれる",
        "acceptable_variants": ["使われる", "つかわれる", "使われます", "つかわれます"],
        "triplet_sonkeigo": "使われる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 使う.",
        "example_ja": "この会議室を使われますか。",
        "example_vi": "Ngài dùng phòng họp này chứ ạ?",
    },
    {
        "source_word": "帰る(bị động)",
        "source_reading": "かえる",
        "meaning_vi": "về (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "帰られる",
        "canonical_reading": "かえられる",
        "acceptable_variants": ["帰られる", "かえられる", "帰られます", "かえられます"],
        "triplet_sonkeigo": "帰られる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 帰る.",
        "example_ja": "課長はもう帰られました。",
        "example_vi": "Tổ trưởng đã về rồi ạ.",
    },
    {
        "source_word": "話す(bị động)",
        "source_reading": "はなす",
        "meaning_vi": "nói chuyện (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "話される",
        "canonical_reading": "はなされる",
        "acceptable_variants": ["話される", "はなされる", "話されます", "はなされます"],
        "triplet_sonkeigo": "話される",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 話す.",
        "example_ja": "先生は英語で話されました。",
        "example_vi": "Thầy giáo đã nói chuyện bằng tiếng Anh ạ.",
    },
    {
        "source_word": "食べる(bị động)",
        "source_reading": "たべる",
        "meaning_vi": "ăn (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "食べられる",
        "canonical_reading": "たべられる",
        "acceptable_variants": ["食べられる", "たべられる", "食べられます", "たべられます"],
        "triplet_sonkeigo": "食べられる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 食べる (dù có 召し上がる, dạng này vẫn được dùng khi thân thiện).",
        "example_ja": "お昼ご飯はもう食べられましたか。",
        "example_vi": "Ngài đã ăn cơm trưa chưa ạ?",
    },
    {
        "source_word": "褒める",
        "source_reading": "ほめる",
        "meaning_vi": "khen ngợi (sếp khen ai)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "褒められる",
        "canonical_reading": "ほめられる",
        "acceptable_variants": ["褒められる", "ほめられる", "褒められます", "ほめられます"],
        "triplet_sonkeigo": "褒められる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 褒める.",
        "example_ja": "社長が新入社員を褒められました。",
        "example_vi": "Giám đốc đã khen ngợi các nhân viên mới ạ.",
    },
    {
        "source_word": "始める",
        "source_reading": "はじめる",
        "meaning_vi": "bắt đầu",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "始められる",
        "canonical_reading": "はじめられる",
        "acceptable_variants": ["始められる", "はじめられる", "始められます", "はじめられます"],
        "triplet_sonkeigo": "始められる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 始める.",
        "example_ja": "何時から会議を始められますか。",
        "example_vi": "Mấy giờ thì ngài bắt đầu cuộc họp ạ?",
    },
    {
        "source_word": "決める(bị động)",
        "source_reading": "きめる",
        "meaning_vi": "quyết định (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "決められる",
        "canonical_reading": "きめられる",
        "acceptable_variants": ["決められる", "きめられる", "決められます", "きめられます"],
        "triplet_sonkeigo": "決められる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 決める.",
        "example_ja": "取締役会で決められました。",
        "example_vi": "Hội đồng quản trị đã đưa ra quyết định ạ.",
    },
    {
        "source_word": "呼ぶ(bị động)",
        "source_reading": "よぶ",
        "meaning_vi": "gọi (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "呼ばれる",
        "canonical_reading": "よばれる",
        "acceptable_variants": ["呼ばれる", "よばれる", "呼ばれます", "よばれます"],
        "triplet_sonkeigo": "呼ばれる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 呼ぶ.",
        "example_ja": "タクシーを呼ばれますか。",
        "example_vi": "Ngài có gọi taxi không ạ?",
    },
    {
        "source_word": "買う(bị động)",
        "source_reading": "かう",
        "meaning_vi": "mua (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "買われる",
        "canonical_reading": "かわれる",
        "acceptable_variants": ["買われる", "かわれる", "買われます", "かわれます"],
        "triplet_sonkeigo": "買われる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 買う.",
        "example_ja": "どちらを買われますか。",
        "example_vi": "Ngài sẽ mua chiếc nào ạ?",
    },
    {
        "source_word": "送る(bị động)",
        "source_reading": "おくる",
        "meaning_vi": "gửi (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "送られる",
        "canonical_reading": "おくられる",
        "acceptable_variants": ["送られる", "おくられる", "送られます", "おくられます"],
        "triplet_sonkeigo": "送られる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 送る.",
        "example_ja": "郵送で送られますか。",
        "example_vi": "Ngài gửi bằng đường bưu điện ạ?",
    },
    {
        "source_word": "調べる(bị động)",
        "source_reading": "しらべる",
        "meaning_vi": "tra cứu (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "調べられる",
        "canonical_reading": "しらべられる",
        "acceptable_variants": ["調べられる", "しらべられる", "調べられます", "しらべられます"],
        "triplet_sonkeigo": "調べられる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 調べる.",
        "example_ja": "先生がインターネットで調べられました。",
        "example_vi": "Thầy giáo đã tra cứu trên mạng ạ.",
    },
    {
        "source_word": "探す(bị động)",
        "source_reading": "さがす",
        "meaning_vi": "tìm kiếm (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "探される",
        "canonical_reading": "さがされる",
        "acceptable_variants": ["探される", "さがされる", "探されます", "さがされます"],
        "triplet_sonkeigo": "探される",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 探す.",
        "example_ja": "新しい物件を探されますか。",
        "example_vi": "Ngài tìm mặt bằng mới ạ?",
    },
    {
        "source_word": "開く",
        "source_reading": "ひらく",
        "meaning_vi": "mở (hội nghị / lớp học)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "開かれる",
        "canonical_reading": "ひらかれる",
        "acceptable_variants": ["開かれる", "ひらかれる", "開かれます", "ひらかれます"],
        "triplet_sonkeigo": "開かれる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 開く.",
        "example_ja": "市長がパーティーを開かれました。",
        "example_vi": "Thị trưởng đã tổ chức buổi tiệc ạ.",
    },
    {
        "source_word": "考える(bị động)",
        "source_reading": "かんがえる",
        "meaning_vi": "cân nhắc (bị động tôn kính)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "考えられる",
        "canonical_reading": "かんがえられる",
        "acceptable_variants": ["考えられる", "かんがえられる", "考えられます", "かんがえられます"],
        "triplet_sonkeigo": "考えられる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 考える.",
        "example_ja": "どのように考えられますか。",
        "example_vi": "Ngài suy nghĩ như thế nào ạ?",
    },
    {
        "source_word": "頼む",
        "source_reading": "たのむ",
        "meaning_vi": "nhờ vả / yêu cầu",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "頼まれる",
        "canonical_reading": "たのまれる",
        "acceptable_variants": ["頼まれる", "たのまれる", "頼まれます", "たのまれます"],
        "triplet_sonkeigo": "頼まれる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_passive",
        "formula": "Thể bị động: 〜れる / 〜られます",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Thể bị động tôn kính của 頼む.",
        "example_ja": "部長が外部に仕事を頼まれました。",
        "example_vi": "Trưởng phòng đã nhờ đối tác bên ngoài làm việc ạ.",
    },
]

# 4. sonkeigo_go_ni_naru: 18 entries
SONKEIGO_GO_NI_NARU_DATA = [
    {
        "source_word": "利用する",
        "source_reading": "りようする",
        "meaning_vi": "sử dụng / tận dụng (dịch vụ)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご利用になる",
        "canonical_reading": "ごりようになる",
        "acceptable_variants": ["ご利用になる", "ごりようになる", "ご利用になります", "ごりようになります"],
        "triplet_sonkeigo": "ご利用になる",
        "triplet_kenjougo": "利用いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Quy tắc tôn kính cho danh động từ Hán-Nhật (Kango): ご + Danh từ + になる.",
        "example_ja": "ホテルのジムをご利用になりますか。",
        "example_vi": "Ngài có sử dụng phòng tập của khách sạn không ạ?",
    },
    {
        "source_word": "案内する",
        "source_reading": "あんないする",
        "meaning_vi": "hướng dẫn / dẫn dắt",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご案内になる",
        "canonical_reading": "ごあんないになる",
        "acceptable_variants": ["ご案内になる", "ごあんないになる", "ご案内になります", "ごあんないになります"],
        "triplet_sonkeigo": "ご案内になる",
        "triplet_kenjougo": "ご案内いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi sếp hoặc hướng dẫn viên dẫn đoàn.",
        "example_ja": "会長が直々にご案内になります。",
        "example_vi": "Chủ tịch sẽ đích thân hướng dẫn quý vị ạ.",
    },
    {
        "source_word": "連絡する",
        "source_reading": "れんらくする",
        "meaning_vi": "liên lạc / thông báo",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご連絡になる",
        "canonical_reading": "ごれんらくになる",
        "acceptable_variants": ["ご連絡になる", "ごれんらくになる", "ご連絡になります", "ごれんらくになります"],
        "triplet_sonkeigo": "ご連絡になる",
        "triplet_kenjougo": "ご連絡いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi khách hàng chủ động liên hệ.",
        "example_ja": "後ほどお電話でご連絡になりますか。",
        "example_vi": "Lát nữa ngài sẽ liên lạc qua điện thoại chứ ạ?",
    },
    {
        "source_word": "検討する",
        "source_reading": "けんとうする",
        "meaning_vi": "cân nhắc / xem xét (đề xuất)",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご検討になる",
        "canonical_reading": "ごけんとうになる",
        "acceptable_variants": ["ご検討になる", "ごけんとうになる", "ご検討になります", "ごけんとうになります"],
        "triplet_sonkeigo": "ご検討になる",
        "triplet_kenjougo": "検討いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ kinh điển khi đề nghị đối tác xem xét đề án.",
        "example_ja": "弊社の提案をご検討になりますか。",
        "example_vi": "Quý công ty sẽ xem xét đề xuất của bên em chứ ạ?",
    },
    {
        "source_word": "出席する",
        "source_reading": "しゅっせきする",
        "meaning_vi": "tham dự / có mặt",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご出席になる",
        "canonical_reading": "ごしゅっせきになる",
        "acceptable_variants": ["ご出席になる", "ごしゅっせきになる", "ご出席になります", "ごしゅっせきになります"],
        "triplet_sonkeigo": "ご出席になる",
        "triplet_kenjougo": "出席いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi sếp tham dự cuộc họp.",
        "example_ja": "明日の式典にご出席になりますか。",
        "example_vi": "Ngài có tham dự buổi lễ ngày mai không ạ?",
    },
    {
        "source_word": "参加する",
        "source_reading": "さんかする",
        "meaning_vi": "tham gia",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご参加になる",
        "canonical_reading": "ごさんかになる",
        "acceptable_variants": ["ご参加になる", "ごさんかになる", "ご参加になります", "ごさんかになります"],
        "triplet_sonkeigo": "ご参加になる",
        "triplet_kenjougo": "参加いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi khách tham gia sự kiện.",
        "example_ja": "セミナーにご参加になりますか。",
        "example_vi": "Ngài sẽ tham gia buổi hội thảo chứ ạ?",
    },
    {
        "source_word": "注文する",
        "source_reading": "ちゅうもんする",
        "meaning_vi": "đặt món / đặt hàng",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご注文になる",
        "canonical_reading": "ごちゅうもんになる",
        "acceptable_variants": ["ご注文になる", "ごちゅうもんになる", "ご注文になります", "ごちゅうもんになります"],
        "triplet_sonkeigo": "ご注文になる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ dùng trong nhà hàng khi khách gọi món.",
        "example_ja": "何をご注文になりますか。",
        "example_vi": "Quý khách gọi món gì ạ?",
    },
    {
        "source_word": "確認する",
        "source_reading": "かくにんする",
        "meaning_vi": "xác nhận / kiểm tra lại",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご確認になる",
        "canonical_reading": "ごかくにんになる",
        "acceptable_variants": ["ご確認になる", "ごかくにんになる", "ご確認になります", "ごかくにんになります"],
        "triplet_sonkeigo": "ご確認になる",
        "triplet_kenjougo": "確認いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi khách hàng kiểm tra lại thông tin hợp đồng.",
        "example_ja": "契約書の内容をご確認になりましたか。",
        "example_vi": "Ngài đã kiểm tra lại nội dung hợp đồng chưa ạ?",
    },
    {
        "source_word": "遠慮する",
        "source_reading": "えんりょする",
        "meaning_vi": "khách sáo / e ngại",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご遠慮になる",
        "canonical_reading": "ごえんりょになる",
        "acceptable_variants": ["ご遠慮になる", "ごえんりょになる", "ご遠慮になります", "ごえんりょになります"],
        "triplet_sonkeigo": "ご遠慮になる",
        "triplet_kenjougo": "遠慮いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 遠慮する.",
        "example_ja": "どうぞご遠慮なさらないでください。",
        "example_vi": "Xin ngài đừng khách sáo ạ.",
    },
    {
        "source_word": "理解する",
        "source_reading": "りかいする",
        "meaning_vi": "thấu hiểu / thông cảm",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご理解になる",
        "canonical_reading": "ごりかいになる",
        "acceptable_variants": ["ご理解になる", "ごりかいになる", "ご理解になります", "ごりかいになります"],
        "triplet_sonkeigo": "ご理解になる",
        "triplet_kenjougo": "理解いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi khách hàng thấu hiểu quy định.",
        "example_ja": "趣旨をご理解になりましたか。",
        "example_vi": "Ngài đã hiểu rõ tôn chỉ này chưa ạ?",
    },
    {
        "source_word": "相談する",
        "source_reading": "そうだんする",
        "meaning_vi": "thảo luận / trao đổi ý kiến",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご相談になる",
        "canonical_reading": "ごそうだんになる",
        "acceptable_variants": ["ご相談になる", "ごそうだんになる", "ご相談になります", "ごそうだんになります"],
        "triplet_sonkeigo": "ご相談になる",
        "triplet_kenjougo": "ご相談いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi sếp trao đổi với ai đó.",
        "example_ja": "弁護士にご相談になりましたか。",
        "example_vi": "Ngài đã thảo luận với luật sư chưa ạ?",
    },
    {
        "source_word": "協力する",
        "source_reading": "きょうりょくする",
        "meaning_vi": "hợp tác / phối hợp",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご協力になる",
        "canonical_reading": "ごきょうりょくになる",
        "acceptable_variants": ["ご協力になる", "ごきょうりょくになる", "ご協力になります", "ごきょうりょくになります"],
        "triplet_sonkeigo": "ご協力になる",
        "triplet_kenjougo": "協力いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 協力する.",
        "example_ja": "アンケートにご協力になりますか。",
        "example_vi": "Ngài sẽ hỗ trợ làm bảng khảo sát chứ ạ?",
    },
    {
        "source_word": "署名する",
        "source_reading": "しょめいする",
        "meaning_vi": "ký tên",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご署名になる",
        "canonical_reading": "ごしょめいになる",
        "acceptable_variants": ["ご署名になる", "ごしょめいになる", "ご署名になります", "ごしょめいになります"],
        "triplet_sonkeigo": "ご署名になる",
        "triplet_kenjougo": "署名いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi khách ký vào văn bản.",
        "example_ja": "こちらにご署名になります。",
        "example_vi": "Ngài sẽ ký tên vào đây ạ.",
    },
    {
        "source_word": "記入する",
        "source_reading": "きにゅうする",
        "meaning_vi": "điền vào biểu mẫu",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご記入になる",
        "canonical_reading": "ごきにゅうになる",
        "acceptable_variants": ["ご記入になる", "ごきにゅうになる", "ご記入になります", "ごきにゅうになります"],
        "triplet_sonkeigo": "ご記入になる",
        "triplet_kenjougo": "記入いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi khách điền thông tin.",
        "example_ja": "申込書にご記入になりましたか。",
        "example_vi": "Ngài đã điền vào đơn đăng ký chưa ạ?",
    },
    {
        "source_word": "到着する",
        "source_reading": "とうちゃくする",
        "meaning_vi": "đến nơi / đáp xuống",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご到着になる",
        "canonical_reading": "ごとうちゃくになる",
        "acceptable_variants": ["ご到着になる", "ごとうちゃくになる", "ご到着になります", "ごとうちゃくになります"],
        "triplet_sonkeigo": "ご到着になる",
        "triplet_kenjougo": "到着いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ chỉ chuyến bay hoặc xe của khách đến nơi.",
        "example_ja": "飛行機は無事にご到着になりました。",
        "example_vi": "Máy bay của quý khách đã đáp bình an rồi ạ.",
    },
    {
        "source_word": "訪問する",
        "source_reading": "ほうもんする",
        "meaning_vi": "đến thăm / ghé thăm",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご訪問になる",
        "canonical_reading": "ごほうもんになる",
        "acceptable_variants": ["ご訪問になる", "ごほうもんになる", "ご訪問になります", "ごほうもんになります"],
        "triplet_sonkeigo": "ご訪問になる",
        "triplet_kenjougo": "伺う",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi khách đến thăm công ty.",
        "example_ja": "何時に弊社をご訪問になりますか。",
        "example_vi": "Ngài sẽ ghé thăm công ty chúng tôi lúc mấy giờ ạ?",
    },
    {
        "source_word": "満足する",
        "source_reading": "まんぞくする",
        "meaning_vi": "hài lòng / thỏa mãn",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご満足になる",
        "canonical_reading": "ごまんぞくになる",
        "acceptable_variants": ["ご満足になる", "ごまんぞくになる", "ご満足になります", "ごまんぞくになります"],
        "triplet_sonkeigo": "ご満足になる",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ của 満足する.",
        "example_ja": "サービスにご満足になりましたでしょうか。",
        "example_vi": "Ngài có cảm thấy hài lòng với dịch vụ không ạ?",
    },
    {
        "source_word": "了解する",
        "source_reading": "りょうかいする",
        "meaning_vi": "chấp thuận / đồng ý",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご了解になる",
        "canonical_reading": "ごりょうかいになる",
        "acceptable_variants": ["ご了解になる", "ごりょうかいになる", "ご了解になります", "ごりょうかいになります"],
        "triplet_sonkeigo": "ご了解になる",
        "triplet_kenjougo": "承知する",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "sonkeigo_go_ni_naru",
        "formula": "ご + N(Suru) + になる / なさる",
        "subject_hint_vi": "👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        "explanation_vi": "Tôn kính ngữ khi khách đồng ý điều khoản.",
        "example_ja": "変更点をご了解になりましたでしょうか。",
        "example_vi": "Ngài đã đồng thuận với các điểm thay đổi chưa ạ?",
    },
]

# 5. sonkeigo_kudasai: 18 entries
SONKEIGO_KUDASAI_DATA = [
    {
        "source_word": "待つ(xin mời)",
        "source_reading": "まつ",
        "meaning_vi": "xin mời chờ đợi",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お待ちください",
        "canonical_reading": "おまちください",
        "acceptable_variants": ["お待ちください", "おまちください", "お待ち下さい", "少々お待ちください"],
        "triplet_sonkeigo": "お待ちください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Công thức yêu cầu lịch sự với từ thuần Nhật: お + V-stem + ください.",
        "example_ja": "少々お待ちください。",
        "example_vi": "Xin ngài vui lòng đợi trong giây lát ạ.",
    },
    {
        "source_word": "入る",
        "source_reading": "はいる",
        "meaning_vi": "xin mời vào",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お入りください",
        "canonical_reading": "おはいりください",
        "acceptable_variants": ["お入りください", "おはいりください", "お入り下さい"],
        "triplet_sonkeigo": "お入りください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Mời khách vào phòng họp.",
        "example_ja": "どうぞ中へお入りください。",
        "example_vi": "Xin mời ngài vào bên trong ạ.",
    },
    {
        "source_word": "使う(xin mời)",
        "source_reading": "つかう",
        "meaning_vi": "xin mời sử dụng",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お使いください",
        "canonical_reading": "おつかいください",
        "acceptable_variants": ["お使いください", "おつかいください", "お使い下さい"],
        "triplet_sonkeigo": "お使いください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Mời khách sử dụng tiện ích.",
        "example_ja": "こちらのペンをお使いください。",
        "example_vi": "Xin mời ngài dùng chiếc bút này ạ.",
    },
    {
        "source_word": "座る(xin mời)",
        "source_reading": "すわる",
        "meaning_vi": "xin mời ngồi",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お掛けください",
        "canonical_reading": "おかけください",
        "acceptable_variants": ["お掛けください", "おかけください", "お掛け下さい", "お座りください"],
        "triplet_sonkeigo": "お掛けください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Mời khách an tọa (dùng お掛けください lịch sự hơn お座りください).",
        "example_ja": "どうぞお掛けになってお待ちください。",
        "example_vi": "Xin mời ngài ngồi đợi ạ.",
    },
    {
        "source_word": "確認する(xin mời)",
        "source_reading": "かくにんする",
        "meaning_vi": "xin vui lòng kiểm tra lại",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご確認ください",
        "canonical_reading": "ごかくにんください",
        "acceptable_variants": ["ご確認ください", "ごかくにんください", "ご確認下さい", "ご確認をお願いします"],
        "triplet_sonkeigo": "ご確認ください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Công thức yêu cầu lịch sự với từ gốc Hán: ご + N + ください.",
        "example_ja": "添付ファイルをどうぞご確認ください。",
        "example_vi": "Xin ngài vui lòng kiểm tra file đính kèm ạ.",
    },
    {
        "source_word": "連絡する(xin mời)",
        "source_reading": "れんらくする",
        "meaning_vi": "xin vui lòng liên hệ",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご連絡ください",
        "canonical_reading": "ごれんらくください",
        "acceptable_variants": ["ご連絡ください", "ごれんらくください", "ご連絡下さい"],
        "triplet_sonkeigo": "ご連絡ください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Nhờ khách liên lạc lại.",
        "example_ja": "都合の良い時にご連絡ください。",
        "example_vi": "Khi thuận tiện xin ngài vui lòng liên hệ lại ạ.",
    },
    {
        "source_word": "遠慮する(xin đừng)",
        "source_reading": "えんりょする",
        "meaning_vi": "xin đừng khách sáo / xin kiêng",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご遠慮ください",
        "canonical_reading": "ごえんりょください",
        "acceptable_variants": ["ご遠慮ください", "ごえんりょください", "ご遠慮下さい"],
        "triplet_sonkeigo": "ご遠慮ください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Dùng để nhắc nhở lịch sự cấm làm gì hoặc mời không khách sáo.",
        "example_ja": "館内での撮影はご遠慮ください。",
        "example_vi": "Xin vui lòng không chụp ảnh trong tòa nhà ạ.",
    },
    {
        "source_word": "記入する(xin mời)",
        "source_reading": "きにゅうする",
        "meaning_vi": "xin vui lòng điền vào biểu mẫu",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご記入ください",
        "canonical_reading": "ごきにゅうください",
        "acceptable_variants": ["ご記入ください", "ごきにゅうください", "ご記入下さい"],
        "triplet_sonkeigo": "ご記入ください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Yêu cầu khách điền đơn.",
        "example_ja": "太枠の中をご記入ください。",
        "example_vi": "Xin ngài vui lòng điền vào trong khung đậm ạ.",
    },
    {
        "source_word": "呼ぶ(xin mời)",
        "source_reading": "よぶ",
        "meaning_vi": "xin hãy gọi khi cần",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お呼びください",
        "canonical_reading": "およびください",
        "acceptable_variants": ["お呼びください", "およびください", "お呼び下さい"],
        "triplet_sonkeigo": "お呼びください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Nhắc khách gọi nhân viên khi cần.",
        "example_ja": "御用がございましたら、いつでもお呼びください。",
        "example_vi": "Nếu có việc gì, xin ngài cứ gọi chúng em bất cứ lúc nào ạ.",
    },
    {
        "source_word": "取る(xin mời)",
        "source_reading": "とる",
        "meaning_vi": "xin mời lấy / cầm",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お取りください",
        "canonical_reading": "おとりください",
        "acceptable_variants": ["お取りください", "おとりください", "お取り下さい"],
        "triplet_sonkeigo": "お取りください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Mời khách lấy tài liệu/đồ vật.",
        "example_ja": "ご自由にお取りください。",
        "example_vi": "Xin mời quý khách tự nhiên lấy ạ.",
    },
    {
        "source_word": "話す(xin mời)",
        "source_reading": "はなす",
        "meaning_vi": "xin hãy nói / chia sẻ",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お話しください",
        "canonical_reading": "おはなしください",
        "acceptable_variants": ["お話しください", "おはなしください", "お話し下さい"],
        "triplet_sonkeigo": "お話しください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Mời khách trình bày sự việc.",
        "example_ja": "詳しい状況をお話しください。",
        "example_vi": "Xin ngài hãy kể lại tình hình chi tiết ạ.",
    },
    {
        "source_word": "楽しむ(xin mời)",
        "source_reading": "たのしむ",
        "meaning_vi": "xin hãy tận hưởng",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お楽しみください",
        "canonical_reading": "おたのしみください",
        "acceptable_variants": ["お楽しみください", "おたのしみください", "お楽しみ下さい"],
        "triplet_sonkeigo": "お楽しみください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Chúc khách tận hưởng kỳ nghỉ hoặc buổi tiệc.",
        "example_ja": "どうぞ素敵な夜をお楽しみください。",
        "example_vi": "Xin chúc quý khách tận hưởng một đêm tuyệt vời ạ.",
    },
    {
        "source_word": "気をつける",
        "source_reading": "きをつける",
        "meaning_vi": "xin hãy cẩn thận / giữ gìn",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "お気をつけください",
        "canonical_reading": "おきをつけてください",
        "acceptable_variants": ["お気をつけください", "おきをつけください", "お気をつけてください", "お気を付けください"],
        "triplet_sonkeigo": "お気をつけください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Nhắc khách đi lại cẩn thận.",
        "example_ja": "足元にお気をつけください。",
        "example_vi": "Xin quý khách cẩn thận bước chân ạ.",
    },
    {
        "source_word": "相談する(xin mời)",
        "source_reading": "そうだんする",
        "meaning_vi": "xin vui lòng trao đổi / hỏi ý kiến",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご相談ください",
        "canonical_reading": "ごそうだんください",
        "acceptable_variants": ["ご相談ください", "ごそうだんください", "ご相談下さい"],
        "triplet_sonkeigo": "ご相談ください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Mời khách trao đổi nếu có thắc mắc.",
        "example_ja": "何かご不明な点があればご相談ください。",
        "example_vi": "Nếu có điểm nào chưa rõ xin ngài cứ trao đổi ạ.",
    },
    {
        "source_word": "利用する(xin mời)",
        "source_reading": "りようする",
        "meaning_vi": "xin mời sử dụng",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご利用ください",
        "canonical_reading": "ごりようください",
        "acceptable_variants": ["ご利用ください", "ごりようください", "ご利用下さい"],
        "triplet_sonkeigo": "ご利用ください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Mời khách sử dụng dịch vụ.",
        "example_ja": "ぜひ当サービスをご利用ください。",
        "example_vi": "Xin kính mời quý khách sử dụng dịch vụ của chúng tôi ạ.",
    },
    {
        "source_word": "注意する",
        "source_reading": "ちゅういする",
        "meaning_vi": "xin hãy chú ý",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご注意ください",
        "canonical_reading": "ごちゅういください",
        "acceptable_variants": ["ご注意ください", "ごちゅういください", "ご注意下さい"],
        "triplet_sonkeigo": "ご注意ください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Thông báo nhắc nhở khách lưu ý an toàn.",
        "example_ja": "ドアの開閉にご注意ください。",
        "example_vi": "Xin quý khách chú ý khi cửa đóng mở ạ.",
    },
    {
        "source_word": "協力する(xin hãy)",
        "source_reading": "きょうりょくする",
        "meaning_vi": "xin vui lòng hợp tác",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご協力ください",
        "canonical_reading": "ごきょうりょくください",
        "acceptable_variants": ["ご協力ください", "ごきょうりょくください", "ご協力下さい"],
        "triplet_sonkeigo": "ご協力ください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Kêu gọi khách hàng hợp tác vì mục đích chung.",
        "example_ja": "環境保護にご協力ください。",
        "example_vi": "Xin quý khách vui lòng hợp tác bảo vệ môi trường ạ.",
    },
    {
        "source_word": "安心する",
        "source_reading": "あんしんする",
        "meaning_vi": "xin hãy yên tâm",
        "target_type": "sonkeigo",
        "target_label_vi": "Tôn kính ngữ (尊敬語)",
        "canonical": "ご安心ください",
        "canonical_reading": "ごあんしんください",
        "acceptable_variants": ["ご安心ください", "ごあんしんください", "ご安心下さい"],
        "triplet_sonkeigo": "ご安心ください",
        "triplet_kenjougo": None,
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "sonkeigo_kudasai",
        "formula": "お / ご + V(stem) + ください",
        "subject_hint_vi": "👑 Yêu cầu lịch sự đối với: KHÁCH HÀNG / ĐỐI TÁC",
        "explanation_vi": "Lời trấn an trang trọng gửi tới đối tác hoặc khách hàng.",
        "example_ja": "セキュリティは万全ですので、ご安心ください。",
        "example_vi": "Bảo mật rất an toàn nên xin ngài hãy yên tâm ạ.",
    },
]
