# -*- coding: utf-8 -*-
"""Bikago & Business words data definitions (98 entries total across 6 formulas):
1. bikago_prefix_o: 18 entries
2. bikago_prefix_go: 20 entries
3. teineigo_desu_masu: 14 entries
4. business_pronouns: 15 entries
5. business_time_adverbs: 16 entries
6. business_phrases: 15 entries
"""

from __future__ import annotations

# 1. bikago_prefix_o: 18 entries
BIKAGO_PREFIX_O_DATA = [
    {
        "source_word": "名前",
        "source_reading": "なまえ",
        "meaning_vi": "quý danh / tên",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お名前",
        "canonical_reading": "おなまえ",
        "acceptable_variants": ["お名前", "おなまえ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Quy tắc tiền tố tôn kính: 'お' đứng trước từ gốc thuần Nhật (和語).",
        "example_ja": "お名前を伺ってもよろしいでしょうか。",
        "example_vi": "Tôi có thể xin phép hỏi quý danh của ngài được không ạ?",
    },
    {
        "source_word": "元気",
        "source_reading": "げんき",
        "meaning_vi": "sức khỏe dồi dào",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お元気",
        "canonical_reading": "おげんき",
        "acceptable_variants": ["お元気", "おげんき", "お元気ですか"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Ngoại lệ quen thuộc: dù 元気 là Hán tự nhưng gắn với 'お' trong giao tiếp thường ngày.",
        "example_ja": "お元気でお過ごしでしょうか。",
        "example_vi": "Dạo này ngài vẫn khỏe mạnh chứ ạ?",
    },
    {
        "source_word": "宅",
        "source_reading": "たく",
        "meaning_vi": "nhà / tư gia của quý vị",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お宅",
        "canonical_reading": "おたく",
        "acceptable_variants": ["お宅", "おたく"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Ngoại lệ: 宅 là Hán tự nhưng đi kèm tiền tố 'お' để chỉ nhà khách.",
        "example_ja": "どちらがお宅でいらっしゃいますか。",
        "example_vi": "Nhà của ngài ở khu vực nào vậy ạ?",
    },
    {
        "source_word": "仕事",
        "source_reading": "しごと",
        "meaning_vi": "công việc quý báu của ngài",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お仕事",
        "canonical_reading": "おしごと",
        "acceptable_variants": ["お仕事", "おしごと"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Đi kèm 'お' biểu thị sự tôn trọng công việc của đối tác.",
        "example_ja": "今日はお仕事ですか。",
        "example_vi": "Hôm nay ngài có công việc phải làm ạ?",
    },
    {
        "source_word": "電話",
        "source_reading": "でんわ",
        "meaning_vi": "cuộc điện thoại",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お電話",
        "canonical_reading": "おでんわ",
        "acceptable_variants": ["お電話", "おでんわ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Ngoại lệ cực kỳ phổ biến: 電話 đi với 'お' chứ không đi với 'ご'.",
        "example_ja": "お電話ありがとうございます。",
        "example_vi": "Cảm ơn ngài đã gọi điện tới ạ.",
    },
    {
        "source_word": "食事",
        "source_reading": "しょくじ",
        "meaning_vi": "bữa ăn",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お食事",
        "canonical_reading": "おしょくじ",
        "acceptable_variants": ["お食事", "おしょくじ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Ngoại lệ: 食事 quen thuộc đi với 'お'.",
        "example_ja": "お食事はお済みになりましたか。",
        "example_vi": "Ngài đã dùng bữa xong chưa ạ?",
    },
    {
        "source_word": "料理",
        "source_reading": "りょうり",
        "meaning_vi": "món ăn / ẩm thực",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お料理",
        "canonical_reading": "おりょうり",
        "acceptable_variants": ["お料理", "おりょうり"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Ngoại lệ mỹ hóa từ ngữ: 料理 đi với 'お'.",
        "example_ja": "お料理はいかがでしたか。",
        "example_vi": "Món ăn có hợp khẩu vị của ngài không ạ?",
    },
    {
        "source_word": "時間",
        "source_reading": "じかん",
        "meaning_vi": "thời gian quý báu của khách",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お時間",
        "canonical_reading": "おじかん",
        "acceptable_variants": ["お時間", "おじかん"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Ngoại lệ: 時間 đi với 'お'. Thường dùng xin vài phút của sếp.",
        "example_ja": "今、少しお時間よろしいでしょうか。",
        "example_vi": "Hiện giờ ngài có chút thời gian rảnh không ạ?",
    },
    {
        "source_word": "忙しい",
        "source_reading": "いそがしい",
        "meaning_vi": "bận rộn (tính từ thuần Nhật)",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お忙しい",
        "canonical_reading": "おいそがしい",
        "acceptable_variants": ["お忙しい", "おいそがしい"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Tính từ đuôi い thuần Nhật đi kèm 'お': お忙しい中.",
        "example_ja": "お忙しいところ、恐れ入ります。",
        "example_vi": "Xin thứ lỗi vì đã làm phiền ngài trong lúc bận rộn ạ.",
    },
    {
        "source_word": "手紙",
        "source_reading": "てがみ",
        "meaning_vi": "lá thư",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お手紙",
        "canonical_reading": "おてがみ",
        "acceptable_variants": ["お手紙", "おてがみ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Từ thuần Nhật đi với tiền tố 'お'.",
        "example_ja": "心温まるお手紙をありがとうございます。",
        "example_vi": "Cảm ơn bức thư ấm áp của ngài ạ.",
    },
    {
        "source_word": "荷物",
        "source_reading": "にもつ",
        "meaning_vi": "hành lý / kiện hàng",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お荷物",
        "canonical_reading": "おにもつ",
        "acceptable_variants": ["お荷物", "おにもつ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Từ thuần Nhật đi với 'お'.",
        "example_ja": "お荷物をお持ちしましょうか。",
        "example_vi": "Để tôi xách hành lý giúp ngài nhé ạ?",
    },
    {
        "source_word": "部屋",
        "source_reading": "へや",
        "meaning_vi": "căn phòng",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お部屋",
        "canonical_reading": "おへや",
        "acceptable_variants": ["お部屋", "おへや"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Từ thuần Nhật đi với 'お'.",
        "example_ja": "お部屋をご案内いたします。",
        "example_vi": "Tôi xin phép dẫn ngài vào phòng ạ.",
    },
    {
        "source_word": "水",
        "source_reading": "みず",
        "meaning_vi": "nước uống thanh khiết",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お水",
        "canonical_reading": "おみず",
        "acceptable_variants": ["お水", "おみず", "お冷"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Mỹ từ pháp cho nước trong nhà hàng.",
        "example_ja": "お水のおかわりはいかがですか。",
        "example_vi": "Ngài có muốn dùng thêm nước không ạ?",
    },
    {
        "source_word": "茶",
        "source_reading": "ちゃ",
        "meaning_vi": "trà mời khách",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お茶",
        "canonical_reading": "おちゃ",
        "acceptable_variants": ["お茶", "おちゃ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Mỹ hóa danh từ kinh điển trong văn hóa trà đạo và tiếp khách.",
        "example_ja": "どうぞお茶を召し上がりください。",
        "example_vi": "Xin mời ngài dùng trà ạ.",
    },
    {
        "source_word": "金",
        "source_reading": "かね",
        "meaning_vi": "tiền bạc",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お金",
        "canonical_reading": "おかね",
        "acceptable_variants": ["お金", "おかね"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Mỹ hóa danh từ 金 thành お金.",
        "example_ja": "お金の管理には十分ご注意ください。",
        "example_vi": "Xin quý khách lưu ý bảo quản tiền bạc cẩn thận ạ.",
    },
    {
        "source_word": "店",
        "source_reading": "みせ",
        "meaning_vi": "cửa tiệm / quán",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お店",
        "canonical_reading": "おみせ",
        "acceptable_variants": ["お店", "おみせ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Mỹ hóa danh từ 店.",
        "example_ja": "素敵なお店ですね。",
        "example_vi": "Cửa hàng đẹp quá ngài nhỉ.",
    },
    {
        "source_word": "席",
        "source_reading": "せき",
        "meaning_vi": "chỗ ngồi",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お席",
        "canonical_reading": "おせき",
        "acceptable_variants": ["お席", "おせき"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Ngoại lệ: 席 đi với 'お'.",
        "example_ja": "お席にご案内いたします。",
        "example_vi": "Tôi xin phép dẫn ngài tới chỗ ngồi ạ.",
    },
    {
        "source_word": "礼",
        "source_reading": "れい",
        "meaning_vi": "lời cảm ơn / quà đáp lễ",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "お礼",
        "canonical_reading": "おれい",
        "acceptable_variants": ["お礼", "おれい"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_o",
        "formula": "お + Từ thuần Nhật (Wago)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ thuần Nhật",
        "explanation_vi": "Ngoại lệ: 礼 đi với 'お'.",
        "example_ja": "心からのお礼を申し上げます。",
        "example_vi": "Tôi xin gửi lời cảm ơn tự đáy lòng ạ.",
    },
]

# 2. bikago_prefix_go: 20 entries
BIKAGO_PREFIX_GO_DATA = [
    {
        "source_word": "家族",
        "source_reading": "かぞく",
        "meaning_vi": "gia đình của quý vị",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご家族",
        "canonical_reading": "ごかぞく",
        "acceptable_variants": ["ご家族", "ごかぞく", "ご家族様"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Quy tắc tiền tố: 'ご' đứng trước danh từ gốc Hán (漢語).",
        "example_ja": "ご家族の皆様によろしくお伝えください。",
        "example_vi": "Xin gửi lời chào thăm của tôi tới toàn thể gia đình ngài ạ.",
    },
    {
        "source_word": "意見",
        "source_reading": "いけん",
        "meaning_vi": "ý kiến quý báu",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご意見",
        "canonical_reading": "ごいけん",
        "acceptable_variants": ["ご意見", "ごいけん"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 意見 đi kèm tiền tố 'ご'.",
        "example_ja": "貴重なご意見をありがとうございます。",
        "example_vi": "Cảm ơn những ý kiến đóng góp quý báu của ngài ạ.",
    },
    {
        "source_word": "連絡",
        "source_reading": "れんらく",
        "meaning_vi": "thông tin liên hệ",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご連絡",
        "canonical_reading": "ごれんらく",
        "acceptable_variants": ["ご連絡", "ごれんらく"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 連絡 đi kèm tiền tố 'ご'.",
        "example_ja": "早急なご連絡に感謝いたします。",
        "example_vi": "Cảm ơn ngài đã liên lạc nhanh chóng ạ.",
    },
    {
        "source_word": "住所",
        "source_reading": "じゅうしょ",
        "meaning_vi": "địa chỉ nhà của ngài",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご住所",
        "canonical_reading": "ごじゅうしょ",
        "acceptable_variants": ["ご住所", "ごじゅうしょ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N5",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 住所 đi với 'ご'.",
        "example_ja": "こちらにご住所をご記入ください。",
        "example_vi": "Xin ngài vui lòng ghi địa chỉ vào đây ạ.",
    },
    {
        "source_word": "都合",
        "source_reading": "つごう",
        "meaning_vi": "lịch trình / sự tiện lợi của khách",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご都合",
        "canonical_reading": "ごつごう",
        "acceptable_variants": ["ご都合", "ごつごう"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 都合 đi với 'ご'.",
        "example_ja": "ご都合のよろしい日時はいつでしょうか。",
        "example_vi": "Ngày giờ nào thuận tiện nhất cho ngài vậy ạ?",
    },
    {
        "source_word": "予定",
        "source_reading": "よてい",
        "meaning_vi": "kế hoạch / lịch trình dự định",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご予定",
        "canonical_reading": "ごよてい",
        "acceptable_variants": ["ご予定", "ごよてい"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 予定 đi với 'ご'.",
        "example_ja": "来週のご予定はいかがでしょうか。",
        "example_vi": "Lịch trình tuần sau của ngài thế nào ạ?",
    },
    {
        "source_word": "案内",
        "source_reading": "あんない",
        "meaning_vi": "bản tin thông báo / chỉ dẫn",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご案内",
        "canonical_reading": "ごあんない",
        "acceptable_variants": ["ご案内", "ごあんない"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 案内 đi với 'ご'.",
        "example_ja": "詳細のご案内をお送りいたします。",
        "example_vi": "Chúng tôi xin gửi bản thông báo chi tiết ạ.",
    },
    {
        "source_word": "説明",
        "source_reading": "せつめい",
        "meaning_vi": "lời giải thích",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご説明",
        "canonical_reading": "ごせつめい",
        "acceptable_variants": ["ご説明", "ごせつめい"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 説明 đi với 'ご'.",
        "example_ja": "丁寧なご説明に感謝申し上げます。",
        "example_vi": "Tôi xin cảm ơn lời giải thích tận tình của ngài ạ.",
    },
    {
        "source_word": "協力",
        "source_reading": "きょうりょく",
        "meaning_vi": "sự hỗ trợ / hợp tác",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご協力",
        "canonical_reading": "ごきょうりょく",
        "acceptable_variants": ["ご協力", "ごきょうりょく"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 協力 đi với 'ご'.",
        "example_ja": "皆様のご協力に心より感謝いたします。",
        "example_vi": "Tôi xin chân thành cảm ơn sự hợp tác của mọi người ạ.",
    },
    {
        "source_word": "検討",
        "source_reading": "けんとう",
        "meaning_vi": "sự cân nhắc xem xét",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご検討",
        "canonical_reading": "ごけんとう",
        "acceptable_variants": ["ご検討", "ごけんとう"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N3",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 検討 đi với 'ご'.",
        "example_ja": "何卒ご検討のほどよろしくお願いいたします。",
        "example_vi": "Kính mong ngài xem xét cân nhắc giúp ạ.",
    },
    {
        "source_word": "親切",
        "source_reading": "しんせつ",
        "meaning_vi": "sự tử tế / lòng tốt của ngài",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご親切",
        "canonical_reading": "ごしんせつ",
        "acceptable_variants": ["ご親切", "ごしんせつ", "ご親切に"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Tính từ đuôi な gốc Hán: ご親切にありがとうございます.",
        "example_ja": "ご親切に教えていただき、感謝いたします。",
        "example_vi": "Cảm ơn ngài đã tận tình chỉ bảo cho tôi ạ.",
    },
    {
        "source_word": "心配",
        "source_reading": "しんぱい",
        "meaning_vi": "sự lo lắng / bận lòng",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご心配",
        "canonical_reading": "ごしんぱい",
        "acceptable_variants": ["ご心配", "ごしんぱい"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 心配 đi với 'ご'.",
        "example_ja": "ご心配をおかけして申し訳ありませんでした。",
        "example_vi": "Xin lỗi vì đã khiến ngài phải lo lắng ạ.",
    },
    {
        "source_word": "質問",
        "source_reading": "しつもん",
        "meaning_vi": "câu hỏi thắc mắc",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご質問",
        "canonical_reading": "ごしつもん",
        "acceptable_variants": ["ご質問", "ごしつもん"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 質問 đi với 'ご'.",
        "example_ja": "何かご質問はございますか。",
        "example_vi": "Ngài có câu hỏi thắc mắc nào không ạ?",
    },
    {
        "source_word": "注文",
        "source_reading": "ちゅうもん",
        "meaning_vi": "đơn đặt hàng",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご注文",
        "canonical_reading": "ごちゅうもん",
        "acceptable_variants": ["ご注文", "ごちゅうもん"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 注文 đi với 'ご'.",
        "example_ja": "ご注文はお決まりでしょうか。",
        "example_vi": "Quý khách đã quyết định gọi món chưa ạ?",
    },
    {
        "source_word": "利用",
        "source_reading": "りよう",
        "meaning_vi": "sự sử dụng / mua sắm",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご利用",
        "canonical_reading": "ごりよう",
        "acceptable_variants": ["ご利用", "ごりよう"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 利用 đi với 'ご'.",
        "example_ja": "毎度のご利用ありがとうございます。",
        "example_vi": "Cảm ơn quý khách lúc nào cũng ghé ủng hộ chúng tôi ạ.",
    },
    {
        "source_word": "挨拶",
        "source_reading": "あいさつ",
        "meaning_vi": "lời chào hỏi",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご挨拶",
        "canonical_reading": "ごあいさつ",
        "acceptable_variants": ["ご挨拶", "ごあいさつ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 挨拶 đi với 'ご'.",
        "example_ja": "社長より開会のご挨拶がございます。",
        "example_vi": "Giám đốc sẽ có lời chào mừng khai mạc ạ.",
    },
    {
        "source_word": "報告",
        "source_reading": "ほうこく",
        "meaning_vi": "bản báo cáo",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご報告",
        "canonical_reading": "ごほうこく",
        "acceptable_variants": ["ご報告", "ごほうこく"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 報告 đi với 'ご'.",
        "example_ja": "皆様に嬉しいご報告がございます。",
        "example_vi": "Tôi xin có một tin vui báo cáo cùng toàn thể mọi người ạ.",
    },
    {
        "source_word": "相談",
        "source_reading": "そうだん",
        "meaning_vi": "việc trao đổi ý kiến",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご相談",
        "canonical_reading": "ごそうだん",
        "acceptable_variants": ["ご相談", "ごそうだん"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 相談 đi với 'ご'.",
        "example_ja": "折り入ってご相談がございます。",
        "example_vi": "Tôi có một việc quan trọng muốn xin ý kiến trao đổi ạ.",
    },
    {
        "source_word": "迷惑",
        "source_reading": "めいわく",
        "meaning_vi": "sự phiền toái",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご迷惑",
        "canonical_reading": "ごめいわく",
        "acceptable_variants": ["ご迷惑", "ごめいわく"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N4",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 迷惑 đi với 'ご'.",
        "example_ja": "多大なご迷惑をおかけいたしました。",
        "example_vi": "Chúng tôi xin lỗi vì đã gây ra phiền phức lớn cho quý vị ạ.",
    },
    {
        "source_word": "理解",
        "source_reading": "りかい",
        "meaning_vi": "sự thấu hiểu thông cảm",
        "target_type": "prefix",
        "target_label_vi": "Mỹ từ pháp (美化語)",
        "canonical": "ご理解",
        "canonical_reading": "ごりかい",
        "acceptable_variants": ["ご理解", "ごりかい"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "noun_prefixes",
        "jlpt_level": "N3",
        "formula_id": "bikago_prefix_go",
        "formula": "ご + Từ gốc Hán (Kango)",
        "subject_hint_vi": "✨ Làm trang trọng & mỹ hóa danh từ gốc Hán",
        "explanation_vi": "Từ gốc Hán 理解 đi với 'ご'.",
        "example_ja": "何卒ご理解のほどお願い申し上げます。",
        "example_vi": "Kính mong quý khách thấu hiểu và thông cảm ạ.",
    },
]

# 3. teineigo_desu_masu: 14 entries
TEINEIGO_DESU_MASU_DATA = [
    {
        "source_word": "いい",
        "source_reading": "いい",
        "meaning_vi": "tốt / được / ổn",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "よろしい",
        "canonical_reading": "よろしい",
        "acceptable_variants": ["よろしい", "よろしゅうございます", "よろしいです"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Từ lịch sự thay thế cho いい/よい trong môi trường làm việc chuẩn.",
        "example_ja": "こちらでよろしいでしょうか。",
        "example_vi": "Phương án này có ổn thỏa với ngài không ạ?",
    },
    {
        "source_word": "ある",
        "source_reading": "ある",
        "meaning_vi": "có (đồ vật/tài liệu)",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "ございます",
        "canonical_reading": "ございます",
        "acceptable_variants": ["ございます", "ございまして", "ございません"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Thể lịch sự đinh trọng (丁寧語) của あります.",
        "example_ja": "何かご不明な点はございますか。",
        "example_vi": "Có điểm nào chưa rõ ràng không ạ?",
    },
    {
        "source_word": "だ / です",
        "source_reading": "です",
        "meaning_vi": "là / thì",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "でございます",
        "canonical_reading": "でございます",
        "acceptable_variants": ["でございます", "でございまして"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Thể lịch sự đinh trọng của です.",
        "example_ja": "担当の山田でございます。",
        "example_vi": "Tôi là Yamada phụ trách ạ.",
    },
    {
        "source_word": "いいですか",
        "source_reading": "いいですか",
        "meaning_vi": "có được không ạ?",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "よろしいでしょうか",
        "canonical_reading": "よろしいでしょうか",
        "acceptable_variants": ["よろしいでしょうか", "よろしいですか", "よろしゅうございますか"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Hỏi ý kiến khách hàng lịch sự thay vì dùng 'いいですか'.",
        "example_ja": "少々お時間をいただいてもよろしいでしょうか。",
        "example_vi": "Tôi xin phép ngài một chút thời gian được không ạ?",
    },
    {
        "source_word": "どうですか",
        "source_reading": "どうですか",
        "meaning_vi": "ngài thấy thế nào ạ?",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "いかがでしょうか",
        "canonical_reading": "いかがでしょうか",
        "acceptable_variants": ["いかがでしょうか", "いかがですか", "いかがでございましょうか"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Cách hỏi lịch sự chuẩn mực cho 'どうですか'.",
        "example_ja": "こちらのプランはいかがでしょうか。",
        "example_vi": "Phương án này ngài thấy thế nào ạ?",
    },
    {
        "source_word": "どこですか",
        "source_reading": "どこですか",
        "meaning_vi": "ở đâu vậy ạ?",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "どちらでございますか",
        "canonical_reading": "どちらでございますか",
        "acceptable_variants": ["どちらでございますか", "どちらでしょうか", "どこでございますか"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Hỏi vị trí trang nhã thay vì nói 'どこですか'.",
        "example_ja": "お手洗いはどちらでございますか。",
        "example_vi": "Nhà vệ sinh ở hướng nào vậy ạ?",
    },
    {
        "source_word": "ない",
        "source_reading": "ない",
        "meaning_vi": "không có",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "ございません",
        "canonical_reading": "ございません",
        "acceptable_variants": ["ございません", "ございませんでした"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Phủ định lịch sự của ありません.",
        "example_ja": "ただいま在庫がございません。",
        "example_vi": "Hiện tại chúng tôi không còn hàng tồn kho ạ.",
    },
    {
        "source_word": "ありません",
        "source_reading": "ありません",
        "meaning_vi": "không có (dạng trang trọng)",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "ございません",
        "canonical_reading": "ございません",
        "acceptable_variants": ["ございません", "ございませんでした"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Thay thế ありません bằng ございません để tăng mức độ tôn trọng.",
        "example_ja": "あいにく空室はございません。",
        "example_vi": "Rất tiếc là hiện tại không còn phòng trống ạ.",
    },
    {
        "source_word": "だれですか",
        "source_reading": "だれですか",
        "meaning_vi": "vị nào thế ạ?",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "どなた様でしょうか",
        "canonical_reading": "どなたさまでしょうか",
        "acceptable_variants": ["どなた様でしょうか", "どなたさまでしょうか", "どなた様でございますか", "どちら様でしょうか"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Hỏi danh tính người gọi điện hoặc khách đến thăm một cách lịch thiệp.",
        "example_ja": "失礼ですが、どちら様でしょうか。",
        "example_vi": "Xin thứ lỗi, ngài là vị nào vậy ạ?",
    },
    {
        "source_word": "そうです",
        "source_reading": "そうです",
        "meaning_vi": "đúng như vậy ạ",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "さようでございます",
        "canonical_reading": "さようでございます",
        "acceptable_variants": ["さようでございます", "そうでございます", "さようでございますね"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Khẳng định trang trọng thay cho そうです.",
        "example_ja": "左様でございます、私が担当の田中です。",
        "example_vi": "Đúng như vậy ạ, tôi là Tanaka phụ trách.",
    },
    {
        "source_word": "そうですか",
        "source_reading": "そうですか",
        "meaning_vi": "ra là vậy ạ",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "さようでございますか",
        "canonical_reading": "さようでございますか",
        "acceptable_variants": ["さようでございますか", "そうでございますか"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Hưởng ứng nhã nhặn khi nghe đối tác nói.",
        "example_ja": "左様でございますか、かしこまりました。",
        "example_vi": "Dạ ra là vậy ạ, tôi đã hiểu rõ rồi ạ.",
    },
    {
        "source_word": "どうですか(v2)",
        "source_reading": "どうですか",
        "meaning_vi": "ngài thấy thế nào (rất trang trọng)",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "いかがでございましょうか",
        "canonical_reading": "いかがでございましょうか",
        "acceptable_variants": ["いかがでございましょうか", "いかがでしょうか"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Biến thể cực kỳ trang trọng khi thăm dò ý kiến VIP.",
        "example_ja": "ご都合はいかがでございましょうか。",
        "example_vi": "Lịch trình của ngài thấy thế nào ạ?",
    },
    {
        "source_word": "いくらですか",
        "source_reading": "いくらですか",
        "meaning_vi": "giá bao nhiêu vậy ạ?",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "おいくらでございますか",
        "canonical_reading": "おいくらでございますか",
        "acceptable_variants": ["おいくらでございますか", "おいくらでしょうか"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Hỏi giá tiền một cách thanh lịch.",
        "example_ja": "こちらの総額はおいくらでございますか。",
        "example_vi": "Tổng số tiền này là bao nhiêu vậy ạ?",
    },
    {
        "source_word": "何ですか",
        "source_reading": "なんですか",
        "meaning_vi": "điều gì thế ạ?",
        "target_type": "business",
        "target_label_vi": "Từ lịch sự (丁寧語)",
        "canonical": "何でございましょうか",
        "canonical_reading": "なんでございましょうか",
        "acceptable_variants": ["何でございましょうか", "なんでございましょうか", "何でしょうか"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "teineigo_desu_masu",
        "formula": "Thể lịch sự / Đinh trọng: ございます / でございます",
        "subject_hint_vi": "🤝 Lịch sự, trang trọng tiêu chuẩn trong giao tiếp",
        "explanation_vi": "Cách phản hồi nhã nhặn khi khách cần hỏi việc.",
        "example_ja": "ご用件は何でございましょうか。",
        "example_vi": "Ngài có việc gì cần dặn dò ạ?",
    },
]

# 4. business_pronouns: 15 entries
BUSINESS_PRONOUNS_DATA = [
    {
        "source_word": "わたし",
        "source_reading": "わたし",
        "meaning_vi": "tôi (khiêm tốn công sở)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "わたくし",
        "canonical_reading": "わたくし",
        "acceptable_variants": ["わたくし", "私"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Đại từ ngôi thứ nhất trang trọng nhất trong tiếng Nhật kinh doanh.",
        "example_ja": "わたくしがご案内いたします。",
        "example_vi": "Tôi xin phép được hướng dẫn ngài ạ.",
    },
    {
        "source_word": "わたしたち",
        "source_reading": "わたしたち",
        "meaning_vi": "chúng tôi",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "私ども",
        "canonical_reading": "わたくしども",
        "acceptable_variants": ["私ども", "わたくしども", "わたしたち"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Đại từ số nhiều khiêm tốn của bên mình khi nói chuyện với đối tác.",
        "example_ja": "私どもにお任せください。",
        "example_vi": "Xin ngài hãy yên tâm giao phó cho phía chúng tôi ạ.",
    },
    {
        "source_word": "会社(mình)",
        "source_reading": "かいしゃ",
        "meaning_vi": "công ty chúng tôi (khiêm tốn)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "弊社",
        "canonical_reading": "へいしゃ",
        "acceptable_variants": ["弊社", "へいしゃ", "当社", "とうしゃ"],
        "triplet_sonkeigo": "御社",
        "triplet_kenjougo": "弊社",
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Khiêm nhường ngữ chỉ công ty mình khi nói chuyện với khách hàng.",
        "example_ja": "弊社の製品をご愛顧いただき感謝します。",
        "example_vi": "Cảm ơn ngài đã luôn tin dùng sản phẩm của công ty chúng tôi ạ.",
    },
    {
        "source_word": "会社(khách)",
        "source_reading": "かいしゃ",
        "meaning_vi": "quý công ty (văn nói)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "御社",
        "canonical_reading": "おんしゃ",
        "acceptable_variants": ["御社", "おんしゃ", "貴社", "きしゃ"],
        "triplet_sonkeigo": "御社",
        "triplet_kenjougo": "弊社",
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Tôn kính ngữ chỉ công ty của đối tác trong giao tiếp trực tiếp / qua điện thoại.",
        "example_ja": "御社の今後のビジョンについて教えてください。",
        "example_vi": "Xin ngài chia sẻ thêm về tầm nhìn tương lai của quý công ty ạ.",
    },
    {
        "source_word": "会社(văn bản)",
        "source_reading": "かいしゃ",
        "meaning_vi": "quý công ty (trong email / văn bản)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "貴社",
        "canonical_reading": "きしゃ",
        "acceptable_variants": ["貴社", "きしゃ", "御社", "おんしゃ"],
        "triplet_sonkeigo": "貴社",
        "triplet_kenjougo": "弊社",
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Dùng trong văn bản viết hoặc email gửi đối tác: 貴社の発展を祈る.",
        "example_ja": "貴社ますますご清栄のこととお慶び申し上げます。",
        "example_vi": "Chúc quý công ty ngày càng hưng thịnh và phát triển ạ.",
    },
    {
        "source_word": "会社(nội bộ)",
        "source_reading": "かいしゃ",
        "meaning_vi": "công ty chúng ta (khi nói nội bộ)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "当社",
        "canonical_reading": "とうしゃ",
        "acceptable_variants": ["当社", "とうしゃ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "当社",
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Dùng để chỉ công ty mình khi trình bày với tính chất trung tính hoặc nội bộ.",
        "example_ja": "当社の基本方針について説明します。",
        "example_vi": "Tôi xin giải thích về phương châm cơ bản của công ty chúng ta.",
    },
    {
        "source_word": "人",
        "source_reading": "ひと",
        "meaning_vi": "vị đó / người đó",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "方",
        "canonical_reading": "かた",
        "acceptable_variants": ["方", "かた", "あの方", "あのかた"],
        "triplet_sonkeigo": "方",
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N5",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Từ lịch sự thay thế cho 人.",
        "example_ja": "あちらの方はどなたですか。",
        "example_vi": "Vị ở đằng kia là ai thế ạ?",
    },
    {
        "source_word": "だれ",
        "source_reading": "だれ",
        "meaning_vi": "vị nào",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "どなた",
        "canonical_reading": "どなた",
        "acceptable_variants": ["どなた", "どちら様", "どなた様"],
        "triplet_sonkeigo": "どなた",
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N5",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Từ lịch sự thay thế cho だれ.",
        "example_ja": "どなたにご連絡すればよろしいですか。",
        "example_vi": "Tôi nên liên hệ với vị nào thì được ạ?",
    },
    {
        "source_word": "どこ",
        "source_reading": "どこ",
        "meaning_vi": "phía nào / nơi nào",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "どちら",
        "canonical_reading": "どちら",
        "acceptable_variants": ["どちら", "どちら様"],
        "triplet_sonkeigo": "どちら",
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N5",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Từ lịch sự thay thế cho どこ.",
        "example_ja": "出身はどちらですか。",
        "example_vi": "Quê quán của ngài ở đâu vậy ạ?",
    },
    {
        "source_word": "どう",
        "source_reading": "どう",
        "meaning_vi": "như thế nào",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "いかが",
        "canonical_reading": "いかが",
        "acceptable_variants": ["いかが", "いかがでしょうか"],
        "triplet_sonkeigo": "いかが",
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Từ lịch sự thay thế cho どう.",
        "example_ja": "ご気分はいかがですか。",
        "example_vi": "Tâm trạng ngài thấy thế nào ạ?",
    },
    {
        "source_word": "あなた",
        "source_reading": "あなた",
        "meaning_vi": "phía quý ngài",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "そちら様",
        "canonical_reading": "そちらさま",
        "acceptable_variants": ["そちら様", "そちらさま", "貴殿"],
        "triplet_sonkeigo": "そちら様",
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Tránh dùng あなた trong tiếng Nhật công sở, thay bằng そちら様.",
        "example_ja": "そちら様のご要望をお聞かせください。",
        "example_vi": "Xin hãy cho chúng tôi biết nguyện vọng của phía quý ngài ạ.",
    },
    {
        "source_word": "みんな",
        "source_reading": "みんな",
        "meaning_vi": "quý vị / toàn thể mọi người",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "皆様",
        "canonical_reading": "みなさま",
        "acceptable_variants": ["皆様", "みなさま", "皆さん"],
        "triplet_sonkeigo": "皆様",
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N5",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Từ xưng hô tập thể trang trọng với khách hàng và cử tọa.",
        "example_ja": "皆様、本日はご来場ありがとうございます。",
        "example_vi": "Kính thưa quý vị, cảm ơn quý vị đã đến tham dự hôm nay ạ.",
    },
    {
        "source_word": "あの人",
        "source_reading": "あのひと",
        "meaning_vi": "vị ở đằng kia",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "あちら様",
        "canonical_reading": "あちらさま",
        "acceptable_variants": ["あちら様", "あちらさま", "あの方", "あのかた"],
        "triplet_sonkeigo": "あちら様",
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Chỉ người thứ ba với sự tôn trọng tối đa.",
        "example_ja": "あちら様が弊社の代表取締役です。",
        "example_vi": "Vị ở đằng kia là Giám đốc đại diện của công ty chúng tôi ạ.",
    },
    {
        "source_word": "この人",
        "source_reading": "このひと",
        "meaning_vi": "người này (giới thiệu)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "こちらの方",
        "canonical_reading": "こちらのかた",
        "acceptable_variants": ["こちらの方", "こちらのかた", "こちら様"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Giới thiệu lịch sự người bên cạnh.",
        "example_ja": "こちらの方から詳しくお聞きください。",
        "example_vi": "Xin ngài hãy lắng nghe chi tiết từ vị này ạ.",
    },
    {
        "source_word": "相手の会社",
        "source_reading": "あいてのかいしゃ",
        "meaning_vi": "công ty đối tác",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "御社",
        "canonical_reading": "おんしゃ",
        "acceptable_variants": ["御社", "おんしゃ", "貴社", "きしゃ"],
        "triplet_sonkeigo": "御社",
        "triplet_kenjougo": "弊社",
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_pronouns",
        "formula": "Xưng hô công sở & Uchi / Soto",
        "subject_hint_vi": "🏢 Phân biệt trong - ngoài công ty (Uchi / Soto)",
        "explanation_vi": "Xưng hô tôn trọng khi nói về công ty của người đối diện.",
        "example_ja": "御社との業務提携を嬉しく思います。",
        "example_vi": "Chúng tôi rất vui mừng được hợp tác kinh doanh cùng quý công ty ạ.",
    },
]

# 5. business_time_adverbs: 16 entries
BUSINESS_TIME_ADVERBS_DATA = [
    {
        "source_word": "今日",
        "source_reading": "きょう",
        "meaning_vi": "hôm nay (công sở)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "本日",
        "canonical_reading": "ほんじつ",
        "acceptable_variants": ["本日", "ほんじつ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng 本日 thay vì 今日 trong mọi cuộc gọi và văn bản công việc.",
        "example_ja": "本日はお時間をいただきありがとうございます。",
        "example_vi": "Cảm ơn ngài đã dành thời gian cho chúng tôi ngày hôm nay ạ.",
    },
    {
        "source_word": "明日",
        "source_reading": "あした",
        "meaning_vi": "ngày mai (trang trọng)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "明日(あす)",
        "canonical_reading": "あす",
        "acceptable_variants": ["明日", "あす", "みょうにち", "明日(あす)", "明日(みょうにち)"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Đọc là あす hoặc みょうにち (Minh nhật) trong công sở thay cho あした.",
        "example_ja": "明日、10時にお伺いいたします。",
        "example_vi": "Ngày mai lúc 10 giờ tôi xin phép tới gặp ngài ạ.",
    },
    {
        "source_word": "昨日",
        "source_reading": "きのう",
        "meaning_vi": "ngày hôm qua (trang trọng)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "昨日(さくじつ)",
        "canonical_reading": "さくじつ",
        "acceptable_variants": ["昨日", "さくじつ", "昨日(さくじつ)"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Đọc là さくじつ (Tác nhật) thay cho きのう.",
        "example_ja": "昨日のメールをご確認いただけましたでしょうか。",
        "example_vi": "Ngài đã kiểm tra email ngày hôm qua chưa ạ?",
    },
    {
        "source_word": "おととい",
        "source_reading": "おととい",
        "meaning_vi": "ngày hôm kia",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "一昨日",
        "canonical_reading": "いっさくじつ",
        "acceptable_variants": ["一昨日", "いっさくじつ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng いっさくじつ thay vì おととい.",
        "example_ja": "一昨日お電話いたしました件ですが。",
        "example_vi": "Về việc tôi đã gọi điện vào hôm kia...",
    },
    {
        "source_word": "あさって",
        "source_reading": "あさって",
        "meaning_vi": "ngày kia",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "明後日",
        "canonical_reading": "みょうごにち",
        "acceptable_variants": ["明後日", "みょうごにち", "あさって"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng みょうごにち thay vì あさって.",
        "example_ja": "明後日、改めてご連絡いたします。",
        "example_vi": "Ngày kia tôi xin phép liên lạc lại ạ.",
    },
    {
        "source_word": "今年",
        "source_reading": "ことし",
        "meaning_vi": "năm nay (trang trọng)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "本年",
        "canonical_reading": "ほんねん",
        "acceptable_variants": ["本年", "ほんねん"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng 本年 thay cho ことし trong chúc Tết và thư từ.",
        "example_ja": "本年もどうぞよろしくお願い申し上げます。",
        "example_vi": "Năm nay kính mong ngài tiếp tục giúp đỡ ạ.",
    },
    {
        "source_word": "去年",
        "source_reading": "きょねん",
        "meaning_vi": "năm ngoái (trang trọng)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "昨年",
        "canonical_reading": "さくねん",
        "acceptable_variants": ["昨年", "さくねん"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng 昨年 thay cho 去年 (tránh chữ 去 mang nghĩa chết chóc).",
        "example_ja": "昨年中は大変お世話になりました。",
        "example_vi": "Trong suốt năm qua cảm ơn ngài đã giúp đỡ rất nhiều ạ.",
    },
    {
        "source_word": "ちょっと",
        "source_reading": "ちょっと",
        "meaning_vi": "một chút / giây lát",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "少々",
        "canonical_reading": "しょうしょう",
        "acceptable_variants": ["少々", "しょうしょう"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Thay thế phó từ khẩu ngữ ちょっと bằng 少々.",
        "example_ja": "少々お待ちいただけますでしょうか。",
        "example_vi": "Ngài vui lòng đợi trong giây lát được không ạ?",
    },
    {
        "source_word": "すぐ",
        "source_reading": "すぐ",
        "meaning_vi": "ngay lập tức / khẩn cấp",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "至急",
        "canonical_reading": "しきゅう",
        "acceptable_variants": ["至急", "しきゅう", "早急", "さっきゅう"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng 至急 hoặc 早急 trong thông báo khẩn thay cho すぐ.",
        "example_ja": "至急ご対応をお願いいたします。",
        "example_vi": "Kính mong ngài xử lý việc này gấp giúp ạ.",
    },
    {
        "source_word": "あとで",
        "source_reading": "あとで",
        "meaning_vi": "lát nữa / sau đó",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "後ほど",
        "canonical_reading": "のちほど",
        "acceptable_variants": ["後ほど", "のちほど", "後程"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng 後ほど thay cho あとで.",
        "example_ja": "後ほど担当者よりご連絡いたします。",
        "example_vi": "Lát nữa người phụ trách sẽ liên lạc lại cho ngài ạ.",
    },
    {
        "source_word": "さっき",
        "source_reading": "さっき",
        "meaning_vi": "vừa nãy / vừa rồi",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "先ほど",
        "canonical_reading": "さきほど",
        "acceptable_variants": ["先ほど", "さきほど", "先程"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng 先ほど thay cho さっき.",
        "example_ja": "先ほどお電話を差し上げました田中です。",
        "example_vi": "Tôi là Tanaka vừa mới gọi điện thoại lúc nãy ạ.",
    },
    {
        "source_word": "いま",
        "source_reading": "いま",
        "meaning_vi": "bây giờ / hiện nay",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "ただいま",
        "canonical_reading": "ただいま",
        "acceptable_variants": ["ただいま", "只今"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng ただいま thay cho いま.",
        "example_ja": "ただいま席を外しております。",
        "example_vi": "Hiện người đó đang vắng mặt tại chỗ ngồi ạ.",
    },
    {
        "source_word": "もうすぐ",
        "source_reading": "もうすぐ",
        "meaning_vi": "chẳng bao lâu nữa / sắp sửa",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "間もなく",
        "canonical_reading": "まもなく",
        "acceptable_variants": ["間もなく", "まもなく"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng 間もなく trong thông báo công sở và phát thanh tàu xe.",
        "example_ja": "間もなく開演いたします。",
        "example_vi": "Chương trình sẽ bắt đầu ngay sau đây ạ.",
    },
    {
        "source_word": "すごく",
        "source_reading": "すごく",
        "meaning_vi": "vô cùng / rất",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "大変",
        "canonical_reading": "たいへん",
        "acceptable_variants": ["大変", "たいへん"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng 大変 thay vì すごく/とても khi nhấn mạnh mức độ cảm ơn hoặc xin lỗi.",
        "example_ja": "大変勉強になりました。",
        "example_vi": "Tôi đã học hỏi được rất nhiều điều ạ.",
    },
    {
        "source_word": "本当に",
        "source_reading": "ほんとうに",
        "meaning_vi": "thực sự / thành thật",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "誠に",
        "canonical_reading": "まことに",
        "acceptable_variants": ["誠に", "まことに"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng 誠に thay cho 本当に.",
        "example_ja": "誠に申し訳ございません。",
        "example_vi": "Thực lòng chúng tôi vô cùng xin lỗi ạ.",
    },
    {
        "source_word": "一番",
        "source_reading": "いちばん",
        "meaning_vi": "nhất / tối đa",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "最も",
        "canonical_reading": "もっとも",
        "acceptable_variants": ["最も", "もっとも"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_time_adverbs",
        "formula": "Thời gian & Phó từ công sở",
        "subject_hint_vi": "🏢 Diễn đạt thời gian & mức độ chuyên nghiệp",
        "explanation_vi": "Dùng 最も thay cho 一番 trong các bài thuyết trình và báo cáo số liệu.",
        "example_ja": "これが最も重要なポイントです。",
        "example_vi": "Đây chính là điểm quan trọng nhất ạ.",
    },
]

# 6. business_phrases: 15 entries
BUSINESS_PHRASES_DATA = [
    {
        "source_word": "いくら",
        "source_reading": "いくら",
        "meaning_vi": "bao nhiêu tiền",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "おいくら",
        "canonical_reading": "おいくら",
        "acceptable_variants": ["おいくら", "お幾ら"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N5",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Dùng おいくら thay vì いくら khi hỏi chi phí hoặc giá dịch vụ.",
        "example_ja": "おいくらになりますか。",
        "example_vi": "Tổng cộng là bao nhiêu tiền ạ?",
    },
    {
        "source_word": "すみません",
        "source_reading": "すみません",
        "meaning_vi": "thành thật xin lỗi (chuẩn công sở)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "申し訳ございません",
        "canonical_reading": "もうしわけございません",
        "acceptable_variants": ["申し訳ございません", "もうしわけございません", "申し訳ありません"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "申し訳ございません",
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Câu xin lỗi chuẩn mực cao cấp trong công ty, thay thế hoàn toàn cho すみません.",
        "example_ja": "ご迷惑をおかけして、大変申し訳ございません。",
        "example_vi": "Làm phiền ngài như vậy, tôi thực sự vô cùng xin lỗi ạ.",
    },
    {
        "source_word": "わかりました",
        "source_reading": "わかりました",
        "meaning_vi": "tôi đã hiểu rõ mệnh lệnh",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "かしこまりました",
        "canonical_reading": "かしこまりました",
        "acceptable_variants": ["かしこまりました", "承知いたしました", "しょうちいたしました"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "かしこまりました",
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Câu nhận lệnh kinh điển trước khách hàng và cấp trên.",
        "example_ja": "かしこまりました、直ちに対応いたします。",
        "example_vi": "Tôi đã hiểu rõ rồi ạ, xin xử lý ngay lập tức.",
    },
    {
        "source_word": "ありがとう",
        "source_reading": "ありがとう",
        "meaning_vi": "chân thành cảm ơn quý khách",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "誠にありがとうございます",
        "canonical_reading": "まことにありがとうございます",
        "acceptable_variants": ["誠にありがとうございます", "まことにありがとうございます", "ありがとうございます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Lời cảm ơn lịch sự và đầy đủ nhất dành cho đối tác.",
        "example_ja": "ご支援いただき、誠にありがとうございます。",
        "example_vi": "Chúng tôi xin chân thành cảm ơn sự hỗ trợ của quý vị ạ.",
    },
    {
        "source_word": "どういたしまして",
        "source_reading": "どういたしまして",
        "meaning_vi": "dạ không có chi ạ (khiêm tốn tuyệt đối)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "とんでもないことでございます",
        "canonical_reading": "とんでもないことでございます",
        "acceptable_variants": ["とんでもないことでございます", "とんでもございません", "とんでもないです"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Cách đáp lại lời khen hoặc lời cảm ơn của người bề trên, lịch sự hơn どういたしまして.",
        "example_ja": "とんでもないことでございます、お役に立てて光栄です。",
        "example_vi": "Dạ không có chi đâu ạ, giúp ích được cho ngài là niềm vinh hạnh của tôi.",
    },
    {
        "source_word": "よろしく",
        "source_reading": "よろしく",
        "meaning_vi": "kính mong được chiếu cố giúp đỡ",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "何卒よろしくお願い申し上げます",
        "canonical_reading": "なにとぞよろしくおねがいもうしあげます",
        "acceptable_variants": ["何卒よろしくお願い申し上げます", "なにとぞよろしくおねがいもうしあげます", "よろしくお願いいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "何卒よろしくお願い申し上げます",
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Lời nhờ vả trang trọng tột bậc ở đuôi thư hoặc cuối buổi đàm phán.",
        "example_ja": "今後とも何卒よろしくお願い申し上げます。",
        "example_vi": "Từ nay về sau cũng kính mong ngài tiếp tục giúp đỡ cho ạ.",
    },
    {
        "source_word": "お疲れ様",
        "source_reading": "おつかれさま",
        "meaning_vi": "ngài đã vất vả rồi ạ",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "お疲れ様でございます",
        "canonical_reading": "おつかれさまでございます",
        "acceptable_variants": ["お疲れ様でございます", "おつかれさまでございます", "お疲れ様です"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Chào hỏi động viên đồng nghiệp cuối ngày làm việc.",
        "example_ja": "本日もお疲れ様でございました。",
        "example_vi": "Hôm nay ngài cũng đã vất vả nhiều rồi ạ.",
    },
    {
        "source_word": "ご苦労様",
        "source_reading": "ごくろうさま",
        "meaning_vi": "ngài đã vất vả (chỉ dùng cho bề dưới)",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "ご苦労様でございます",
        "canonical_reading": "ごくろうさまでございます",
        "acceptable_variants": ["ご苦労様でございます", "ごくろうさまでございます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": None,
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Lưu ý: Chỉ cấp trên nói với cấp dưới hoặc bảo vệ, giao hàng.",
        "example_ja": "配達ご苦労様でございます。",
        "example_vi": "Anh giao hàng vất vả rồi ạ.",
    },
    {
        "source_word": "しばらくです",
        "source_reading": "しばらくです",
        "meaning_vi": "lâu ngày không gặp / đã lâu không diện kiến",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "ご無沙汰しております",
        "canonical_reading": "ごぶさたしております",
        "acceptable_variants": ["ご無沙汰しております", "ごぶさたしております", "お久しぶりでございます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご無沙汰しております",
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Lời chào khi gặp lại đối tác sau một khoảng thời gian dài không liên lạc.",
        "example_ja": "大変ご無沙汰しております、お変わりございませんか。",
        "example_vi": "Đã lâu lắm rồi không diện kiến ngài, dạo này ngài vẫn khỏe chứ ạ?",
    },
    {
        "source_word": "お邪魔します",
        "source_reading": "おじゃまします",
        "meaning_vi": "xin phép làm phiền khi vào phòng",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "お邪魔いたします",
        "canonical_reading": "おじゃまいたします",
        "acceptable_variants": ["お邪魔いたします", "おじゃまいたします", "お邪魔します"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お邪魔いたします",
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Chào hỏi khi bước chân vào văn phòng hoặc nhà riêng của người khác.",
        "example_ja": "失礼ですが、お邪魔いたします。",
        "example_vi": "Tôi xin phép được vào phòng làm phiền ạ.",
    },
    {
        "source_word": "失礼します",
        "source_reading": "しつれいします",
        "meaning_vi": "tôi xin phép thất lễ",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "失礼いたします",
        "canonical_reading": "しつれいいたします",
        "acceptable_variants": ["失礼いたします", "しつれいいたします", "失礼します"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "失礼いたします",
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Dùng khi bước vào/ra khỏi phòng hoặc kết thúc cuộc gọi điện thoại.",
        "example_ja": "それでは、失礼いたします。",
        "example_vi": "Nếu vậy thì tôi xin phép gác máy / ra về ạ.",
    },
    {
        "source_word": "わかりました(承知)",
        "source_reading": "わかりました",
        "meaning_vi": "tôi đã thấu suốt yêu cầu",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "承知いたしました",
        "canonical_reading": "しょうちいたしました",
        "acceptable_variants": ["承知いたしました", "しょうちいたしました", "承知しました"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "承知いたしました",
        "category": "business_words",
        "jlpt_level": "N4",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Biểu thị sự thấu suốt và cam kết hoàn thành chỉ thị.",
        "example_ja": "件の件、承知いたしました。",
        "example_vi": "Về việc đó tôi đã nắm rõ và ghi nhận rồi ạ.",
    },
    {
        "source_word": "わかりました(了解)",
        "source_reading": "わかりました",
        "meaning_vi": "tôi đã đồng ý tiếp nhận",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "了承いたしました",
        "canonical_reading": "りょうしょういたしました",
        "acceptable_variants": ["了承いたしました", "りょうしょういたしました", "かしこまりました"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "了承いたしました",
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Đồng ý với các điều kiện thay đổi do đối tác đưa ra.",
        "example_ja": "スケジュールの変更、了承いたしました。",
        "example_vi": "Về việc thay đổi lịch trình, tôi xin phép tiếp nhận đồng ý ạ.",
    },
    {
        "source_word": "すみません(お詫び)",
        "source_reading": "すみません",
        "meaning_vi": "thật áy náy / lấy làm ái ngại",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "恐れ入ります",
        "canonical_reading": "おそれいります",
        "acceptable_variants": ["恐れ入ります", "おそれいります", "恐縮でございます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "恐れ入ります",
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Biểu cảm áy náy tinh tế khi được người khác quan tâm hoặc giúp đỡ.",
        "example_ja": "温かいお心遣い、恐れ入ります。",
        "example_vi": "Trước sự quan tâm ấm áp của ngài, tôi thật lấy làm áy náy cảm kích ạ.",
    },
    {
        "source_word": "すみません(呼びかけ)",
        "source_reading": "すみません",
        "meaning_vi": "xin mạn phép làm phiền ngài",
        "target_type": "business",
        "target_label_vi": "Từ thương mại (ビジネス語)",
        "canonical": "恐れ入りますが",
        "canonical_reading": "おそれいりますが",
        "acceptable_variants": ["恐れ入りますが", "おそれいりますが", "恐縮ですが"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "恐れ入りますが",
        "category": "business_words",
        "jlpt_level": "N3",
        "formula_id": "business_phrases",
        "formula": "Cụm từ ứng đối công sở kinh điển",
        "subject_hint_vi": "🏢 Phản xạ câu cửa miệng đối tác & khách hàng",
        "explanation_vi": "Cụm từ đệm cực phẩm mở đầu trước khi nhờ vả cấp trên hoặc khách hàng.",
        "example_ja": "恐れ入りますが、もう一度ご説明願えますか。",
        "example_vi": "Xin mạn phép làm phiền ngài, ngài có thể giải thích lại một lần nữa giúp tôi được không ạ?",
    },
]
