# -*- coding: utf-8 -*-
"""Kenjougo data definitions (93 entries total across 5 formulas):
1. kenjougo_irregular: 25 entries
2. kenjougo_o_suru: 20 entries
3. kenjougo_go_suru: 18 entries
4. kenjougo_moushiageru: 15 entries
5. kenjougo_permissive: 15 entries
"""

from __future__ import annotations

# 1. kenjougo_irregular: 25 entries
KENJOUGO_IRREGULAR_DATA = [
    {
        "source_word": "する(khiêm nhường)",
        "source_reading": "する",
        "meaning_vi": "làm (bản thân tôi làm)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "いたす",
        "canonical_reading": "いたす",
        "acceptable_variants": ["いたす", "いたします", "いたしまして", "いたしました"],
        "triplet_sonkeigo": "なさる",
        "triplet_kenjougo": "いたす",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ đặc biệt của する, dùng cực kỳ thường xuyên trong giao tiếp công sở.",
        "example_ja": "私が担当いたします。",
        "example_vi": "Tôi xin phép đảm nhận việc này ạ.",
    },
    {
        "source_word": "行く(khiêm nhường)",
        "source_reading": "いく",
        "meaning_vi": "đi (tôi đi)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "参る",
        "canonical_reading": "まいる",
        "acceptable_variants": ["参る", "まいる", "参ります", "まいります", "伺う", "うかがう"],
        "triplet_sonkeigo": "いらっしゃる",
        "triplet_kenjougo": "参る",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 行く (và 来る).",
        "example_ja": "明日、10時に参ります。",
        "example_vi": "Ngày mai lúc 10 giờ tôi xin phép tới ạ.",
    },
    {
        "source_word": "来る(khiêm nhường)",
        "source_reading": "くる",
        "meaning_vi": "đến (tôi đến)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "参る",
        "canonical_reading": "まいる",
        "acceptable_variants": ["参る", "まいる", "参ります", "まいります"],
        "triplet_sonkeigo": "いらっしゃる",
        "triplet_kenjougo": "参る",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 来る.",
        "example_ja": "ベトナムから参りました。",
        "example_vi": "Tôi đến từ Việt Nam ạ.",
    },
    {
        "source_word": "居る(khiêm nhường)",
        "source_reading": "いる",
        "meaning_vi": "ở / có mặt (tôi có mặt)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "おる",
        "canonical_reading": "おる",
        "acceptable_variants": ["おる", "おります", "おりまして", "おりました"],
        "triplet_sonkeigo": "いらっしゃる",
        "triplet_kenjougo": "おる",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Đinh trọng ngữ / khiêm nhường ngữ của いる.",
        "example_ja": "田中は今、席を外しております。",
        "example_vi": "Tanaka hiện đang vắng mặt tại chỗ ngồi ạ.",
    },
    {
        "source_word": "言う(khiêm nhường)",
        "source_reading": "いう",
        "meaning_vi": "nói / tên là",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "申す",
        "canonical_reading": "もうす",
        "acceptable_variants": ["申す", "もうす", "申します", "もうします", "申し上げます"],
        "triplet_sonkeigo": "おっしゃる",
        "triplet_kenjougo": "申す",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 言う khi xưng tên hoặc phát biểu.",
        "example_ja": "グエンと申します。",
        "example_vi": "Tôi tên là Nguyễn ạ.",
    },
    {
        "source_word": "食べる(khiêm nhường)",
        "source_reading": "たべる",
        "meaning_vi": "ăn / dùng bữa",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "いただく",
        "canonical_reading": "いただく",
        "acceptable_variants": ["いただく", "いただきます", "いただきました", "頂戴する"],
        "triplet_sonkeigo": "召し上がる",
        "triplet_kenjougo": "いただく",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 食べる và 飲む.",
        "example_ja": "美味しくいただきました。",
        "example_vi": "Tôi đã dùng bữa rất ngon miệng ạ.",
    },
    {
        "source_word": "飲む(khiêm nhường)",
        "source_reading": "のむ",
        "meaning_vi": "uống",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "いただく",
        "canonical_reading": "いただく",
        "acceptable_variants": ["いただく", "いただきます", "いただきました"],
        "triplet_sonkeigo": "召し上がる",
        "triplet_kenjougo": "いただく",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 飲む.",
        "example_ja": "お茶をいただきます。",
        "example_vi": "Tôi xin phép uống trà ạ.",
    },
    {
        "source_word": "見る(khiêm nhường)",
        "source_reading": "みる",
        "meaning_vi": "xem / xem xét kính cẩn",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "拝見する",
        "canonical_reading": "はいけんする",
        "acceptable_variants": ["拝見する", "はいけんする", "拝見します", "はいけんします", "拝見いたします"],
        "triplet_sonkeigo": "ご覧になる",
        "triplet_kenjougo": "拝見する",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 見る khi xem đồ vật/tài liệu của đối tác.",
        "example_ja": "メールを拝見いたしました。",
        "example_vi": "Tôi đã đọc email của quý vị rồi ạ.",
    },
    {
        "source_word": "知る(khiêm nhường)",
        "source_reading": "しる",
        "meaning_vi": "biết / nắm được",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "存じる",
        "canonical_reading": "ぞんじる",
        "acceptable_variants": ["存じる", "ぞんじる", "存じます", "ぞんじます", "存じております"],
        "triplet_sonkeigo": "ご存知だ",
        "triplet_kenjougo": "存じる",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 知っている và 思う.",
        "example_ja": "その件は存じております。",
        "example_vi": "Tôi có biết về việc đó rồi ạ.",
    },
    {
        "source_word": "もらう",
        "source_reading": "もらう",
        "meaning_vi": "nhận từ ai đó",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "いただく",
        "canonical_reading": "いただく",
        "acceptable_variants": ["いただく", "いただきます", "いただきました", "頂戴する", "ちょうだいする"],
        "triplet_sonkeigo": "くださる",
        "triplet_kenjougo": "いただく",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của もらう.",
        "example_ja": "お土産をいただきました。",
        "example_vi": "Tôi đã nhận được món quà lưu niệm ạ.",
    },
    {
        "source_word": "あげる",
        "source_reading": "あげる",
        "meaning_vi": "tặng / biếu (người trên)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "差し上げる",
        "canonical_reading": "さしあげる",
        "acceptable_variants": ["差し上げる", "さしあげる", "差し上げます", "さしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "差し上げる",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của あげる (tặng người trên hoặc khách hàng).",
        "example_ja": "資料を差し上げます。",
        "example_vi": "Tôi xin gửi tặng ngài tài liệu ạ.",
    },
    {
        "source_word": "会う(khiêm nhường)",
        "source_reading": "あう",
        "meaning_vi": "gặp gỡ cấp trên / khách hàng",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お目にかかる",
        "canonical_reading": "おめにかかる",
        "acceptable_variants": ["お目にかかる", "おめにかかる", "お目にかかります", "お目にかかれて"],
        "triplet_sonkeigo": "お会いになる",
        "triplet_kenjougo": "お目にかかる",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 会う khi mình diện kiến cấp trên hoặc đối tác.",
        "example_ja": "お目にかかれて光栄です。",
        "example_vi": "Rất vinh hạnh được gặp gỡ ngài ạ.",
    },
    {
        "source_word": "聞く(hỏi thăm)",
        "source_reading": "きく",
        "meaning_vi": "hỏi thăm / nghe ngóng",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "伺う",
        "canonical_reading": "うかがう",
        "acceptable_variants": ["伺う", "うかがう", "伺います", "うかがいます", "伺いました"],
        "triplet_sonkeigo": "お聞きになる",
        "triplet_kenjougo": "伺う",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 聞く (hỏi ý kiến hoặc lắng nghe tin từ đối tác).",
        "example_ja": "ご意見を伺いたいと存じます。",
        "example_vi": "Tôi xin phép muốn lắng nghe ý kiến của ngài ạ.",
    },
    {
        "source_word": "訪ねる",
        "source_reading": "たずねる",
        "meaning_vi": "đến thăm văn phòng đối tác",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "伺う",
        "canonical_reading": "うかがう",
        "acceptable_variants": ["伺う", "うかがう", "伺います", "うかがいます"],
        "triplet_sonkeigo": "いらっしゃる",
        "triplet_kenjougo": "伺う",
        "category": "kenjougo_irregular",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 訪ねる (đến thăm nhà hoặc công ty đối tác).",
        "example_ja": "明日御社へ伺います。",
        "example_vi": "Ngày mai tôi xin phép ghé thăm quý công ty ạ.",
    },
    {
        "source_word": "読む(khiêm nhường)",
        "source_reading": "よむ",
        "meaning_vi": "đọc (kính cẩn đọc thư/sách của sếp)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "拝読する",
        "canonical_reading": "はいどくする",
        "acceptable_variants": ["拝読する", "はいどくする", "拝読します", "はいどくします", "拝読いたします"],
        "triplet_sonkeigo": "お読みになる",
        "triplet_kenjougo": "拝読する",
        "category": "kenjougo_irregular",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 読む khi mình đọc thư từ, bài viết của đối tác.",
        "example_ja": "お手紙を拝読いたしました。",
        "example_vi": "Tôi đã kính cẩn đọc bức thư của ngài rồi ạ.",
    },
    {
        "source_word": "伝える",
        "source_reading": "つたえる",
        "meaning_vi": "truyền đạt / nhắn lại",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "申し伝える",
        "canonical_reading": "もうしつたえる",
        "acceptable_variants": ["申し伝える", "もうしつたえる", "申し伝えます", "もうしつたえます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "申し伝える",
        "category": "kenjougo_irregular",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Dùng khi nhắn lời của khách cho người nội bộ công ty mình.",
        "example_ja": "その旨、担当者に申し伝えます。",
        "example_vi": "Nội dung đó tôi xin chuyển lời tới người phụ trách ạ.",
    },
    {
        "source_word": "借りる",
        "source_reading": "かりる",
        "meaning_vi": "mượn đồ của cấp trên",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "拝借する",
        "canonical_reading": "はいしゃくする",
        "acceptable_variants": ["拝借する", "はいしゃくする", "拝借します", "はいしゃくします", "お借りする"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "拝借する",
        "category": "kenjougo_irregular",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ trang trọng của 借りる.",
        "example_ja": "お知恵を拝借したいと存じます。",
        "example_vi": "Tôi xin phép mượn trí tuệ/ý kiến của ngài ạ.",
    },
    {
        "source_word": "見せる(khiêm nhường)",
        "source_reading": "みせる",
        "meaning_vi": "cho xem (kính cẩn)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お目にかける",
        "canonical_reading": "おめにかける",
        "acceptable_variants": ["お目にかける", "おめにかける", "お目にかけます", "おめにかければ"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お目にかける",
        "category": "kenjougo_irregular",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 見せる khi đưa cho khách hoặc bề trên xem.",
        "example_ja": "ぜひ最新作をお目にかけたいと存じます。",
        "example_vi": "Tôi rất muốn đưa tác phẩm mới nhất cho ngài xem ạ.",
    },
    {
        "source_word": "見せる(trang trọng)",
        "source_reading": "みせる",
        "meaning_vi": "trình cho xem",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご覧に入れる",
        "canonical_reading": "ごらんにいれる",
        "acceptable_variants": ["ご覧に入れる", "ごらんにいれる", "ご覧に入れます", "ごらんにいれます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご覧に入れる",
        "category": "kenjougo_irregular",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Biến thể khiêm nhường rất trang trọng của 見せる.",
        "example_ja": "資料の原本をご覧に入れます。",
        "example_vi": "Tôi xin trình bản gốc tài liệu để ngài xem ạ.",
    },
    {
        "source_word": "聞く(lắng nghe)",
        "source_reading": "きく",
        "meaning_vi": "lắng nghe chăm chú / lĩnh giáo",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "拝聴する",
        "canonical_reading": "はいちょうする",
        "acceptable_variants": ["拝聴する", "はいちょうする", "拝聴します", "はいちょうします", "拝聴いたします"],
        "triplet_sonkeigo": "お聞きになる",
        "triplet_kenjougo": "拝聴する",
        "category": "kenjougo_irregular",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 聞く khi chăm chú lắng nghe bài diễn thuyết.",
        "example_ja": "素晴らしいご講演を拝聴いたしました。",
        "example_vi": "Tôi đã được lắng nghe bài phát biểu tuyệt vời ạ.",
    },
    {
        "source_word": "承知する",
        "source_reading": "しょうちする",
        "meaning_vi": "tiếp nhận / hiểu rõ mệnh lệnh",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "承る",
        "canonical_reading": "うけたまわる",
        "acceptable_variants": ["承る", "うけたまわる", "承ります", "うけたまわります"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "承る",
        "category": "kenjougo_irregular",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Từ ngữ tinh tế khi tiếp nhận đơn hàng, yêu cầu từ khách hàng.",
        "example_ja": "ご注文を承りました。",
        "example_vi": "Tôi đã tiếp nhận đơn đặt hàng của quý khách rồi ạ.",
    },
    {
        "source_word": "知る(người)",
        "source_reading": "しる",
        "meaning_vi": "biết ai đó (người bề trên)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "存じ上げる",
        "canonical_reading": "ぞんじあげる",
        "acceptable_variants": ["存じ上げる", "ぞんじあげる", "存じ上げております", "ぞんじあげております"],
        "triplet_sonkeigo": "ご存知だ",
        "triplet_kenjougo": "存じ上げる",
        "category": "kenjougo_irregular",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Dùng khi biết một người hoặc danh tiếng của một nhân vật quan trọng.",
        "example_ja": "田中先生のお噂はかねてより存じ上げております。",
        "example_vi": "Tôi đã biết danh tiếng của thầy Tanaka từ trước rồi ạ.",
    },
    {
        "source_word": "思う(khiêm nhường)",
        "source_reading": "おもう",
        "meaning_vi": "nghĩ rằng / cho rằng",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "存じる",
        "canonical_reading": "ぞんじる",
        "acceptable_variants": ["存じる", "ぞんじる", "存じます", "ぞんじます"],
        "triplet_sonkeigo": "お思いになる",
        "triplet_kenjougo": "存じる",
        "category": "kenjougo_irregular",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 思う khi biểu đạt ý kiến cá nhân khiêm tốn.",
        "example_ja": "問題ないと存じます。",
        "example_vi": "Tôi nghĩ là không có vấn đề gì ạ.",
    },
    {
        "source_word": "もらう(trang trọng)",
        "source_reading": "もらう",
        "meaning_vi": "nhận lãnh kính cẩn",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "頂戴する",
        "canonical_reading": "ちょうだいする",
        "acceptable_variants": ["頂戴する", "ちょうだいする", "頂戴します", "ちょうだいします", "頂戴いたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "頂戴する",
        "category": "kenjougo_irregular",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ rất lịch sự của もらう khi nhận danh thiếp, thời gian.",
        "example_ja": "名刺を頂戴いたします。",
        "example_vi": "Tôi xin phép nhận danh thiếp của ngài ạ.",
    },
    {
        "source_word": "届ける(khiêm nhường)",
        "source_reading": "とどける",
        "meaning_vi": "đem tới tận nơi dâng lên",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お届けにあがる",
        "canonical_reading": "おとどけにあがる",
        "acceptable_variants": ["お届けにあがる", "おとどけにあがる", "お届けにあがります", "お届けに上がります"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お届けにあがる",
        "category": "kenjougo_irregular",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_irregular",
        "formula": "Bất quy tắc (Đặc biệt)",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ diễn đạt hành động đích thân mang đồ đến nhà/công ty khách.",
        "example_ja": "午後、書類をお届けにあがります。",
        "example_vi": "Buổi chiều tôi xin phép đem tài liệu đến tận nơi ạ.",
    },
]

# 2. kenjougo_o_suru: 20 entries
KENJOUGO_O_SURU_DATA = [
    {
        "source_word": "持つ",
        "source_reading": "もつ",
        "meaning_vi": "cầm / xách đồ hộ khách",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お持ちする",
        "canonical_reading": "おもちする",
        "acceptable_variants": ["お持ちする", "おもちする", "お持ちします", "おもちします", "お持ちいたす", "お持ちいたします"],
        "triplet_sonkeigo": "お持ちになる",
        "triplet_kenjougo": "お持ちする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Công thức khiêm nhường quy tắc chuẩn: お + Động từ nhóm 1 & 2 thể stem + する / いたします.",
        "example_ja": "荷物をお持ちいたします。",
        "example_vi": "Tôi xin phép xách hành lý giúp ngài ạ.",
    },
    {
        "source_word": "送る(khiêm nhường)",
        "source_reading": "おくる",
        "meaning_vi": "gửi / tiễn đưa khách",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お送りする",
        "canonical_reading": "おおくりする",
        "acceptable_variants": ["お送りする", "おおくりする", "お送りします", "おおくりします", "お送りいたします"],
        "triplet_sonkeigo": "お送りになる",
        "triplet_kenjougo": "お送りする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi mình gửi hàng hoặc tiễn khách ra ga.",
        "example_ja": "駅まで車でお送りいたします。",
        "example_vi": "Tôi xin phép đưa xe tiễn ngài ra tận ga ạ.",
    },
    {
        "source_word": "届ける(quy tắc)",
        "source_reading": "とどける",
        "meaning_vi": "chuyển phát / đem tới",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お届けする",
        "canonical_reading": "おとどけする",
        "acceptable_variants": ["お届けする", "おとどけする", "お届けします", "おとどけします", "お届けいたします"],
        "triplet_sonkeigo": "お届けになる",
        "triplet_kenjougo": "お届けする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 届ける.",
        "example_ja": "明日、商品をお届けいたします。",
        "example_vi": "Ngày mai chúng tôi xin phép giao hàng tới ngài ạ.",
    },
    {
        "source_word": "手伝う(khiêm nhường)",
        "source_reading": "てつだう",
        "meaning_vi": "giúp đỡ cấp trên",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お手伝いする",
        "canonical_reading": "おてつだいする",
        "acceptable_variants": ["お手伝いする", "おてつだいする", "お手伝いします", "おてつだいします", "お手伝いいたします"],
        "triplet_sonkeigo": "お手伝いになる",
        "triplet_kenjougo": "お手伝いする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi chủ động đề nghị giúp sếp.",
        "example_ja": "何かお手伝いいたしましょうか。",
        "example_vi": "Tôi có thể phụ giúp ngài việc gì không ạ?",
    },
    {
        "source_word": "迎える",
        "source_reading": "むかえる",
        "meaning_vi": "đón tiếp khách quý",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お迎えする",
        "canonical_reading": "おむかえする",
        "acceptable_variants": ["お迎えする", "おむかえする", "お迎えします", "おむかえします", "お迎えいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お迎えする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi đón khách tại sân bay.",
        "example_ja": "空港までお迎えに上がります。",
        "example_vi": "Chúng tôi xin phép ra sân bay đón ngài ạ.",
    },
    {
        "source_word": "預かる",
        "source_reading": "あずかる",
        "meaning_vi": "giữ hộ / trông nom đồ",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お預かりする",
        "canonical_reading": "おあずかりする",
        "acceptable_variants": ["お預かりする", "おあずかりする", "お預かりします", "おあずかりします", "お預かりいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お預かりする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Dùng trong khách sạn hoặc quầy tiếp tân khi giữ đồ cho khách.",
        "example_ja": "お荷物をお預かりいたします。",
        "example_vi": "Tôi xin phép nhận giữ hành lý của ngài ạ.",
    },
    {
        "source_word": "渡す(khiêm nhường)",
        "source_reading": "わたす",
        "meaning_vi": "trao / nộp cho cấp trên",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お渡しする",
        "canonical_reading": "おわたしする",
        "acceptable_variants": ["お渡しする", "おわたしする", "お渡しします", "おわたしします", "お渡しいたします"],
        "triplet_sonkeigo": "お渡しになる",
        "triplet_kenjougo": "お渡しする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 渡す.",
        "example_ja": "領収書をお渡しいたします。",
        "example_vi": "Tôi xin phép gửi biên lai cho ngài ạ.",
    },
    {
        "source_word": "電話する(khiêm nhường)",
        "source_reading": "でんわする",
        "meaning_vi": "gọi điện thoại cho khách",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お電話いたす",
        "canonical_reading": "おでんわいたす",
        "acceptable_variants": ["お電話いたす", "おでんわいたす", "お電話いたします", "おでんわいたします", "お電話します"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お電話いたす",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "お電話 + いたします (ngoại lệ danh từ dùng お).",
        "example_ja": "後ほど改めてお電話いたします。",
        "example_vi": "Lát nữa tôi xin phép gọi điện lại ạ.",
    },
    {
        "source_word": "呼ぶ(khiêm nhường)",
        "source_reading": "よぶ",
        "meaning_vi": "gọi taxi / bác sĩ hộ khách",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お呼びする",
        "canonical_reading": "およびする",
        "acceptable_variants": ["お呼びする", "およびする", "お呼びします", "およびします", "お呼びいたします"],
        "triplet_sonkeigo": "お呼びになる",
        "triplet_kenjougo": "お呼びする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 呼ぶ khi gọi taxi giúp khách.",
        "example_ja": "すぐにタクシーをお呼びいたします。",
        "example_vi": "Tôi xin phép gọi taxi ngay cho ngài ạ.",
    },
    {
        "source_word": "連れる",
        "source_reading": "つれる",
        "meaning_vi": "dẫn đường / đưa đi",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お連れする",
        "canonical_reading": "おつれする",
        "acceptable_variants": ["お連れする", "おつれする", "お連れします", "おつれします", "お連れいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お連れする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi dẫn khách đến phòng họp.",
        "example_ja": "応接室へお連れいたします。",
        "example_vi": "Tôi xin phép đưa ngài sang phòng tiếp khách ạ.",
    },
    {
        "source_word": "助ける",
        "source_reading": "たすける",
        "meaning_vi": "hỗ trợ / cứu giúp",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お助けする",
        "canonical_reading": "おたすけする",
        "acceptable_variants": ["お助けする", "おたすけする", "お助けします", "おたすけします", "お助けいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お助けする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 助ける.",
        "example_ja": "少しでもお助けできれば幸いです。",
        "example_vi": "Nếu có thể giúp đỡ ngài chút nào tôi rất hân hạnh ạ.",
    },
    {
        "source_word": "尋ねる",
        "source_reading": "たずねる",
        "meaning_vi": "hỏi xin thông tin",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お尋ねする",
        "canonical_reading": "おたずねする",
        "acceptable_variants": ["お尋ねする", "おたずねする", "お尋ねします", "おたずねします", "お尋ねいたします"],
        "triplet_sonkeigo": "お聞きになる",
        "triplet_kenjougo": "お尋ねする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi mình xin phép hỏi sếp điều gì.",
        "example_ja": "一点だけお尋ねしたいことがございます。",
        "example_vi": "Tôi xin phép có một điểm muốn hỏi ngài ạ.",
    },
    {
        "source_word": "調べる(khiêm nhường)",
        "source_reading": "しらべる",
        "meaning_vi": "tra cứu tìm hiểu giúp khách",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お調べする",
        "canonical_reading": "おしらべする",
        "acceptable_variants": ["お調べする", "おしらべする", "お調べします", "おしらべします", "お調べいたします"],
        "triplet_sonkeigo": "お調べになる",
        "triplet_kenjougo": "お調べする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi nhân viên tra cứu hồ sơ giúp khách.",
        "example_ja": "在庫をお調べいたします。",
        "example_vi": "Tôi xin phép tra cứu lượng hàng tồn kho ạ.",
    },
    {
        "source_word": "直す",
        "source_reading": "なおす",
        "meaning_vi": "sửa chữa / chỉnh sửa",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お直しする",
        "canonical_reading": "おなおしする",
        "acceptable_variants": ["お直しする", "おなおしする", "お直しします", "おなおしします", "お直しいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お直しする",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi sửa đồ áo hoặc sửa văn bản cho cấp trên.",
        "example_ja": "すぐに資料をお直しいたします。",
        "example_vi": "Tôi xin phép sửa ngay bản tài liệu ạ.",
    },
    {
        "source_word": "借りる(quy tắc)",
        "source_reading": "かりる",
        "meaning_vi": "mượn đồ (dạng quy tắc)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お借りする",
        "canonical_reading": "おかりする",
        "acceptable_variants": ["お借りする", "おかりする", "お借りします", "おかりします", "お借りいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お借りする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ quy tắc của 借りる.",
        "example_ja": "傘をお借りしてもよろしいでしょうか。",
        "example_vi": "Tôi có thể xin phép mượn chiếc ô được không ạ?",
    },
    {
        "source_word": "伝える(quy tắc)",
        "source_reading": "つたえる",
        "meaning_vi": "nhắn lại / báo lại",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お伝えする",
        "canonical_reading": "おつたえする",
        "acceptable_variants": ["お伝えする", "おつたえする", "お伝えします", "おつたえします", "お伝えいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お伝えする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 伝える.",
        "example_ja": "感謝の気持ちをお伝えいたします。",
        "example_vi": "Tôi xin gửi lời cảm ơn chân thành đến ngài ạ.",
    },
    {
        "source_word": "貸す",
        "source_reading": "かす",
        "meaning_vi": "cho mượn",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お貸しする",
        "canonical_reading": "おかしする",
        "acceptable_variants": ["お貸しする", "おかしする", "お貸しします", "おかしします", "お貸しいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お貸しする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi mình cho đối tác mượn bút hoặc sạc.",
        "example_ja": "こちらの充電器をお貸しいたします。",
        "example_vi": "Tôi xin phép cho ngài mượn bộ sạc này ạ.",
    },
    {
        "source_word": "待たせる",
        "source_reading": "またせる",
        "meaning_vi": "để khách phải chờ lâu",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お待たせする",
        "canonical_reading": "おまたせする",
        "acceptable_variants": ["お待たせする", "おまたせする", "お待たせします", "おまたせします", "お待たせいたしました"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お待たせする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Lời xin lỗi kinh điển khi để khách chờ: 大変お待たせいたしました.",
        "example_ja": "大変お待たせいたしました。",
        "example_vi": "Xin lỗi vì đã để quý khách phải đợi lâu ạ.",
    },
    {
        "source_word": "案内する(お)",
        "source_reading": "あんないする",
        "meaning_vi": "dẫn đường cho khách",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お案内する",
        "canonical_reading": "おあんないする",
        "acceptable_variants": ["お案内する", "おあんないする", "お案内します", "ご案内する", "ご案内します"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お案内する",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Biến thể khẩu ngữ khiêm tốn của 案内する.",
        "example_ja": "エレベーターまでお案内いたします。",
        "example_vi": "Tôi xin phép dẫn ngài tới thang máy ạ.",
    },
    {
        "source_word": "知らせる",
        "source_reading": "しらせる",
        "meaning_vi": "thông báo cho khách",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お知らせする",
        "canonical_reading": "おしらせする",
        "acceptable_variants": ["お知らせする", "おしらせする", "お知らせします", "おしらせします", "お知らせいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お知らせする",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_o_suru",
        "formula": "お + V(stem) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 知らせる.",
        "example_ja": "決まり次第、すぐにお知らせいたします。",
        "example_vi": "Ngay khi có quyết định chúng tôi xin thông báo ngay ạ.",
    },
]

# 3. kenjougo_go_suru: 18 entries
KENJOUGO_GO_SURU_DATA = [
    {
        "source_word": "連絡する(khiêm nhường)",
        "source_reading": "れんらくする",
        "meaning_vi": "tôi xin liên lạc lại",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご連絡いたす",
        "canonical_reading": "ごれんらくいたす",
        "acceptable_variants": ["ご連絡いたす", "ごれんらくいたす", "ご連絡いたします", "ごれんらくいたします", "ご連絡する", "ご連絡します"],
        "triplet_sonkeigo": "ご連絡になる",
        "triplet_kenjougo": "ご連絡いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Công thức khiêm nhường chuẩn cho từ gốc Hán: ご + N + いたします.",
        "example_ja": "折り返しご連絡いたします。",
        "example_vi": "Tôi xin phép liên lạc lại sau ạ.",
    },
    {
        "source_word": "案内する(khiêm nhường)",
        "source_reading": "あんないする",
        "meaning_vi": "tôi xin hướng dẫn",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご案内いたす",
        "canonical_reading": "ごあんないいたす",
        "acceptable_variants": ["ご案内いたす", "ごあんないいたす", "ご案内いたします", "ごあんないいたします", "ご案内する", "ご案内します"],
        "triplet_sonkeigo": "ご案内になる",
        "triplet_kenjougo": "ご案内いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ dẫn khách tham quan văn phòng.",
        "example_ja": "社内をご案内いたします。",
        "example_vi": "Tôi xin phép dẫn ngài đi tham quan công ty ạ.",
    },
    {
        "source_word": "説明する",
        "source_reading": "せつめいする",
        "meaning_vi": "tôi xin giải thích",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご説明いたす",
        "canonical_reading": "ごせつめいいたす",
        "acceptable_variants": ["ご説明いたす", "ごせつめいいたす", "ご説明いたします", "ごせつめいいたします", "ご説明する", "ご説明します"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご説明いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi thuyết trình dự án cho đối tác.",
        "example_ja": "企画の詳細をご説明いたします。",
        "example_vi": "Tôi xin phép giải thích chi tiết bản kế hoạch ạ.",
    },
    {
        "source_word": "報告する",
        "source_reading": "ほうこくする",
        "meaning_vi": "tôi xin báo cáo",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご報告いたす",
        "canonical_reading": "ごほうこくいたす",
        "acceptable_variants": ["ご報告いたす", "ごほうこくいたす", "ご報告いたします", "ごほうこくいたします", "ご報告する", "ご報告します"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご報告いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi cấp dưới báo cáo tiến độ cho sếp.",
        "example_ja": "進捗状況をご報告いたします。",
        "example_vi": "Tôi xin phép báo cáo tình hình tiến độ ạ.",
    },
    {
        "source_word": "相談する(khiêm nhường)",
        "source_reading": "そうだんする",
        "meaning_vi": "tôi xin thảo luận / bàn bạc",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご相談いたす",
        "canonical_reading": "ごそうだんいたす",
        "acceptable_variants": ["ご相談いたす", "ごそうだんいたす", "ご相談いたします", "ごそうだんいたします", "ご相談する", "ご相談します"],
        "triplet_sonkeigo": "ご相談になる",
        "triplet_kenjougo": "ご相談いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ xin ý kiến sếp.",
        "example_ja": "予算の件でご相談いたしたいと存じます。",
        "example_vi": "Tôi xin phép muốn trao đổi về vấn đề ngân sách ạ.",
    },
    {
        "source_word": "挨拶する",
        "source_reading": "あいさつする",
        "meaning_vi": "tôi xin chào hỏi",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご挨拶いたす",
        "canonical_reading": "ごあいさついたす",
        "acceptable_variants": ["ご挨拶いたす", "ごあいさついたす", "ご挨拶いたします", "ごあいさついたします", "ご挨拶する", "ご挨拶します"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご挨拶いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Chào hỏi ra mắt đối tác nhân dịp nhậm chức mới.",
        "example_ja": "着任のご挨拶に伺いました。",
        "example_vi": "Tôi đến để chào hỏi ra mắt nhân dịp nhận chức mới ạ.",
    },
    {
        "source_word": "訪問する(khiêm nhường)",
        "source_reading": "ほうもんする",
        "meaning_vi": "tôi xin đến thăm",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご訪問いたす",
        "canonical_reading": "ごほうもんいたす",
        "acceptable_variants": ["ご訪問いたす", "ごほうもんいたす", "ご訪問いたします", "ごほうもんいたします", "ご訪問する", "ご訪問します"],
        "triplet_sonkeigo": "ご訪問になる",
        "triplet_kenjougo": "ご訪問いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ của 訪問する.",
        "example_ja": "明日、14時にご訪問いたします。",
        "example_vi": "Ngày mai lúc 14 giờ tôi xin phép ghé thăm quý công ty ạ.",
    },
    {
        "source_word": "同行する",
        "source_reading": "どうこうする",
        "meaning_vi": "tôi xin đi cùng / tháp tùng",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご同行いたす",
        "canonical_reading": "ごどうこういたす",
        "acceptable_variants": ["ご同行いたす", "ごどうこういたす", "ご同行いたします", "ごどうこういたします", "ご同行する", "ご同行します"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご同行いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ tháp tùng sếp đi gặp khách.",
        "example_ja": "部長の出張にご同行いたします。",
        "example_vi": "Tôi xin phép tháp tùng chuyến công tác của trưởng phòng ạ.",
    },
    {
        "source_word": "紹介する",
        "source_reading": "しょうかいする",
        "meaning_vi": "tôi xin giới thiệu",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご紹介いたす",
        "canonical_reading": "ごしょうかいいたす",
        "acceptable_variants": ["ご紹介いたす", "ごしょうかいいたす", "ご紹介いたします", "ごしょうかいいたします", "ご紹介する", "ご紹介します"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご紹介いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi giới thiệu đồng nghiệp cho khách.",
        "example_ja": "弊社の営業部長をご紹介いたします。",
        "example_vi": "Tôi xin phép giới thiệu trưởng phòng kinh doanh của công ty chúng tôi ạ.",
    },
    {
        "source_word": "提案する",
        "source_reading": "ていあんする",
        "meaning_vi": "tôi xin đề xuất",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご提案いたす",
        "canonical_reading": "ごていあんいたす",
        "acceptable_variants": ["ご提案いたす", "ごていあんいたす", "ご提案いたします", "ごていあんいたします", "ご提案する", "ご提案します"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご提案いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi trình bày giải pháp cho đối tác.",
        "example_ja": "新しいコスト削減案をご提案いたします。",
        "example_vi": "Chúng tôi xin phép đề xuất phương án cắt giảm chi phí mới ạ.",
    },
    {
        "source_word": "協力する(khiêm nhường)",
        "source_reading": "きょうりょくする",
        "meaning_vi": "chúng tôi xin hết lòng hợp tác",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご協力いたす",
        "canonical_reading": "ごきょうりょくいたす",
        "acceptable_variants": ["ご協力いたす", "ごきょうりょくいたす", "ご協力いたします", "ごきょうりょくいたします", "ご協力する", "ご協力します"],
        "triplet_sonkeigo": "ご協力になる",
        "triplet_kenjougo": "ご協力いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Cam kết hợp tác với dự án của đối tác.",
        "example_ja": "全力でご協力いたします。",
        "example_vi": "Chúng tôi xin phép dốc toàn lực hợp tác ạ.",
    },
    {
        "source_word": "返事する",
        "source_reading": "へんじする",
        "meaning_vi": "tôi xin hồi đáp",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご返事いたす",
        "canonical_reading": "ごへんじいたす",
        "acceptable_variants": ["ご返事いたす", "ごへんじいたす", "ご返事いたします", "ごへんじいたします", "ご返答いたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご返事いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ hồi đáp thư từ của đối tác.",
        "example_ja": "明日までにご返事いたします。",
        "example_vi": "Tôi xin phép gửi thư hồi đáp trước ngày mai ạ.",
    },
    {
        "source_word": "提供する",
        "source_reading": "ていきょうする",
        "meaning_vi": "chúng tôi xin cung cấp",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご提供いたす",
        "canonical_reading": "ごていきょういたす",
        "acceptable_variants": ["ご提供いたす", "ごていきょういたす", "ご提供いたします", "ごていきょういたします", "ご提供する", "ご提供します"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご提供いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ khi cung ứng dịch vụ/sản phẩm.",
        "example_ja": "最高品質のサービスをご提供いたします。",
        "example_vi": "Chúng tôi xin cung cấp dịch vụ chất lượng cao nhất ạ.",
    },
    {
        "source_word": "請求する",
        "source_reading": "せいきゅうする",
        "meaning_vi": "chúng tôi xin gửi hóa đơn thanh toán",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご請求いたす",
        "canonical_reading": "ごせいきゅういたす",
        "acceptable_variants": ["ご請求いたす", "ごせいきゅういたす", "ご請求いたします", "ごせいきゅういたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご請求いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Khiêm nhường ngữ gửi yêu cầu thanh toán cuối tháng.",
        "example_ja": "月末にご請求いたします。",
        "example_vi": "Chúng tôi xin phép gửi hóa đơn thanh toán vào cuối tháng ạ.",
    },
    {
        "source_word": "辞退する(khiêm nhường)",
        "source_reading": "じたいする",
        "meaning_vi": "tôi xin phép từ chối khiêm tốn",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご辞退いたす",
        "canonical_reading": "ごじたいいたす",
        "acceptable_variants": ["ご辞退いたす", "ごじたいいたす", "ご辞退いたします", "ごじたいいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご辞退いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Từ chối lời mời một cách trang trọng, tránh thô lỗ.",
        "example_ja": "今回はご辞退いたします。",
        "example_vi": "Lần này tôi xin phép khiêm tốn từ chối ạ.",
    },
    {
        "source_word": "配慮する",
        "source_reading": "はいりょする",
        "meaning_vi": "chúng tôi xin chu đáo quan tâm",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご配慮いたす",
        "canonical_reading": "ごはいりょいたす",
        "acceptable_variants": ["ご配慮いたす", "ごはいりょいたす", "ご配慮いたします", "ごはいりょいたします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご配慮いたす",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Thể hiện sự chu đáo trong phục vụ khách hàng.",
        "example_ja": "安全面に十分ご配慮いたします。",
        "example_vi": "Chúng tôi xin cam kết chu đáo tối đa về mặt an toàn ạ.",
    },
    {
        "source_word": "案内する(suru)",
        "source_reading": "あんないする",
        "meaning_vi": "tôi xin chỉ dẫn (dạng ご...する)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご案内する",
        "canonical_reading": "ごあんないする",
        "acceptable_variants": ["ご案内する", "ごあんないする", "ご案内します", "ごあんないします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご案内する",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Dạng khiêm nhường chuẩn với động từ する.",
        "example_ja": "席へご案内します。",
        "example_vi": "Tôi xin dẫn ngài về chỗ ngồi ạ.",
    },
    {
        "source_word": "連絡する(suru)",
        "source_reading": "れんらくする",
        "meaning_vi": "tôi xin liên hệ (dạng ご...する)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご連絡する",
        "canonical_reading": "ごれんらくする",
        "acceptable_variants": ["ご連絡する", "ごれんらくする", "ご連絡します", "ごれんらくします"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご連絡する",
        "category": "rule_based",
        "jlpt_level": "N4",
        "formula_id": "kenjougo_go_suru",
        "formula": "ご + N(Suru) + する / いたします",
        "subject_hint_vi": "🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Dạng nói quen thuộc trong công việc hàng ngày.",
        "example_ja": "また改めてご連絡します。",
        "example_vi": "Tôi xin phép sẽ liên lạc lại sau ạ.",
    },
]

# 4. kenjougo_moushiageru: 15 entries
KENJOUGO_MOUSHIAGERU_DATA = [
    {
        "source_word": "礼を言う",
        "source_reading": "れいをいう",
        "meaning_vi": "bày tỏ lòng biết ơn chân thành",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お礼申し上げる",
        "canonical_reading": "おれいもうしあげる",
        "acceptable_variants": ["お礼申し上げる", "おれいもうしあげる", "お礼申し上げます", "おれいもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お礼申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Mẫu câu cung kính tuyệt đối (khiêm nhường ngữ II) dùng trong email trang trọng và phát biểu trước đám đông.",
        "example_ja": "心よりお礼申し上げます。",
        "example_vi": "Tôi xin chân thành bày tỏ lòng biết ơn sâu sắc ạ.",
    },
    {
        "source_word": "詫びる",
        "source_reading": "わびる",
        "meaning_vi": "xin lỗi sâu sắc",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お詫び申し上げる",
        "canonical_reading": "おわびもうしあげる",
        "acceptable_variants": ["お詫び申し上げる", "おわびもうしあげる", "お詫び申し上げます", "おわびもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お詫び申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Lời tạ lỗi trang trọng nhất trong văn bản kinh doanh khi phát sinh sự cố.",
        "example_ja": "深くお詫び申し上げます。",
        "example_vi": "Chúng tôi xin cúi đầu nhận lỗi sâu sắc ạ.",
    },
    {
        "source_word": "祝う",
        "source_reading": "いわう",
        "meaning_vi": "gửi lời chúc mừng",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お祝い申し上げる",
        "canonical_reading": "おいわいもうしあげる",
        "acceptable_variants": ["お祝い申し上げる", "おいわいもうしあげる", "お祝い申し上げます", "おいわいもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お祝い申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Lời chúc mừng trang trọng gửi tới đối tác nhân ngày thành lập hoặc thăng chức.",
        "example_ja": "ご栄進を心よりお祝い申し上げます。",
        "example_vi": "Tôi xin gửi lời chúc mừng chân thành nhân dịp ngài được thăng chức ạ.",
    },
    {
        "source_word": "お願いする",
        "source_reading": "おねがいする",
        "meaning_vi": "tha thiết kính cẩn nhờ vả",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お願い申し上げる",
        "canonical_reading": "おねがいもうしあげる",
        "acceptable_variants": ["お願い申し上げる", "おねがいもうしあげる", "お願い申し上げます", "おねがいもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お願い申し上げる",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Câu kết thúc kinh điển của mọi email và thư từ giao dịch kinh doanh tiếng Nhật.",
        "example_ja": "何卒よろしくお願い申し上げます。",
        "example_vi": "Kính mong ngài chiếu cố giúp đỡ cho chúng tôi ạ.",
    },
    {
        "source_word": "報告する(kính cẩn)",
        "source_reading": "ほうこくする",
        "meaning_vi": "kính cẩn đệ trình báo cáo",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご報告申し上げる",
        "canonical_reading": "ごほうこくもうしあげる",
        "acceptable_variants": ["ご報告申し上げる", "ごほうこくもうしあげる", "ご報告申し上げます", "ごほうこくもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご報告申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Kính cẩn báo cáo lên hội đồng quản trị hoặc khách hàng lớn.",
        "example_ja": "結果を速やかにご報告申し上げます。",
        "example_vi": "Tôi xin kính cẩn nhanh chóng báo cáo kết quả ạ.",
    },
    {
        "source_word": "案内する(kính cẩn)",
        "source_reading": "あんないする",
        "meaning_vi": "kính cẩn gửi thông báo hướng dẫn",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご案内申し上げる",
        "canonical_reading": "ごあんないもうしあげる",
        "acceptable_variants": ["ご案内申し上げる", "ごあんないもうしあげる", "ご案内申し上げます", "ごあんないもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご案内申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Gửi thư mời tham dự hội nghị cấp cao.",
        "example_ja": "新製品の発表会をご案内申し上げます。",
        "example_vi": "Chúng tôi xin kính gửi thư mời buổi ra mắt sản phẩm mới ạ.",
    },
    {
        "source_word": "挨拶する(kính cẩn)",
        "source_reading": "あいさつする",
        "meaning_vi": "kính cẩn chào mừng",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご挨拶申し上げる",
        "canonical_reading": "ごあいさつもうしあげる",
        "acceptable_variants": ["ご挨拶申し上げる", "ごあいさつもうしあげる", "ご挨拶申し上げます", "ごあいさつもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご挨拶申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Lời phát biểu mở đầu của đại diện công ty tại buổi lễ.",
        "example_ja": "一言ご挨拶申し上げます。",
        "example_vi": "Tôi xin phép được gửi lời chào mừng đôi câu ạ.",
    },
    {
        "source_word": "感謝する",
        "source_reading": "かんしゃする",
        "meaning_vi": "kính cẩn tri ân / cảm tạ",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "感謝申し上げる",
        "canonical_reading": "かんしゃもうしあげる",
        "acceptable_variants": ["感謝申し上げる", "かんしゃもうしあげる", "感謝申し上げます", "かんしゃもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "感謝申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Bày tỏ lòng tri ân sâu sắc tới đối tác hỗ trợ suốt nhiều năm.",
        "example_ja": "長年のご厚情に深く感謝申し上げます。",
        "example_vi": "Chúng tôi xin thành kính tri ân tấm thịnh tình quý báu suốt nhiều năm qua ạ.",
    },
    {
        "source_word": "お見舞いする",
        "source_reading": "おみまいする",
        "meaning_vi": "thăm hỏi ân cần (khi có thiên tai/đau ốm)",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お見舞い申し上げる",
        "canonical_reading": "おみまいもうしあげる",
        "acceptable_variants": ["お見舞い申し上げる", "おみまいもうしあげる", "お見舞い申し上げます", "おみまいもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お見舞い申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Thư từ thăm hỏi đối tác khi gặp thiên tai lũ lụt.",
        "example_ja": "被災された皆様に心よりお見舞い申し上げます。",
        "example_vi": "Chúng tôi xin gửi lời thăm hỏi sâu sắc tới toàn thể bà con bị ảnh hưởng bởi thiên tai ạ.",
    },
    {
        "source_word": "連絡する(kính cẩn)",
        "source_reading": "れんらくする",
        "meaning_vi": "kính cẩn báo tin",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご連絡申し上げる",
        "canonical_reading": "ごれんらくもうしあげる",
        "acceptable_variants": ["ご連絡申し上げる", "ごれんらくもうしあげる", "ご連絡申し上げます", "ごれんらくもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご連絡申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Kính cẩn gửi liên hệ khẩn cấp tới đối tác.",
        "example_ja": "取り急ぎご連絡申し上げます。",
        "example_vi": "Tôi xin phép được nhanh chóng liên lạc thông báo trước ạ.",
    },
    {
        "source_word": "説明する(kính cẩn)",
        "source_reading": "せつめいする",
        "meaning_vi": "kính cẩn trình bày giải thích",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご説明申し上げる",
        "canonical_reading": "ごせつめいもうしあげる",
        "acceptable_variants": ["ご説明申し上げる", "ごせつめいもうしあげる", "ご説明申し上げます", "ごせつめいもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご説明申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Trình bày giải thích trong phiên họp đại hội cổ đông.",
        "example_ja": "事業計画をご説明申し上げます。",
        "example_vi": "Tôi xin phép kính cẩn trình bày kế hoạch kinh doanh ạ.",
    },
    {
        "source_word": "提案する(kính cẩn)",
        "source_reading": "ていあんする",
        "meaning_vi": "kính cẩn đề xuất phương án",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご提案申し上げる",
        "canonical_reading": "ごていあんもうしあげる",
        "acceptable_variants": ["ご提案申し上げる", "ごていあんもうしあげる", "ご提案申し上げます", "ごていあんもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご提案申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Đệ trình phương án hợp tác chiến lược lên đối tác.",
        "example_ja": "新たな提携案をご提案申し上げます。",
        "example_vi": "Chúng tôi xin kính cẩn đề xuất phương án hợp tác mới ạ.",
    },
    {
        "source_word": "返答する",
        "source_reading": "へんとうする",
        "meaning_vi": "kính cẩn hồi âm giải đáp",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご返答申し上げる",
        "canonical_reading": "ごへんとうもうしあげる",
        "acceptable_variants": ["ご返答申し上げる", "ごへんとうもうしあげる", "ご返答申し上げます", "ごへんとうもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご返答申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Hồi âm trang trọng đối với các chất vấn từ khách hàng.",
        "example_ja": "ご質問に対し、謹んでご返答申し上げます。",
        "example_vi": "Đối với câu hỏi của ngài, chúng tôi xin kính cẩn hồi đáp ạ.",
    },
    {
        "source_word": "祈る",
        "source_reading": "いのる",
        "meaning_vi": "cầu chúc thành công vạn sự",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "お祈り申し上げる",
        "canonical_reading": "おいのりもうしあげる",
        "acceptable_variants": ["お祈り申し上げる", "おいのりもうしあげる", "お祈り申し上げます", "おいのりもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "お祈り申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Lời chúc cầu phúc ở cuối thư kinh doanh gửi đối tác.",
        "example_ja": "貴社のますますのご発展をお祈り申し上げます。",
        "example_vi": "Kính chúc quý công ty ngày càng phát triển thịnh vượng ạ.",
    },
    {
        "source_word": "忠告する",
        "source_reading": "ちゅうこくする",
        "meaning_vi": "kính cẩn khuyên can lưu ý",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "ご忠告申し上げる",
        "canonical_reading": "ごちゅうこくもうしあげる",
        "acceptable_variants": ["ご忠告申し上げる", "ごちゅうこくもうしあげる", "ご忠告申し上げます", "ごちゅうこくもうしあげます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "ご忠告申し上げる",
        "category": "rule_based",
        "jlpt_level": "N2",
        "formula_id": "kenjougo_moushiageru",
        "formula": "お / ご + V(stem) + 申し上げる / 申し上げます",
        "subject_hint_vi": "🙇 Hành động cung kính của: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Kính cẩn đưa ra lời khuyên nhủ thiện chí với đối tác.",
        "example_ja": "差し出がましいようですが、ご忠告申し上げます。",
        "example_vi": "Dù mạo muội nhưng tôi xin phép kính cẩn đưa ra lời khuyên ạ.",
    },
]

# 5. kenjougo_permissive: 15 entries
KENJOUGO_PERMISSIVE_DATA = [
    {
        "source_word": "休む",
        "source_reading": "やすむ",
        "meaning_vi": "xin phép được nghỉ phép",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "休ませていただく",
        "canonical_reading": "やすませていただく",
        "acceptable_variants": ["休ませていただく", "やすませていただく", "休ませていただきます", "やすませていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "休ませていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Công thức xin phép cho bản thân làm việc gì: Động từ thể sai khiến (使役形) + ていただく / ていただきます.",
        "example_ja": "明日、有給休暇を休ませていただきます。",
        "example_vi": "Ngày mai tôi xin phép được nghỉ phép có lương ạ.",
    },
    {
        "source_word": "説明する(xin phép)",
        "source_reading": "せつめいする",
        "meaning_vi": "xin phép được giải thích",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "説明させていただく",
        "canonical_reading": "せつめいさせていただく",
        "acceptable_variants": ["説明させていただく", "せつめいさせていただく", "説明させていただきます", "せつめいさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "説明させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Xin phép bắt đầu thuyết trình trong buổi họp.",
        "example_ja": "本日の議題について説明させていただきます。",
        "example_vi": "Tôi xin phép được giải thích về chủ đề cuộc họp hôm nay ạ.",
    },
    {
        "source_word": "参加する(xin phép)",
        "source_reading": "さんかする",
        "meaning_vi": "xin phép được tham gia",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "参加させていただく",
        "canonical_reading": "さんかさせていただく",
        "acceptable_variants": ["参加させていただく", "さんかさせていただく", "参加させていただきます", "さんかさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "参加させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Xin phép góp mặt vào sự kiện hoặc dự án chung.",
        "example_ja": "プロジェクトに参加させていただきます。",
        "example_vi": "Tôi xin phép được tham gia vào dự án ạ.",
    },
    {
        "source_word": "担当する",
        "source_reading": "たんとうする",
        "meaning_vi": "xin phép được phụ trách",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "担当させていただく",
        "canonical_reading": "たんとうさせていただく",
        "acceptable_variants": ["担当させていただく", "たんとうさせていただく", "担当させていただきます", "たんとうさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "担当させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Ra mắt với tư cách người phụ trách dự án cho khách.",
        "example_ja": "本件を担当させていただきます、佐藤です。",
        "example_vi": "Tôi là Satou, xin phép được phụ trách vụ việc này ạ.",
    },
    {
        "source_word": "辞退する",
        "source_reading": "じたいする",
        "meaning_vi": "xin phép được rút lui / khước từ",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "辞退させていただく",
        "canonical_reading": "じたいさせていただく",
        "acceptable_variants": ["辞退させていただく", "じたいさせていただく", "辞退させていただきます", "じたいさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "辞退させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Xin phép từ chối đề bạt hoặc cơ hội một cách nhã nhặn.",
        "example_ja": "身に余る光栄ですが、辞退させていただきます。",
        "example_vi": "Thật quá vinh dự cho tôi, nhưng xin phép được từ chối ạ.",
    },
    {
        "source_word": "確認する(xin phép)",
        "source_reading": "かくにんする",
        "meaning_vi": "xin phép được kiểm tra lại",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "確認させていただく",
        "canonical_reading": "かくにんさせていただく",
        "acceptable_variants": ["確認させていただく", "かくにんさせていただく", "確認させていただきます", "かくにんさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "確認させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Xin phép khách hàng đối chiếu lại thông tin.",
        "example_ja": "もう一度お名前を確認させていただきます。",
        "example_vi": "Tôi xin phép được xác nhận lại quý danh một lần nữa ạ.",
    },
    {
        "source_word": "自己紹介する",
        "source_reading": "じこしょうかいする",
        "meaning_vi": "xin phép được tự giới thiệu",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "自己紹介させていただく",
        "canonical_reading": "じこしょうかいさせていただく",
        "acceptable_variants": ["自己紹介させていただく", "じこしょうかいさせていただく", "自己紹介させていただきます", "じこしょうかいさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "自己紹介させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Mở đầu màn phỏng vấn hoặc gặp mặt đối tác.",
        "example_ja": "簡単に自己紹介させていただきます。",
        "example_vi": "Tôi xin phép được tự giới thiệu ngắn gọn đôi chút ạ.",
    },
    {
        "source_word": "挨拶する(xin phép)",
        "source_reading": "あいさつする",
        "meaning_vi": "xin phép được gửi lời chào",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "挨拶させていただく",
        "canonical_reading": "あいさつさせていただく",
        "acceptable_variants": ["挨拶させていただく", "あいさつさせていただく", "挨拶させていただきます", "あいさつさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "挨拶させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Xin phép được phát biểu đôi lời chào mừng.",
        "example_ja": "新任の挨拶をさせていただきます。",
        "example_vi": "Tôi xin phép được phát biểu lời chào nhận nhiệm vụ mới ạ.",
    },
    {
        "source_word": "連絡する(xin phép)",
        "source_reading": "れんらくする",
        "meaning_vi": "xin phép được liên lạc lại sau",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "連絡させていただく",
        "canonical_reading": "れんらくさせていただく",
        "acceptable_variants": ["連絡させていただく", "れんらくさせていただく", "連絡させていただきます", "れんらくさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "連絡させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Xin phép khách để chủ động liên hệ lại sau khi kiểm tra thông tin.",
        "example_ja": "後日改めて連絡させていただきます。",
        "example_vi": "Vài hôm nữa tôi xin phép được liên lạc lại sau ạ.",
    },
    {
        "source_word": "質問する",
        "source_reading": "しつもんする",
        "meaning_vi": "xin phép được đặt câu hỏi",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "質問させていただく",
        "canonical_reading": "しつもんさせていただく",
        "acceptable_variants": ["質問させていただく", "しつもんさせていただく", "質問させていただきます", "しつもんさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "質問させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Xin phép đặt câu hỏi trong hội thảo.",
        "example_ja": "一つ質問させていただきます。",
        "example_vi": "Tôi xin phép được đặt một câu hỏi ạ.",
    },
    {
        "source_word": "拝見する(xin phép)",
        "source_reading": "はいけんする",
        "meaning_vi": "xin phép được xem qua tài liệu",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "拝見させていただく",
        "canonical_reading": "はいけんさせていただく",
        "acceptable_variants": ["拝見させていただく", "はいけんさせていただく", "拝見させていただきます", "はいけんさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "拝見させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Xin phép đối tác được mở tài liệu ra xem.",
        "example_ja": "資料を拝見させていただきます。",
        "example_vi": "Tôi xin phép được xem qua bản tài liệu ạ.",
    },
    {
        "source_word": "報告する(xin phép)",
        "source_reading": "ほうこくする",
        "meaning_vi": "xin phép được báo cáo",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "報告させていただく",
        "canonical_reading": "ほうこくさせていただく",
        "acceptable_variants": ["報告させていただく", "ほうこくさせていただく", "報告させていただきます", "ほうこくさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "報告させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Xin phép cấp trên bắt đầu phần báo cáo kết quả.",
        "example_ja": "先月の売上を報告させていただきます。",
        "example_vi": "Tôi xin phép được báo cáo doanh thu tháng trước ạ.",
    },
    {
        "source_word": "検討する(xin phép)",
        "source_reading": "けんとうする",
        "meaning_vi": "xin phép đem về nội bộ cân nhắc",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "検討させていただく",
        "canonical_reading": "けんとうさせていただく",
        "acceptable_variants": ["検討させていただく", "けんとうさせていただく", "検討させていただきます", "けんとうさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "検討させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Hứa với đối tác sẽ đem đề xuất về nội bộ bàn bạc kĩ lưỡng.",
        "example_ja": "社内で一度検討させていただきます。",
        "example_vi": "Tôi xin phép đưa về công ty thảo luận xem xét lại ạ.",
    },
    {
        "source_word": "電話する(xin phép)",
        "source_reading": "でんわする",
        "meaning_vi": "xin phép gọi điện lại",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "電話させていただく",
        "canonical_reading": "でんわさせていただく",
        "acceptable_variants": ["電話させていただく", "でんわさせていただく", "電話させていただきます", "でんわさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "電話させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Xin phép gọi điện trao đổi chi tiết.",
        "example_ja": "後ほどお電話させていただきます。",
        "example_vi": "Lát nữa tôi xin phép được gọi điện thoại lại ạ.",
    },
    {
        "source_word": "退出する",
        "source_reading": "たいしゅつする",
        "meaning_vi": "xin phép được rời khỏi phòng",
        "target_type": "kenjougo",
        "target_label_vi": "Khiêm nhường ngữ (謙譲語)",
        "canonical": "退出させていただく",
        "canonical_reading": "たいしゅつさせていただく",
        "acceptable_variants": ["退出させていただく", "たいしゅつさせていただく", "退出させていただきます", "たいしゅつさせていただきます"],
        "triplet_sonkeigo": None,
        "triplet_kenjougo": "退出させていただく",
        "category": "rule_based",
        "jlpt_level": "N3",
        "formula_id": "kenjougo_permissive",
        "formula": "〜（さ）せていただく / いただきます",
        "subject_hint_vi": "🙇 Xin phép hành động: BẢN THÂN / CÔNG TY MÌNH",
        "explanation_vi": "Xin phép rời phòng phỏng vấn hoặc cuộc họp trước.",
        "example_ja": "それではこれで退出させていただきます。",
        "example_vi": "Nếu vậy xin phép cho tôi được rời phòng tại đây ạ.",
    },
]
