import type { JlptLevel, MissionTaxonomyResponse } from '../../../types/api'

export const JLPT_OPTIONS: Array<{ value: JlptLevel; label: string }> = [
  { value: 'N5', label: 'N5 (Sơ cấp 1)' },
  { value: 'N4', label: 'N4 (Sơ cấp 2)' },
  { value: 'N3', label: 'N3 (Trung cấp)' },
  { value: 'N2', label: 'N2 (Cao cấp)' },
  { value: 'N1', label: 'N1 (Bản xứ/Chuyên sâu)' },
]

export const DEFAULT_TAXONOMY: MissionTaxonomyResponse = {
  categories: [
    {
      id: 'work',
      label_vi: 'Công sở & Doanh nghiệp',
      label_ja: '仕事・ビジネス',
      icon: '💼',
      description: 'Giao tiếp trong công việc, báo cáo, email đối tác',
      action_count: 8,
    },
    {
      id: 'daily_life',
      label_vi: 'Đời sống Thường ngày',
      label_ja: '日常生活',
      icon: '🏠',
      description: 'Kế hoạch, hẹn hò, xin giúp đỡ, giải thích sự cố',
      action_count: 6,
    },
    {
      id: 'services',
      label_vi: 'Dịch vụ & Giao dịch',
      label_ja: 'サービス・店舗',
      icon: '🏪',
      description: 'Đặt chỗ, khiếu nại, đổi trả, hỗ trợ khách hàng',
      action_count: 5,
    },
    {
      id: 'social',
      label_vi: 'Xã hội & Bạn bè',
      label_ja: 'ソーシャル・友人',
      icon: '👥',
      description: 'Mời mọc, cảm ơn, cập nhật tình hình',
      action_count: 4,
    },
  ],
  actions: [
    // Work
    {
      action_type: 'progress_update',
      category: 'work',
      label_vi: 'Báo cáo tiến độ',
      label_ja: '進捗報告',
      default_register: 'business',
      recommended_jlpt: ['N3', 'N2'],
      default_medium: 'email',
      typical_role_vi: 'Kỹ sư',
      typical_recipient_vi: 'Trưởng phòng',
      communicative_purpose_vi: 'Báo cáo tiến độ',
    },
    {
      action_type: 'asking_colleague',
      category: 'work',
      label_vi: 'Hỏi/Nhờ đồng nghiệp',
      label_ja: '同僚への依頼',
      default_register: 'polite',
      recommended_jlpt: ['N4', 'N3'],
      default_medium: 'chat',
      typical_role_vi: 'Nhân viên',
      typical_recipient_vi: 'Đồng nghiệp',
      communicative_purpose_vi: 'Nhờ hỗ trợ',
    },
    {
      action_type: 'reporting_problem',
      category: 'work',
      label_vi: 'Báo cáo sự cố',
      label_ja: 'トラブル報告',
      default_register: 'business',
      recommended_jlpt: ['N3', 'N2'],
      default_medium: 'email',
      typical_role_vi: 'Nhân viên',
      typical_recipient_vi: 'Cấp trên',
      communicative_purpose_vi: 'Báo cáo sự cố',
    },
    {
      action_type: 'scheduling',
      category: 'work',
      label_vi: 'Sắp xếp lịch họp',
      label_ja: '日程調整',
      default_register: 'business',
      recommended_jlpt: ['N3', 'N2'],
      default_medium: 'email',
      typical_role_vi: 'Nhân viên',
      typical_recipient_vi: 'Khách hàng',
      communicative_purpose_vi: 'Hẹn lịch họp',
    },
    {
      action_type: 'absence_notice',
      category: 'work',
      label_vi: 'Báo nghỉ phép/ốm',
      label_ja: '勤怠・欠勤連絡',
      default_register: 'business',
      recommended_jlpt: ['N4', 'N3'],
      default_medium: 'email',
      typical_role_vi: 'Nhân viên',
      typical_recipient_vi: 'Quản lý',
      communicative_purpose_vi: 'Báo nghỉ',
    },
    {
      action_type: 'deadline_delay',
      category: 'work',
      label_vi: 'Xin dời deadline',
      label_ja: '納期延長の相談',
      default_register: 'business',
      recommended_jlpt: ['N3', 'N2'],
      default_medium: 'email',
      typical_role_vi: 'Kỹ sư',
      typical_recipient_vi: 'Trưởng phòng',
      communicative_purpose_vi: 'Xin hoãn hạn',
    },
    {
      action_type: 'internal_message',
      category: 'work',
      label_vi: 'Tin nhắn nội bộ',
      label_ja: '社内チャット',
      default_register: 'polite',
      recommended_jlpt: ['N4', 'N3'],
      default_medium: 'chat',
      typical_role_vi: 'Thành viên',
      typical_recipient_vi: 'Team',
      communicative_purpose_vi: 'Trao đổi công việc',
    },
    {
      action_type: 'business_email',
      category: 'work',
      label_vi: 'Email thương mại đối tác',
      label_ja: '取引先ビジネスメール',
      default_register: 'business',
      recommended_jlpt: ['N2', 'N1'],
      default_medium: 'email',
      typical_role_vi: 'Phụ trách',
      typical_recipient_vi: 'Đối tác',
      communicative_purpose_vi: 'Trao đổi hợp tác',
    },
    // Daily Life
    {
      action_type: 'making_plans',
      category: 'daily_life',
      label_vi: 'Lên kế hoạch & Hẹn gặp',
      label_ja: '予定を立てる・約束',
      default_register: 'casual',
      recommended_jlpt: ['N5', 'N4', 'N3'],
      default_medium: 'chat',
      typical_role_vi: 'Bạn bè',
      typical_recipient_vi: 'Bạn cùng lớp',
      communicative_purpose_vi: 'Hẹn gặp và lên lịch hoạt động',
    },
    {
      action_type: 'cancelling_plans',
      category: 'daily_life',
      label_vi: 'Hủy hẹn & Xin dời lịch',
      label_ja: '約束のキャンセル・日程変更',
      default_register: 'polite',
      recommended_jlpt: ['N5', 'N4', 'N3'],
      default_medium: 'chat',
      typical_role_vi: 'Người tham gia',
      typical_recipient_vi: 'Bạn bè',
      communicative_purpose_vi: 'Báo hủy hẹn và đề xuất hẹn lại',
    },
    {
      action_type: 'asking_for_help',
      category: 'daily_life',
      label_vi: 'Nhờ vả & Xin giúp đỡ',
      label_ja: '助けを求める・依頼',
      default_register: 'polite',
      recommended_jlpt: ['N5', 'N4', 'N3'],
      default_medium: 'chat',
      typical_role_vi: 'Cư dân',
      typical_recipient_vi: 'Hàng xóm / Bạn bè',
      communicative_purpose_vi: 'Trình bày khó khăn và nhờ hỗ trợ',
    },
    {
      action_type: 'explaining_a_problem',
      category: 'daily_life',
      label_vi: 'Trình bày sự cố & Vấn đề',
      label_ja: '問題の説明・相談',
      default_register: 'polite',
      recommended_jlpt: ['N4', 'N3', 'N2'],
      default_medium: 'chat',
      typical_role_vi: 'Người thuê nhà',
      typical_recipient_vi: 'Chủ nhà',
      communicative_purpose_vi: 'Mô tả cụ thể sự cố nơi ở',
    },
    {
      action_type: 'apologizing',
      category: 'daily_life',
      label_vi: 'Xin lỗi & Tạ lỗi',
      label_ja: '謝罪・お詫び',
      default_register: 'polite',
      recommended_jlpt: ['N5', 'N4', 'N3'],
      default_medium: 'chat',
      typical_role_vi: 'Người gây sự cố',
      typical_recipient_vi: 'Người bị ảnh hưởng',
      communicative_purpose_vi: 'Bày tỏ sự hối tiếc và hướng khắc phục',
    },
    {
      action_type: 'making_a_request',
      category: 'daily_life',
      label_vi: 'Đưa ra yêu cầu lịch sự',
      label_ja: '丁寧な依頼',
      default_register: 'polite',
      recommended_jlpt: ['N5', 'N4', 'N3'],
      default_medium: 'chat',
      typical_role_vi: 'Người yêu cầu',
      typical_recipient_vi: 'Bạn cùng phòng / Quản lý',
      communicative_purpose_vi: 'Đưa ra yêu cầu nhã nhặn',
    },
    // Services
    {
      action_type: 'complaint',
      category: 'services',
      label_vi: 'Khiếu nại dịch vụ',
      label_ja: 'クレーム・意見の伝達',
      default_register: 'business',
      recommended_jlpt: ['N3', 'N2', 'N1'],
      default_medium: 'email',
      typical_role_vi: 'Khách hàng',
      typical_recipient_vi: 'Chăm sóc khách hàng',
      communicative_purpose_vi: 'Trình bày khiếm khuyết dịch vụ một cách lịch sự',
    },
    {
      action_type: 'inquiry',
      category: 'services',
      label_vi: 'Hỏi thông tin dịch vụ',
      label_ja: '問い合わせ',
      default_register: 'polite',
      recommended_jlpt: ['N4', 'N3', 'N2'],
      default_medium: 'email',
      typical_role_vi: 'Khách hàng',
      typical_recipient_vi: 'Đại diện cửa hàng',
      communicative_purpose_vi: 'Hỏi chi tiết sản phẩm / dịch vụ',
    },
    {
      action_type: 'reservation',
      category: 'services',
      label_vi: 'Đặt chỗ & Đặt lịch',
      label_ja: '予約・日程確保',
      default_register: 'polite',
      recommended_jlpt: ['N5', 'N4', 'N3'],
      default_medium: 'email',
      typical_role_vi: 'Khách hàng',
      typical_recipient_vi: 'Nhà hàng / Khách sạn',
      communicative_purpose_vi: 'Đặt bàn hoặc phòng',
    },
    {
      action_type: 'cancellation_refund',
      category: 'services',
      label_vi: 'Hủy & Hoàn tiền',
      label_ja: 'キャンセル・返金依頼',
      default_register: 'business',
      recommended_jlpt: ['N3', 'N2'],
      default_medium: 'email',
      typical_role_vi: 'Người mua',
      typical_recipient_vi: 'Hỗ trợ khách hàng',
      communicative_purpose_vi: 'Yêu cầu hoàn hủy đúng chính sách',
    },
    {
      action_type: 'feedback',
      category: 'services',
      label_vi: 'Đánh giá & Góp ý dịch vụ',
      label_ja: 'フィードバック・感想',
      default_register: 'polite',
      recommended_jlpt: ['N4', 'N3'],
      default_medium: 'email',
      typical_role_vi: 'Khách trải nghiệm',
      typical_recipient_vi: 'Đơn vị dịch vụ',
      communicative_purpose_vi: 'Góp ý nâng cao chất lượng',
    },
    // Social
    {
      action_type: 'invitation',
      category: 'social',
      label_vi: 'Thư mời sự kiện',
      label_ja: '招待・案内',
      default_register: 'polite',
      recommended_jlpt: ['N4', 'N3', 'N2'],
      default_medium: 'chat',
      typical_role_vi: 'Chủ tiệc / Bạn bè',
      typical_recipient_vi: 'Bạn bè / Người quen',
      communicative_purpose_vi: 'Mời tham gia buổi họp mặt',
    },
    {
      action_type: 'thank_you',
      category: 'social',
      label_vi: 'Lời cảm ơn',
      label_ja: '感謝・お礼',
      default_register: 'polite',
      recommended_jlpt: ['N5', 'N4', 'N3'],
      default_medium: 'chat',
      typical_role_vi: 'Người nhận ơn',
      typical_recipient_vi: 'Người giúp đỡ',
      communicative_purpose_vi: 'Bày tỏ lòng biết ơn sâu sắc',
    },
    {
      action_type: 'congratulations',
      category: 'social',
      label_vi: 'Chúc mừng sự kiện',
      label_ja: 'お祝い・祝福',
      default_register: 'polite',
      recommended_jlpt: ['N4', 'N3'],
      default_medium: 'chat',
      typical_role_vi: 'Bạn bè',
      typical_recipient_vi: 'Người có tin vui',
      communicative_purpose_vi: 'Chúc mừng thành tựu mới',
    },
    {
      action_type: 'staying_in_touch',
      category: 'social',
      label_vi: 'Hỏi thăm & Cập nhật tình hình',
      label_ja: '近況報告・安否確認',
      default_register: 'casual',
      recommended_jlpt: ['N5', 'N4', 'N3'],
      default_medium: 'chat',
      typical_role_vi: 'Bạn bè lâu năm',
      typical_recipient_vi: 'Bạn thân',
      communicative_purpose_vi: 'Hỏi thăm sức khỏe và đời sống',
    },
  ],
  prompt_modes: [
    {
      mode: 'vietnamese_scenario',
      mode_code: 'A',
      label_vi: 'Chế độ A: Kịch bản Song ngữ (VI + JA)',
      description_vi: 'Đọc tình huống bằng tiếng Việt, kích hoạt từ vựng và tư duy chuyển tải sang tiếng Nhật.',
      recommended_level: 'N5 / N4 (Nhập môn)',
    },
    {
      mode: 'japanese_scenario',
      mode_code: 'B',
      label_vi: 'Chế độ B: Kịch bản Tiếng Nhật 100%',
      description_vi: 'Toàn bộ bối cảnh và yêu cầu viết bằng tiếng Nhật tự nhiên, rèn luyện đọc hiểu và phản xạ bản xứ.',
      recommended_level: 'N3 (Trung cấp)',
    },
    {
      mode: 'contextual_simulation',
      mode_code: 'C',
      label_vi: 'Chế độ C: Hộp thư In-Basket / Tin nhắn phản hồi',
      description_vi: 'Đọc email/tin nhắn đến từ người Nhật và soạn thư hồi đáp trực tiếp không qua dịch thuật.',
      recommended_level: 'N2 / N1 (Thực chiến)',
    },
  ],
  evaluation_dimensions: [],
}
