"""Keigo Vocabulary Pool — Complete honorific & humble word pairs, business words, and regular rules.

Organized into 5 world-class practical categories:
- sonkeigo_irregular: Tôn kính ngữ bất quy tắc (25 core verbs)
- kenjougo_irregular: Khiêm nhường ngữ & đinh trọng ngữ bất quy tắc (25 core verbs)
- rule_based: Kính ngữ theo quy tắc (お〜になる / になります, Thể bị động 〜れる / 〜られます, お〜する/いたします, ご〜する/いたします)
- noun_prefixes: Tiền tố tôn kính & mỹ hóa Danh từ / Tính từ (お vs ご và các ngoại lệ)
- business_words: Đại từ nhân xưng, xưng hô Uchi/Soto, thời gian, và phó từ công sở

Usage:
    from app.domains.keigo.keigo_vocab_pool import (
        ALL_KEIGO_WORDS, KeigoWordEntry, get_all_keigo_vocab,
        get_sonkeigo_pool, get_kenjougo_pool, get_rule_based_pool,
        get_prefix_vocab_pool, get_business_vocab_pool, get_keigo_by_category, search_keigo
    )
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class KeigoWordEntry:
    source_word: str  # Plain word (e.g., 食べる, 行く, 今日, 会社, 名前, 家族)
    source_reading: str  # e.g., たべる
    meaning_vi: str  # e.g., ăn, đi, hôm nay, tên, gia đình
    target_type: str  # 'sonkeigo' | 'kenjougo' | 'business' | 'rule_based' | 'prefix'
    target_label_vi: str  # 'Tôn kính ngữ (尊敬語)' | 'Khiêm nhường ngữ (謙譲語)' | 'Từ thương mại (ビジネス語)' | 'Tiền tố mỹ từ (お・ご)'
    canonical: str  # Primary answer (e.g., 召し上がる, 参る, 本日, お名前, ご家族)
    canonical_reading: str  # e.g., めしあがる
    acceptable_variants: list[str] = field(default_factory=list)
    triplet_sonkeigo: str | None = None
    triplet_kenjougo: str | None = None
    category: str = "sonkeigo_irregular"  # 'sonkeigo_irregular' | 'kenjougo_irregular' | 'rule_based' | 'noun_prefixes' | 'business_words'
    jlpt_level: str = "N3"
    explanation_vi: str = ""
    subject_hint_vi: str = ""  # '👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG' | '🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH'
    formula: str = ""  # 'Bất quy tắc (Đặc biệt)' | 'お + V(stem) + になる / になります' | 'Thể bị động: 〜れる / 〜られます'
    example_ja: str = ""
    example_vi: str = ""


# ==============================================================================
# 1. CORE SONKEIGO IRREGULAR (Tôn kính ngữ bất quy tắc — 25 động từ kinh điển)
# ==============================================================================
SONKEIGO_IRREGULAR: list[KeigoWordEntry] = [
    KeigoWordEntry(
        source_word="する",
        source_reading="する",
        meaning_vi="làm",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="なさる",
        canonical_reading="なさる",
        acceptable_variants=["なさる", "なさいます", "なさって", "なされる", "なされます"],
        triplet_sonkeigo="なさる",
        triplet_kenjougo="いたす",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Hành động của đối phương/khách hàng → なさる (hoặc bị động: される)",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Bất quy tắc (Đặc biệt) / Thể bị động: される",
        example_ja="「本日の午後はどのようなご予定をなさいますか？」",
        example_vi="Chiều nay quý khách đã có kế hoạch như thế nào rồi ạ?",
    ),
    KeigoWordEntry(
        source_word="行く",
        source_reading="いく",
        meaning_vi="đi",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="いらっしゃる",
        canonical_reading="いらっしゃる",
        acceptable_variants=["いらっしゃる", "いらっしゃいます", "おいでになる", "おいでになります", "行かれる", "行かれます"],
        triplet_sonkeigo="いらっしゃる / おいでになる",
        triplet_kenjougo="参る / 伺う",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Đối phương đi đâu → いらっしゃる / おいでになる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「社長は明日、大阪の支社へいらっしゃいます。」",
        example_vi="Ngày mai Giám đốc sẽ đến chi nhánh Osaka ạ.",
    ),
    KeigoWordEntry(
        source_word="来る",
        source_reading="くる",
        meaning_vi="đến",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="いらっしゃる",
        canonical_reading="いらっしゃる",
        acceptable_variants=["いらっしゃる", "いらっしゃいます", "お越しになる", "お越しになります", "お見えになる", "お見えになります", "来られる", "来られます", "こられる", "こられます"],
        triplet_sonkeigo="いらっしゃる / お越しになる / お見えになる",
        triplet_kenjougo="参る",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Khách đến công ty → いらっしゃる / お越しになる / お見えになる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Bất quy tắc (Đặc biệt) / Thể bị động: 来られる",
        example_ja="「本日は遠いところをお越しいただきありがとうございます。」",
        example_vi="Cảm ơn quý khách hôm nay đã không quản đường xa đến đây ạ.",
    ),
    KeigoWordEntry(
        source_word="居る",
        source_reading="いる",
        meaning_vi="ở / có mặt",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="いらっしゃる",
        canonical_reading="いらっしゃる",
        acceptable_variants=["いらっしゃる", "いらっしゃいます", "おいでになる", "おいでになります"],
        triplet_sonkeigo="いらっしゃる / おいでになる",
        triplet_kenjougo="おる",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Sếp có ở văn phòng không → いらっしゃいますか",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「田中部長はただいまお席にいらっしゃいますか？」",
        example_vi="Xin hỏi Trưởng phòng Tanaka hiện có đang ở bàn làm việc không ạ?",
    ),
    KeigoWordEntry(
        source_word="言う",
        source_reading="いう",
        meaning_vi="nói",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="おっしゃる",
        canonical_reading="おっしゃる",
        acceptable_variants=["おっしゃる", "おっしゃいます", "おっしゃって", "言われる", "言われます"],
        triplet_sonkeigo="おっしゃる",
        triplet_kenjougo="申す / 申し上げる",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Khách hàng nói → おっしゃる (hoặc 言われる)",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Bất quy tắc (Đặc biệt) / Thể bị động: 言われる",
        example_ja="「お客様がおっしゃった通りに手配いたしました。」",
        example_vi="Tôi đã thu xếp đúng như lời quý khách đã dặn bảo ạ.",
    ),
    KeigoWordEntry(
        source_word="食べる",
        source_reading="たべる",
        meaning_vi="ăn",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="召し上がる",
        canonical_reading="めしあがる",
        acceptable_variants=["召し上がる", "召し上がります", "めしあがる", "めしあがります", "食べられる", "食べられます", "お召し上がりになる"],
        triplet_sonkeigo="召し上がる",
        triplet_kenjougo="いただく",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Mời khách dùng bữa → 召し上がる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「どうぞ温かいうちにお召し上がりください。」",
        example_vi="Món ăn còn đang nóng, xin kính mời quý khách dùng bữa ạ.",
    ),
    KeigoWordEntry(
        source_word="飲む",
        source_reading="のむ",
        meaning_vi="uống",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="召し上がる",
        canonical_reading="めしあがる",
        acceptable_variants=["召し上がる", "召し上がります", "めしあがる", "めしあがります", "飲まれる", "飲まれます"],
        triplet_sonkeigo="召し上がる",
        triplet_kenjougo="いただく",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Mời sếp uống trà → 召し上がる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「お飲み物は何を召し上がりますか？」",
        example_vi="Quý khách muốn dùng đồ uống gì ạ?",
    ),
    KeigoWordEntry(
        source_word="見る",
        source_reading="みる",
        meaning_vi="xem / nhìn",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="ご覧になる",
        canonical_reading="ごらんになる",
        acceptable_variants=["ご覧になる", "ご覧になります", "ごらんになる", "ごらんになります", "見られる", "見られます"],
        triplet_sonkeigo="ご覧になる",
        triplet_kenjougo="拝見する",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Kính mời sếp xem tài liệu → ご覧になる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Bất quy tắc (Đặc biệt) / Thể bị động: 見られる",
        example_ja="「こちらの資料をぜひご覧になってください。」",
        example_vi="Kính mời quý vị xem qua tập tài liệu đính kèm này ạ.",
    ),
    KeigoWordEntry(
        source_word="知る",
        source_reading="しる",
        meaning_vi="biết",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="ご存知だ",
        canonical_reading="ごぞんじだ",
        acceptable_variants=["ご存知だ", "ご存知です", "ご存じだ", "ご存じです", "ご存知ですか", "ご存じですか", "ご存知でしょうか", "知られる", "知られます"],
        triplet_sonkeigo="ご存知だ / ご存知です",
        triplet_kenjougo="存じる / 存じ上げる",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Quý khách có biết chuyện đó không → ご存知ですか",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「こちらの新しいサービスをご存知でしょうか？」",
        example_vi="Quý khách đã biết đến dịch vụ mới này của bên em chưa ạ?",
    ),
    KeigoWordEntry(
        source_word="くれる",
        source_reading="くれる",
        meaning_vi="cho tôi / tặng tôi",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="くださる",
        canonical_reading="くださる",
        acceptable_variants=["くださる", "くださいます", "ください"],
        triplet_sonkeigo="くださる",
        triplet_kenjougo="差し上げる",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Sếp cho tôi lời khuyên → くださる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「部長が貴重なアドバイスをくださいました。」",
        example_vi="Trưởng phòng đã ban tặng cho tôi những lời khuyên vô cùng quý giá.",
    ),
    KeigoWordEntry(
        source_word="寝る",
        source_reading="ねる",
        meaning_vi="ngủ / nghỉ ngơi",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お休みになる",
        canonical_reading="おやすみになる",
        acceptable_variants=["お休みになる", "お休みになります", "お休みになられる", "寝られる", "寝られます"],
        triplet_sonkeigo="お休みになる",
        triplet_kenjougo="休ませていただく",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Chúc sếp nghỉ ngơi ngủ ngon → お休みになる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="お + V(stem) + になる",
        example_ja="「どうぞごゆっくりお休みになってください。」",
        example_vi="Kính chúc quý khách nghỉ ngơi thật thoải mái ạ.",
    ),
    KeigoWordEntry(
        source_word="着る",
        source_reading="きる",
        meaning_vi="mặc (quần áo)",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お召しになる",
        canonical_reading="おめしになる",
        acceptable_variants=["お召しになる", "お召しになります", "着られる", "着られます"],
        triplet_sonkeigo="お召しになる",
        triplet_kenjougo="着させていただく",
        category="sonkeigo_irregular",
        jlpt_level="N3",
        explanation_vi="Sếp mặc bộ vest rất đẹp → お召しになる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「素敵なコートをお召しになっていらっしゃいますね。」",
        example_vi="Ngài mặc chiếc áo khoác này trông thật lịch lãm ạ.",
    ),
    KeigoWordEntry(
        source_word="死ぬ",
        source_reading="しぬ",
        meaning_vi="mất / qua đời",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お亡くなりになる",
        canonical_reading="おなくなりになる",
        acceptable_variants=["お亡くなりになる", "お亡くなりになります", "ご逝去なさる"],
        triplet_sonkeigo="お亡くなりになる",
        triplet_kenjougo="亡くなる",
        category="sonkeigo_irregular",
        jlpt_level="N3",
        explanation_vi="Người thân của khách hàng qua đời → お亡くなりになる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="お + V(stem) + になる",
        example_ja="「先月、会長がお亡くなりになりました。」",
        example_vi="Tháng trước Chủ tịch hội đồng quản trị đã qua đời ạ.",
    ),
    KeigoWordEntry(
        source_word="会う",
        source_reading="あう",
        meaning_vi="gặp",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お会いになる",
        canonical_reading="おあいになる",
        acceptable_variants=["お会いになる", "お会いになります", "会われる", "会われます"],
        triplet_sonkeigo="お会いになる",
        triplet_kenjougo="お目にかかる",
        category="sonkeigo_irregular",
        jlpt_level="N3",
        explanation_vi="Sếp đi gặp khách hàng → お会いになる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="お + V(stem) + になる / Thể bị động: 会われる",
        example_ja="「社長は本日、取引先の代表とお会いになります。」",
        example_vi="Hôm nay Giám đốc sẽ diện kiến đại diện bên đối tác ạ.",
    ),
    KeigoWordEntry(
        source_word="座る",
        source_reading="すわる",
        meaning_vi="ngồi",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お掛けになる",
        canonical_reading="おかえになる",
        acceptable_variants=["お掛けになる", "お掛けになります", "お掛けください", "お座りになる", "座られる"],
        triplet_sonkeigo="お掛けになる / お座りになる",
        triplet_kenjougo="座らせていただく",
        category="sonkeigo_irregular",
        jlpt_level="N4",
        explanation_vi="Mời khách ngồi ghế → どうぞお掛けになってください",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="お + V(stem) + になる",
        example_ja="「どうぞこちらのソファにお掛けになってください。」",
        example_vi="Kính mời quý khách ngồi xuống ghế sofa này ạ.",
    ),
    KeigoWordEntry(
        source_word="買う",
        source_reading="かう",
        meaning_vi="mua",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お求めになる",
        canonical_reading="おもとめになる",
        acceptable_variants=["お求めになる", "お求めになります", "お買い求めになる", "買われる", "買われます"],
        triplet_sonkeigo="お求めになる",
        triplet_kenjougo="買い求める",
        category="sonkeigo_irregular",
        jlpt_level="N3",
        explanation_vi="Khách mua sản phẩm → お求めになる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="お + V(stem) + になる",
        example_ja="「こちらの新商品をお求めになりますでしょうか？」",
        example_vi="Quý khách có muốn chọn mua sản phẩm mới này không ạ?",
    ),
]

# ==============================================================================
# 2. CORE KENJOUGO & TEICHOUGO IRREGULAR (Khiêm nhường ngữ bất quy tắc — 25 động từ)
# ==============================================================================
KENJOUGO_IRREGULAR: list[KeigoWordEntry] = [
    KeigoWordEntry(
        source_word="する",
        source_reading="する",
        meaning_vi="làm",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="いたす",
        canonical_reading="いたす",
        acceptable_variants=["いたす", "いたします", "致す", "致します"],
        triplet_sonkeigo="なさる",
        triplet_kenjougo="いたす",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Bản thân/công ty mình làm → いたす (いたします)",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「私どもが責任を持って対応いたします。」",
        example_vi="Bên chúng tôi xin phép chịu trách nhiệm giải quyết việc này ạ.",
    ),
    KeigoWordEntry(
        source_word="行く",
        source_reading="いく",
        meaning_vi="đi",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="参る",
        canonical_reading="まいる",
        acceptable_variants=["参る", "参ります", "まいる", "まいります", "伺う", "伺います"],
        triplet_sonkeigo="いらっしゃる / おいでになる",
        triplet_kenjougo="参る / 伺う",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi xin phép đi đến → 参る (hoặc 伺う khi đi đến gặp ai)",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「明日の10時に御社へ伺います。」",
        example_vi="10 giờ sáng mai tôi xin phép được đến thăm quý công ty ạ.",
    ),
    KeigoWordEntry(
        source_word="来る",
        source_reading="くる",
        meaning_vi="đến",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="参る",
        canonical_reading="まいる",
        acceptable_variants=["参る", "参ります", "まいる", "まいります"],
        triplet_sonkeigo="いらっしゃる / お越しになる",
        triplet_kenjougo="参る",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi từ chi nhánh đến → 参りました",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「ベトナム支社から参りましたグエンと申します。」",
        example_vi="Tôi là Nguyen, đến từ chi nhánh Việt Nam ạ.",
    ),
    KeigoWordEntry(
        source_word="居る",
        source_reading="いる",
        meaning_vi="ở / có mặt",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="おる",
        canonical_reading="おる",
        acceptable_variants=["おる", "おります"],
        triplet_sonkeigo="いらっしゃる",
        triplet_kenjougo="おる",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi đang ở phòng họp → おります",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「私は午後5時までオフィスにおります。」",
        example_vi="Tôi sẽ ở lại văn phòng cho đến 5 giờ chiều ạ.",
    ),
    KeigoWordEntry(
        source_word="言う",
        source_reading="いう",
        meaning_vi="nói / tên là",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="申す",
        canonical_reading="もうす",
        acceptable_variants=["申す", "申します", "申し上げる", "申し上げます"],
        triplet_sonkeigo="おっしゃる",
        triplet_kenjougo="申す / 申し上げる",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi tên là Tanaka → 田中と申します (trình bày với đối tác → 申し上げる)",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「営業部のナムと申します。よろしくお願いいたします。」",
        example_vi="Tôi là Nam đến từ phòng Kinh doanh. Rất mong được giúp đỡ ạ.",
    ),
    KeigoWordEntry(
        source_word="食べる",
        source_reading="たべる",
        meaning_vi="ăn",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="いただく",
        canonical_reading="いただく",
        acceptable_variants=["いただく", "いただきます", "頂く", "頂きます"],
        triplet_sonkeigo="召し上がる",
        triplet_kenjougo="いただく",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi xin phép dùng bữa → いただきます",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「お土産のお菓子、大変美味しくいただきました。」",
        example_vi="Bánh kẹo quà tặng của quý vị, chúng tôi đã thưởng thức rất ngon miệng ạ.",
    ),
    KeigoWordEntry(
        source_word="飲む",
        source_reading="のむ",
        meaning_vi="uống",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="いただく",
        canonical_reading="いただく",
        acceptable_variants=["いただく", "いただきます", "頂く", "頂きます"],
        triplet_sonkeigo="召し上がる",
        triplet_kenjougo="いただく",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi xin phép uống trà → いただきます",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「お茶を遠慮なくいただきます。」",
        example_vi="Tôi xin phép không khách sáo dùng trà ạ.",
    ),
    KeigoWordEntry(
        source_word="見る",
        source_reading="みる",
        meaning_vi="xem / nhìn",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="拝見する",
        canonical_reading="はいけんする",
        acceptable_variants=["拝見する", "拝見します", "はいけんする", "はいけんします", "拝見いたす", "拝見いたします"],
        triplet_sonkeigo="ご覧になる",
        triplet_kenjougo="拝見する",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi đã xem qua email của quý đối tác → 拝見いたしました",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「お送りいただいたご提案書を拝見いたしました。」",
        example_vi="Tôi đã xem qua bản đề xuất mà quý công ty vừa gửi ạ.",
    ),
    KeigoWordEntry(
        source_word="知る",
        source_reading="しる",
        meaning_vi="biết",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="存じる",
        canonical_reading="ぞんじる",
        acceptable_variants=["存じる", "存じます", "存じております", "存じ上げる", "存じ上げます"],
        triplet_sonkeigo="ご存知だ",
        triplet_kenjougo="存じる / 存じ上げる",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi có biết việc đó → 存じております",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「その件につきましては重々存じております。」",
        example_vi="Về vụ việc đó tôi đã nắm bắt và hiểu rất rõ rồi ạ.",
    ),
    KeigoWordEntry(
        source_word="もらう",
        source_reading="もらう",
        meaning_vi="nhận",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="いただく",
        canonical_reading="いただく",
        acceptable_variants=["いただく", "いただきます", "頂戴する", "ちょうだいする", "頂戴いたします"],
        triplet_sonkeigo="お受け取りになる",
        triplet_kenjougo="いただく / 頂戴する",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi nhận danh thiếp từ khách → 頂戴いたします",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「名刺を1枚頂戴いたします。」",
        example_vi="Tôi xin phép được nhận 1 tấm danh thiếp của quý vị ạ.",
    ),
    KeigoWordEntry(
        source_word="あげる",
        source_reading="あげる",
        meaning_vi="tặng / đưa cho",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="差し上げる",
        canonical_reading="さしあげる",
        acceptable_variants=["差し上げる", "差し上げます", "進呈する"],
        triplet_sonkeigo="くださる",
        triplet_kenjougo="差し上げる",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi xin phép gửi tặng tài liệu → 差し上げます",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「後ほど詳しい資料を差し上げます。」",
        example_vi="Lát nữa tôi xin phép gửi tặng quý vị tài liệu chi tiết ạ.",
    ),
    KeigoWordEntry(
        source_word="会う",
        source_reading="あう",
        meaning_vi="gặp",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お目にかかる",
        canonical_reading="おめにかかる",
        acceptable_variants=["お目にかかる", "お目にかかります", "お会いする", "お会いいたします"],
        triplet_sonkeigo="お会いになる",
        triplet_kenjougo="お目にかかる",
        category="kenjougo_irregular",
        jlpt_level="N3",
        explanation_vi="Rất vinh hạnh được gặp quý ngài → お目にかかれて光栄です",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「本日お目にかかれて大変光栄に存じます。」",
        example_vi="Hôm nay được diện kiến quý ngài tôi cảm thấy vô cùng vinh hạnh ạ.",
    ),
    KeigoWordEntry(
        source_word="聞く",
        source_reading="きく",
        meaning_vi="nghe / hỏi",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="伺う",
        canonical_reading="うかがう",
        acceptable_variants=["伺う", "伺います", "拝聴する", "はいちょうする", "お聞きする"],
        triplet_sonkeigo="お聞きになる",
        triplet_kenjougo="伺う / 拝聴する",
        category="kenjougo_irregular",
        jlpt_level="N4",
        explanation_vi="Tôi xin phép hỏi ý kiến của sếp → 伺う (lắng nghe bài giảng → 拝聴する)",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「詳しいお話を伺ってもよろしいでしょうか？」",
        example_vi="Tôi xin phép được lắng nghe câu chuyện chi tiết được không ạ?",
    ),
    KeigoWordEntry(
        source_word="読む",
        source_reading="よむ",
        meaning_vi="đọc",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="拝読する",
        canonical_reading="はいどくする",
        acceptable_variants=["拝読する", "拝読します", "拝読いたします", "お読みする"],
        triplet_sonkeigo="お読みになる",
        triplet_kenjougo="拝読する",
        category="kenjougo_irregular",
        jlpt_level="N3",
        explanation_vi="Tôi đã đọc bức thư của quý đối tác → 拝読いたしました",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「お手紙を拝読いたしました。」",
        example_vi="Tôi đã kính cẩn đọc xong lá thư của quý vị ạ.",
    ),
    KeigoWordEntry(
        source_word="伝える",
        source_reading="つたえる",
        meaning_vi="nhắn lại / truyền đạt",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="申し伝える",
        canonical_reading="もうしつたえる",
        acceptable_variants=["申し伝える", "申し伝えます", "お伝えする", "お伝えいたします"],
        triplet_sonkeigo="お伝えになる",
        triplet_kenjougo="申し伝える",
        category="kenjougo_irregular",
        jlpt_level="N3",
        explanation_vi="Tôi sẽ nhắn lại với người phụ trách bên mình → 担当の者に申し伝えます",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「担当の者に必ず申し伝えます。」",
        example_vi="Tôi nhất định sẽ chuyển lời này đến người phụ trách bên công ty tôi ạ.",
    ),
    KeigoWordEntry(
        source_word="借りる",
        source_reading="かりる",
        meaning_vi="mượn",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="拝借する",
        canonical_reading="はいしゃくする",
        acceptable_variants=["拝借する", "拝借します", "拝借いたします", "お借りする", "お借りいたします"],
        triplet_sonkeigo="お借りになる",
        triplet_kenjougo="拝借する",
        category="kenjougo_irregular",
        jlpt_level="N3",
        explanation_vi="Tôi xin phép mượn chiếc bút → ペンを拝借いたします",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Bất quy tắc (Đặc biệt)",
        example_ja="「お知恵を少し拝借できますでしょうか？」",
        example_vi="Tôi có thể xin mượn một chút sáng kiến của quý vị được không ạ?",
    ),
]

# ==============================================================================
# 3. RULE-BASED KEIGO (Công thức quy tắc: お〜になる ↔ Thể bị động & お/ご〜いたす)
# ==============================================================================
RULE_BASED_KEIGO: list[KeigoWordEntry] = [
    # --- Sonkeigo Quy tắc (お〜になる / になります & Thể bị động 〜れる/られる) ---
    KeigoWordEntry(
        source_word="書く",
        source_reading="かく",
        meaning_vi="viết",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お書きになる",
        canonical_reading="おかきになる",
        acceptable_variants=["お書きになる", "お書きになります", "書かれる", "書かれます"],
        triplet_sonkeigo="お書きになる / 書かれる",
        triplet_kenjougo="お書きする / お書きいたします",
        category="rule_based",
        jlpt_level="N4",
        explanation_vi="Sếp viết thư/ký hợp đồng → お書きになる (hoặc bị động 書かれる)",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Công thức: お + V(stem) + になる / Thể bị động: 書かれる",
        example_ja="「こちらにお名前とお電話番号をお書きになってください。」",
        example_vi="Xin mời quý khách vui lòng viết họ tên và số điện thoại vào đây ạ.",
    ),
    KeigoWordEntry(
        source_word="読む",
        source_reading="よむ",
        meaning_vi="đọc",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お読みになる",
        canonical_reading="およみになる",
        acceptable_variants=["お読みになる", "お読みになります", "読まれる", "読まれます"],
        triplet_sonkeigo="お読みになる / 読まれる",
        triplet_kenjougo="拝読する / 拝読いたします",
        category="rule_based",
        jlpt_level="N4",
        explanation_vi="Khách đọc điều khoản hợp đồng → お読みになる (hoặc 読まれる)",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Công thức: お + V(stem) + になる / Thể bị động: 読まれる",
        example_ja="「利用規約を事前にお読みになりましたか？」",
        example_vi="Quý khách đã đọc qua điều khoản dịch vụ trước đó chưa ạ?",
    ),
    KeigoWordEntry(
        source_word="待つ",
        source_reading="まつ",
        meaning_vi="chờ đợi",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お待ちになる",
        canonical_reading="おまちになる",
        acceptable_variants=["お待ちになる", "お待ちになります", "待たれる", "待たれます", "お待ちください", "お待ちくださいませ"],
        triplet_sonkeigo="お待ちになる / 待たれる",
        triplet_kenjougo="お待ちする / お待ちいたします",
        category="rule_based",
        jlpt_level="N4",
        explanation_vi="Xin mời quý khách đợi một chút → 少々お待ちください",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Công thức: お + V(stem) + になる / Thể bị động: 待たれる",
        example_ja="「担当者が参りますので、少々お待ちになってください。」",
        example_vi="Người phụ trách sắp tới, xin kính mời quý khách đợi một lát ạ.",
    ),
    KeigoWordEntry(
        source_word="使う",
        source_reading="つかう",
        meaning_vi="sử dụng / dùng",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お使いになる",
        canonical_reading="おつかいになる",
        acceptable_variants=["お使いになる", "お使いになります", "使われる", "使われます"],
        triplet_sonkeigo="お使いになる / 使われる",
        triplet_kenjougo="お使いする",
        category="rule_based",
        jlpt_level="N4",
        explanation_vi="Quý khách dùng thẻ tín dụng → お使いになる",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Công thức: お + V(stem) + になる / Thể bị động: 使われる",
        example_ja="「どちらのクレジットカードをお使いになりますか？」",
        example_vi="Quý khách sử dụng loại thẻ tín dụng nào vậy ạ?",
    ),
    KeigoWordEntry(
        source_word="帰る",
        source_reading="かえる",
        meaning_vi="về / ra về",
        target_type="sonkeigo",
        target_label_vi="Tôn kính ngữ (尊敬語)",
        canonical="お帰りになる",
        canonical_reading="おかえりになる",
        acceptable_variants=["お帰りになる", "お帰りになります", "帰られる", "帰られます"],
        triplet_sonkeigo="お帰りになる / 帰られる",
        triplet_kenjougo="失礼する",
        category="rule_based",
        jlpt_level="N4",
        explanation_vi="Giám đốc đã về nhà lúc nãy → お帰りになりました",
        subject_hint_vi="👑 Hành động của: SẾP / ĐỐI TÁC / KHÁCH HÀNG",
        formula="Công thức: お + V(stem) + になる / Thể bị động: 帰られる",
        example_ja="「社長は先ほどご自宅へお帰りになりました。」",
        example_vi="Giám đốc vừa mới ra về nhà lúc nãy rồi ạ.",
    ),
    # --- Kenjougo Quy tắc Cách 1 (Nhóm 1 & 2: お + V_stem + します / いたします) ---
    KeigoWordEntry(
        source_word="持つ",
        source_reading="もつ",
        meaning_vi="cầm / mang giúp",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お持ちする",
        canonical_reading="おもちする",
        acceptable_variants=["お持ちする", "お持ちします", "お持ちいたす", "お持ちいたします"],
        triplet_sonkeigo="お持ちになる",
        triplet_kenjougo="お持ちする / お持ちいたします",
        category="rule_based",
        jlpt_level="N4",
        explanation_vi="Để tôi xách hành lý giúp quý khách → お持ちいたします",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Cách 1: お + V(stem) + します / いたします",
        example_ja="「重いお荷物は私がロビーまでお持ちいたします。」",
        example_vi="Hành lý nặng để tôi xin phép xách ra sảnh giúp quý khách ạ.",
    ),
    KeigoWordEntry(
        source_word="送る",
        source_reading="おくる",
        meaning_vi="gửi (tài liệu/email)",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お送りする",
        canonical_reading="おおくりする",
        acceptable_variants=["お送りする", "お送りします", "お送りいたす", "お送りいたします"],
        triplet_sonkeigo="お送りになる",
        triplet_kenjougo="お送りする / お送りいたします",
        category="rule_based",
        jlpt_level="N4",
        explanation_vi="Tôi xin phép gửi báo giá qua email → お送りいたします",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Cách 1: お + V(stem) + します / いたします",
        example_ja="「メールにて見積書をお送りいたしました。」",
        example_vi="Tôi đã xin phép gửi bảng báo giá qua email rồi ạ.",
    ),
    KeigoWordEntry(
        source_word="届ける",
        source_reading="とどける",
        meaning_vi="giao đến",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お届けする",
        canonical_reading="おとどけする",
        acceptable_variants=["お届けする", "お届けします", "お届けいたす", "お届けいたします"],
        triplet_sonkeigo="お届けになる",
        triplet_kenjougo="お届けする / お届けいたします",
        category="rule_based",
        jlpt_level="N3",
        explanation_vi="Bên tôi sẽ giao tài liệu đến trong hôm nay → お届けいたします",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Cách 1: お + V(stem) + します / いたします",
        example_ja="「本日中に請求書をお届けいたします。」",
        example_vi="Tôi xin phép được giao hóa đơn đến trong ngày hôm nay ạ.",
    ),
    KeigoWordEntry(
        source_word="手伝う",
        source_reading="てつだう",
        meaning_vi="giúp đỡ",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お手伝いする",
        canonical_reading="おてつだいする",
        acceptable_variants=["お手伝いする", "お手伝いします", "お手伝いいたす", "お手伝いいたします"],
        triplet_sonkeigo="お手伝いになる",
        triplet_kenjougo="お手伝いする / お手伝いいたします",
        category="rule_based",
        jlpt_level="N4",
        explanation_vi="Để tôi phụ giúp chuẩn bị hội trường → お手伝いいたします",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Cách 1: お + V(stem) + します / いたします",
        example_ja="「会場の準備を喜んでお手伝いいたします。」",
        example_vi="Tôi rất sẵn lòng phụ giúp chuẩn bị hội trường ạ.",
    ),
    # --- Kenjougo Quy tắc Cách 2 (Nhóm 3: ご + Danh từ Hán tự + します / いたします) ---
    KeigoWordEntry(
        source_word="連絡する",
        source_reading="れんらくする",
        meaning_vi="liên lạc",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="ご連絡いたす",
        canonical_reading="ごれんらくいたす",
        acceptable_variants=["ご連絡いたす", "ご連絡いたします", "ご連絡する", "ご連絡します", "ご連絡申し上げます"],
        triplet_sonkeigo="ご連絡なさる / ご連絡になる",
        triplet_kenjougo="ご連絡いたす / ご連絡いたします",
        category="rule_based",
        jlpt_level="N3",
        explanation_vi="Bên tôi sẽ chủ động liên lạc lại → ご連絡いたします",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Cách 2: ご + N(Hán tự) + します / いたします",
        example_ja="「確認が取れ次第、すぐにご連絡いたします。」",
        example_vi="Ngay sau khi xác nhận xong, tôi sẽ lập tức liên lạc lại ạ.",
    ),
    KeigoWordEntry(
        source_word="案内する",
        source_reading="あんないする",
        meaning_vi="hướng dẫn / dẫn đường",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="ご案内いたす",
        canonical_reading="ごあんないいたす",
        acceptable_variants=["ご案内いたす", "ご案内いたします", "ご案内する", "ご案内します"],
        triplet_sonkeigo="ご案内なさる / ご案内になる",
        triplet_kenjougo="ご案内いたす / ご案内いたします",
        category="rule_based",
        jlpt_level="N3",
        explanation_vi="Tôi xin phép hướng dẫn lối đi → ご案内いたします",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Cách 2: ご + N(Hán tự) + します / いたします",
        example_ja="「会議室まで私がご案内いたします。」",
        example_vi="Tôi xin phép được dẫn đường cho quý vị đến phòng họp ạ.",
    ),
    KeigoWordEntry(
        source_word="説明する",
        source_reading="せつめいする",
        meaning_vi="giải thích / trình bày",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="ご説明いたす",
        canonical_reading="ごせつめいいたす",
        acceptable_variants=["ご説明いたす", "ご説明いたします", "ご説明する", "ご説明します", "ご説明申し上げます"],
        triplet_sonkeigo="ご説明なさる / ご説明になる",
        triplet_kenjougo="ご説明いたす / ご説明いたします",
        category="rule_based",
        jlpt_level="N3",
        explanation_vi="Tôi xin phép giải thích chi tiết bảng hợp đồng → ご説明いたします",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Cách 2: ご + N(Hán tự) + します / いたします",
        example_ja="「本日の流れについて詳しくご説明いたします。」",
        example_vi="Tôi xin phép được trình bày chi tiết về tiến trình làm việc hôm nay ạ.",
    ),
    KeigoWordEntry(
        source_word="報告する",
        source_reading="ほうこくする",
        meaning_vi="báo cáo",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="ご報告いたす",
        canonical_reading="ごほうこくいたす",
        acceptable_variants=["ご報告いたす", "ご報告いたします", "ご報告する", "ご報告します", "ご報告申し上げます"],
        triplet_sonkeigo="ご報告なさる",
        triplet_kenjougo="ご報告いたす / ご報告いたします",
        category="rule_based",
        jlpt_level="N3",
        explanation_vi="Tôi xin phép báo cáo tiến độ công việc với sếp → ご報告いたします",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Cách 2: ご + N(Hán tự) + します / いたします",
        example_ja="「プロジェクトの進捗状況をご報告いたします。」",
        example_vi="Tôi xin phép được báo cáo về tiến độ của dự án ạ.",
    ),
    KeigoWordEntry(
        source_word="相談する",
        source_reading="そうだんする",
        meaning_vi="trao đổi / bàn bạc",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="ご相談いたす",
        canonical_reading="ごそうだんいたす",
        acceptable_variants=["ご相談いたす", "ご相談いたします", "ご相談する", "ご相談します", "ご相談申し上げます"],
        triplet_sonkeigo="ご相談なさる",
        triplet_kenjougo="ご相談いたす / ご相談いたします",
        category="rule_based",
        jlpt_level="N3",
        explanation_vi="Tôi muốn xin phép được trao đổi với trưởng phòng → ご相談がございます",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Cách 2: ご + N(Hán tự) + します / いたします",
        example_ja="「新規案件についてご相談申し上げたいことがございます。」",
        example_vi="Về dự án mới, tôi có điều muốn xin phép được bàn bạc với ngài ạ.",
    ),
    KeigoWordEntry(
        source_word="電話する",
        source_reading="でんわする",
        meaning_vi="gọi điện thoại (Ngoại lệ Kango)",
        target_type="kenjougo",
        target_label_vi="Khiêm nhường ngữ (謙譲語)",
        canonical="お電話いたす",
        canonical_reading="おでんわいたす",
        acceptable_variants=["お電話いたす", "お電話いたします", "お電話する", "お電話します", "お電話差し上げます"],
        triplet_sonkeigo="お電話なさる",
        triplet_kenjougo="お電話いたす / お電話差し上げる",
        category="rule_based",
        jlpt_level="N4",
        explanation_vi="Ngoại lệ Hán tự dùng tiền tố「お」: Tôi sẽ gọi lại cho quý vị → お電話いたします",
        subject_hint_vi="🙇 Hành động của: BẢN THÂN / CÔNG TY MÌNH",
        formula="Ngoại lệ: お + Hán tự thân thuộc + します / いたします",
        example_ja="「後ほど担当者より改めてお電話を差し上げます。」",
        example_vi="Lát nữa người phụ trách bên tôi sẽ xin phép gọi điện lại ạ.",
    ),
]

# ==============================================================================
# 4. NOUN & ADJECTIVE PREFIXES (Công thức Tiền tố お vs ご cho Danh từ & Tính từ)
# ==============================================================================
NOUN_ADJECTIVE_PREFIXES: list[KeigoWordEntry] = [
    # --- Tiền tố「お」(O): Thuần Nhật (Kunyomi) & Ngoại lệ quen thuộc ---
    KeigoWordEntry(
        source_word="名前",
        source_reading="なまえ",
        meaning_vi="tên của đối phương",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="お名前",
        canonical_reading="おなまえ",
        acceptable_variants=["お名前", "おなまえ"],
        category="noun_prefixes",
        jlpt_level="N5",
        explanation_vi="Kunyomi (Thuần Nhật) → Thêm tiền tố「お」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「お」(O): Đi với từ thuần Nhật (Kunyomi)",
        example_ja="「恐れ入りますが、お名前をお聞かせ願えますか？」",
        example_vi="Xin thứ lỗi, quý khách có thể vui lòng cho tôi xin quý danh được không ạ?",
    ),
    KeigoWordEntry(
        source_word="元気",
        source_reading="げんき",
        meaning_vi="khỏe mạnh / sức khỏe đối phương",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="お元気",
        canonical_reading="おげんき",
        acceptable_variants=["お元気", "おげんき", "お元気ですか"],
        category="noun_prefixes",
        jlpt_level="N5",
        explanation_vi="Trạng thái của đối phương → Thêm tiền tố「お」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「お」(O): Đi với từ thuần Nhật (Kunyomi)",
        example_ja="「その後、お変わりなくお元気でお過ごしでしょうか？」",
        example_vi="Dạo gần đây quý ngài vẫn bình an và mạnh khỏe chứ ạ?",
    ),
    KeigoWordEntry(
        source_word="宅",
        source_reading="たく",
        meaning_vi="nhà của đối phương",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="お宅",
        canonical_reading="おたく",
        acceptable_variants=["お宅", "おたく"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Nhà của khách hàng/đối phương → Thêm tiền tố「お」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「お」(O): Đi với từ thuần Nhật (Kunyomi)",
        example_ja="「明日、先生のお宅へご挨拶に伺います。」",
        example_vi="Ngày mai tôi xin phép được đến nhà thầy để chào hỏi ạ.",
    ),
    KeigoWordEntry(
        source_word="仕事",
        source_reading="しごと",
        meaning_vi="công việc của đối phương",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="お仕事",
        canonical_reading="おしごと",
        acceptable_variants=["お仕事", "おしごと"],
        category="noun_prefixes",
        jlpt_level="N5",
        explanation_vi="Công việc của đối tác → Thêm tiền tố「お」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「お」(O): Đi với từ thuần Nhật (Kunyomi)",
        example_ja="「お仕事中にお邪魔して誠に申し訳ございません。」",
        example_vi="Tôi vô cùng xin lỗi vì đã làm phiền quý vị trong giờ làm việc ạ.",
    ),
    KeigoWordEntry(
        source_word="電話",
        source_reading="でんわ",
        meaning_vi="cuộc gọi / số điện thoại (Ngoại lệ Hán tự)",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="お電話",
        canonical_reading="おでんわ",
        acceptable_variants=["お電話", "おでんわ"],
        category="noun_prefixes",
        jlpt_level="N5",
        explanation_vi="Ngoại lệ: Dù là từ gốc Hán nhưng quen thuộc đời sống nên thêm「お」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Ngoại lệ kinh điển: Thêm「お」cho Hán tự quen thuộc",
        example_ja="「お電話いただき誠にありがとうございます。」",
        example_vi="Chân thành cảm ơn quý khách đã gọi điện đến cho chúng tôi ạ.",
    ),
    KeigoWordEntry(
        source_word="食事",
        source_reading="しょくじ",
        meaning_vi="bữa ăn (Ngoại lệ Hán tự)",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="お食事",
        canonical_reading="おしょくじ",
        acceptable_variants=["お食事", "おしょくじ"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Ngoại lệ: Từ gốc Hán thân thuộc nên thêm「お」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Ngoại lệ kinh điển: Thêm「お」cho Hán tự quen thuộc",
        example_ja="「お食事はお口に合いましたでしょうか？」",
        example_vi="Bữa ăn có vừa khẩu vị của quý khách không ạ?",
    ),
    KeigoWordEntry(
        source_word="料理",
        source_reading="りょうり",
        meaning_vi="món ăn (Ngoại lệ Hán tự)",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="お料理",
        canonical_reading="おりょうり",
        acceptable_variants=["お料理", "おりょうり"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Ngoại lệ: Từ gốc Hán quen thuộc nên thêm「お」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Ngoại lệ kinh điển: Thêm「お」cho Hán tự quen thuộc",
        example_ja="「温かいうちにお料理をお召し上がりください。」",
        example_vi="Xin kính mời quý khách dùng món ăn trong lúc còn nóng ạ.",
    ),
    KeigoWordEntry(
        source_word="時間",
        source_reading="じかん",
        meaning_vi="thời gian quý báu (Ngoại lệ Hán tự)",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="お時間",
        canonical_reading="おじかん",
        acceptable_variants=["お時間", "おじかん"],
        category="noun_prefixes",
        jlpt_level="N5",
        explanation_vi="Ngoại lệ: Thời gian của đối phương → Thêm「お」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Ngoại lệ kinh điển: Thêm「お」cho Hán tự quen thuộc",
        example_ja="「少しだけお時間をいただいてもよろしいでしょうか？」",
        example_vi="Tôi có thể xin phép một chút thời gian của quý vị được không ạ?",
    ),
    KeigoWordEntry(
        source_word="忙しい",
        source_reading="いそがしい",
        meaning_vi="bận rộn (Tính từ thuần Nhật)",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="お忙しい",
        canonical_reading="おいそがしい",
        acceptable_variants=["お忙しい", "おいそがしい", "お忙しいところ"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Tính từ thuần Nhật Kunyomi chỉ trạng thái đối phương → Thêm「お」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「お」(O): Đi với Tính từ thuần Nhật",
        example_ja="「お忙しいところご足労いただき恐れ入ります。」",
        example_vi="Trong lúc bận rộn quý vị đã cất công đến đây, thật vô cùng cảm kích ạ.",
    ),
    # --- Tiền tố「ご」(Go): Từ gốc Hán (Onyomi 2 âm tiết) ---
    KeigoWordEntry(
        source_word="家族",
        source_reading="かぞく",
        meaning_vi="gia đình của đối phương",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご家族",
        canonical_reading="ごかぞく",
        acceptable_variants=["ご家族", "ごかぞく", "ご家族の皆様"],
        category="noun_prefixes",
        jlpt_level="N5",
        explanation_vi="Từ gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với từ gốc Hán (Onyomi)",
        example_ja="「ご家族の皆様にもどうぞよろしくお伝えください。」",
        example_vi="Xin cho tôi gửi lời chào trân trọng đến gia đình quý vị ạ.",
    ),
    KeigoWordEntry(
        source_word="意見",
        source_reading="いけん",
        meaning_vi="ý kiến đóng góp của đối tác",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご意見",
        canonical_reading="ごいけん",
        acceptable_variants=["ご意見", "ごいけん"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Từ gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với từ gốc Hán (Onyomi)",
        example_ja="「貴重なご意見を賜りまして心より感謝いたします。」",
        example_vi="Tôi xin chân thành cảm ơn những ý kiến vô cùng quý báu của quý vị.",
    ),
    KeigoWordEntry(
        source_word="連絡",
        source_reading="れんらく",
        meaning_vi="sự liên lạc của đối tác",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご連絡",
        canonical_reading="ごれんらく",
        acceptable_variants=["ご連絡", "ごれんらく"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Từ gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với từ gốc Hán (Onyomi)",
        example_ja="「早々のご連絡をいただき誠にありがとうございます。」",
        example_vi="Cảm ơn quý vị đã nhanh chóng liên lạc lại cho chúng tôi.",
    ),
    KeigoWordEntry(
        source_word="住所",
        source_reading="じゅうしょ",
        meaning_vi="địa chỉ nhà của đối tác",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご住所",
        canonical_reading="ごじゅうしょ",
        acceptable_variants=["ご住所", "ごじゅうしょ"],
        category="noun_prefixes",
        jlpt_level="N5",
        explanation_vi="Từ gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với từ gốc Hán (Onyomi)",
        example_ja="「書類の送付先のご住所を教えていただけますでしょうか？」",
        example_vi="Quý khách có thể cho tôi xin địa chỉ nơi gửi tài liệu đến được không ạ?",
    ),
    KeigoWordEntry(
        source_word="都合",
        source_reading="つごう",
        meaning_vi="sự tiện lợi / lịch trình của đối tác",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご都合",
        canonical_reading="ごつごう",
        acceptable_variants=["ご都合", "ごつごう", "ご都合はいかがでしょうか"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Từ gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với từ gốc Hán (Onyomi)",
        example_ja="「明日の午後のご都合はいかがでしょうか？」",
        example_vi="Lịch trình chiều mai của quý ngài thế nào, có tiện không ạ?",
    ),
    KeigoWordEntry(
        source_word="予定",
        source_reading="よてい",
        meaning_vi="kế hoạch dự kiến của đối tác",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご予定",
        canonical_reading="ごよてい",
        acceptable_variants=["ご予定", "ごよてい"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Từ gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với từ gốc Hán (Onyomi)",
        example_ja="「来週のご予定が決まり次第、教えていただけますか？」",
        example_vi="Ngay sau khi có kế hoạch tuần tới, quý ngài có thể báo lại cho bên em được không ạ?",
    ),
    KeigoWordEntry(
        source_word="案内",
        source_reading="あんない",
        meaning_vi="thông tin hướng dẫn",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご案内",
        canonical_reading="ごあんない",
        acceptable_variants=["ご案内", "ごあんない"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Từ gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với từ gốc Hán (Onyomi)",
        example_ja="「セミナーの詳細につきましては別紙のご案内をご参照ください。」",
        example_vi="Về chi tiết hội thảo, xin vui lòng xem tài liệu hướng dẫn đính kèm ạ.",
    ),
    KeigoWordEntry(
        source_word="説明",
        source_reading="せつめい",
        meaning_vi="lời giải thích",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご説明",
        canonical_reading="ごせつめい",
        acceptable_variants=["ご説明", "ごせつめい"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Từ gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với từ gốc Hán (Onyomi)",
        example_ja="「ご説明の中で何かご不明な点はございましたでしょうか？」",
        example_vi="Trong phần trình bày giải thích, quý khách có chỗ nào chưa rõ không ạ?",
    ),
    KeigoWordEntry(
        source_word="協力",
        source_reading="きょうりょく",
        meaning_vi="sự hợp tác giúp đỡ",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご協力",
        canonical_reading="ごきょうりょく",
        acceptable_variants=["ご協力", "ごきょうりょく"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Từ gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với từ gốc Hán (Onyomi)",
        example_ja="「アンケートへのご協力をお願い申し上げます。」",
        example_vi="Chúng tôi kính mong nhận được sự hợp tác trả lời phiếu khảo sát ạ.",
    ),
    KeigoWordEntry(
        source_word="検討",
        source_reading="けんとう",
        meaning_vi="sự xem xét cân nhắc",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご検討",
        canonical_reading="ごけんとう",
        acceptable_variants=["ご検討", "ごけんとう", "ご検討のほど"],
        category="noun_prefixes",
        jlpt_level="N3",
        explanation_vi="Từ gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với từ gốc Hán (Onyomi)",
        example_ja="「前向きなご検討のほど、よろしくお願い申し上げます。」",
        example_vi="Rất mong quý công ty tích cực xem xét cân nhắc bản đề xuất này ạ.",
    ),
    KeigoWordEntry(
        source_word="親切",
        source_reading="しんせつ",
        meaning_vi="sự tử tế chu đáo (Tính từ gốc Hán)",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご親切",
        canonical_reading="ごしんせつ",
        acceptable_variants=["ご親切", "ごしんせつ", "ご親切に"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Tính từ Na gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với Tính từ gốc Hán",
        example_ja="「ご親切に教えていただき、本当に助かりました。」",
        example_vi="Được quý vị tận tình chỉ bảo, tôi thật sự đã được giúp đỡ rất nhiều.",
    ),
    KeigoWordEntry(
        source_word="心配",
        source_reading="しんぱい",
        meaning_vi="sự lo lắng bận tâm",
        target_type="prefix",
        target_label_vi="Tiền tố Tôn kính (美化語・尊敬語)",
        canonical="ご心配",
        canonical_reading="ごしんぱい",
        acceptable_variants=["ご心配", "ごしんぱい", "ご心配をおかけして"],
        category="noun_prefixes",
        jlpt_level="N4",
        explanation_vi="Từ gốc Hán (Onyomi) → Thêm tiền tố「ご」",
        subject_hint_vi="🌸 Thuộc sở hữu của KHÁCH HÀNG / ĐỐI TÁC",
        formula="Thêm「ご」(Go): Đi với từ gốc Hán (Onyomi)",
        example_ja="「多大なご心配をおかけして誠に申し訳ございません。」",
        example_vi="Tôi vô cùng xin lỗi vì đã khiến quý vị phải bận tâm lo lắng nhiều.",
    ),
]

# ==============================================================================
# 5. BUSINESS NOUNS, PRONOUNS & TIME (Từ xưng hô, Thời gian & Phó từ công sở)
# ==============================================================================
BUSINESS_WORDS: list[KeigoWordEntry] = [
    # --- Đại từ nhân xưng & Xưng hô Uchi / Soto ---
    KeigoWordEntry(
        source_word="わたし",
        source_reading="わたし",
        meaning_vi="tôi (bản thân mình)",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="わたくし",
        canonical_reading="わたくし",
        acceptable_variants=["わたくし", "私"],
        category="business_words",
        jlpt_level="N4",
        explanation_vi="Xưng hô bản thân trang trọng trước đối tác → わたくし",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi đại từ thương mại",
        example_ja="「営業担当のわたくしがお手伝いいたします。」",
        example_vi="Tôi là người phụ trách kinh doanh, xin phép được hỗ trợ quý vị.",
    ),
    KeigoWordEntry(
        source_word="わたしたち",
        source_reading="わたしたち",
        meaning_vi="chúng tôi (người công ty mình)",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="私ども",
        canonical_reading="わたくしども",
        acceptable_variants=["私ども", "わたくしども"],
        category="business_words",
        jlpt_level="N4",
        explanation_vi="Đại diện công ty mình khi nói với khách ngoài → 私ども (わたくしども)",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi đại từ thương mại",
        example_ja="「私ども一同、心よりお待ち申し上げております。」",
        example_vi="Toàn thể bên công ty chúng tôi hết lòng mong chờ được đón tiếp quý vị.",
    ),
    KeigoWordEntry(
        source_word="会社(mình)",
        source_reading="かいしゃ",
        meaning_vi="công ty của mình (Uchi)",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="弊社",
        canonical_reading="へいしゃ",
        acceptable_variants=["弊社", "へいしゃ", "当社", "とうしゃ"],
        category="business_words",
        jlpt_level="N3",
        explanation_vi="Công ty của mình khi nói với khách ngoài → 弊社 (hoặc 当社)",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại (Uchi)",
        example_ja="「弊社の担当より折り返しお電話を差し上げます。」",
        example_vi="Người phụ trách bên công ty tôi sẽ gọi điện lại cho quý vị ạ.",
    ),
    KeigoWordEntry(
        source_word="会社(khách)",
        source_reading="かいしゃ",
        meaning_vi="công ty của khách (Soto)",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="御社",
        canonical_reading="おんしゃ",
        acceptable_variants=["御社", "おんしゃ", "貴社", "きしゃ"],
        category="business_words",
        jlpt_level="N3",
        explanation_vi="Công ty khách hàng: khi nói dùng 御社 (おんしゃ), khi viết thư dùng 貴社 (きしゃ)",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại (Soto)",
        example_ja="「御社のますますのご発展を心よりお祈り申し上げます。」",
        example_vi="Chúng tôi chân thành kính chúc quý công ty ngày càng phát triển thịnh vượng.",
    ),
    KeigoWordEntry(
        source_word="人",
        source_reading="ひと",
        meaning_vi="người / vị",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="方",
        canonical_reading="かた",
        acceptable_variants=["方", "かた", "皆様", "みなさま"],
        category="business_words",
        jlpt_level="N5",
        explanation_vi="Người kia → あの方 (あのかた)",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「あちらにいらっしゃる方はどなたでしょうか？」",
        example_vi="Xin hỏi vị đứng ở đằng kia là ai thế ạ?",
    ),
    KeigoWordEntry(
        source_word="だれ",
        source_reading="だれ",
        meaning_vi="ai (xin hỏi quý danh)",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="どなた",
        canonical_reading="どなた",
        acceptable_variants=["どなた", "どちら様", "どちらさま", "どなた様"],
        category="business_words",
        jlpt_level="N5",
        explanation_vi="Xin hỏi ngài là ai → どちら様でしょうか / どなた様",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「失礼ですが、どちら様でしょうか？」",
        example_vi="Xin thứ lỗi, xin hỏi quý khách là ai ạ?",
    ),
    KeigoWordEntry(
        source_word="どこ",
        source_reading="どこ",
        meaning_vi="ở đâu / phía nào",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="どちら",
        canonical_reading="どちら",
        acceptable_variants=["どちら", "どちら様"],
        category="business_words",
        jlpt_level="N5",
        explanation_vi="Phòng họp ở đâu → 会議室はどちらでしょうか",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「お手洗いはどちらにございますでしょうか？」",
        example_vi="Xin hỏi nhà vệ sinh nằm ở phía nào vậy ạ?",
    ),
    KeigoWordEntry(
        source_word="どう",
        source_reading="どう",
        meaning_vi="thế nào / ra sao",
        target_type="business",
        target_label_vi="Từ xưng hô lịch sự (ビジネス語)",
        canonical="いかが",
        canonical_reading="いかが",
        acceptable_variants=["いかが", "いかがでしょうか"],
        category="business_words",
        jlpt_level="N5",
        explanation_vi="Ý kiến ngài thế nào → いかがでしょうか",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「こちらのご提案はいかがでしょうか？」",
        example_vi="Bản đề xuất này của bên em quý ngài thấy thế nào ạ?",
    ),
    # --- Từ vựng chỉ thời gian ---
    KeigoWordEntry(
        source_word="今日",
        source_reading="きょう",
        meaning_vi="hôm nay",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="本日",
        canonical_reading="ほんじつ",
        acceptable_variants=["本日", "ほんじつ"],
        category="business_words",
        jlpt_level="N4",
        explanation_vi="Hôm nay trong thư từ & công sở → 本日 (ほんじつ)",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「本日はご多忙の中、お時間をいただき恐れ入ります。」",
        example_vi="Hôm nay trong lúc bận rộn quý vị đã dành thời gian cho chúng tôi, thật cảm kích ạ.",
    ),
    KeigoWordEntry(
        source_word="明日",
        source_reading="あした",
        meaning_vi="ngày mai",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="明日",
        canonical_reading="みょうにち",
        acceptable_variants=["明日", "みょうにち", "あす"],
        category="business_words",
        jlpt_level="N3",
        explanation_vi="Ngày mai lịch sự → 明日 (みょうにち / あす)",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「明日、改めてご連絡申し上げます。」",
        example_vi="Ngày mai tôi xin phép được liên lạc lại với quý vị ạ.",
    ),
    KeigoWordEntry(
        source_word="昨日",
        source_reading="きのう",
        meaning_vi="hôm qua",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="昨日",
        canonical_reading="さくじつ",
        acceptable_variants=["昨日", "さくじつ"],
        category="business_words",
        jlpt_level="N3",
        explanation_vi="Hôm qua lịch sự trong công sở → 昨日 (さくじつ)",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「昨日は大変お世話になりありがとうございました。」",
        example_vi="Hôm qua đã được quý vị quan tâm giúp đỡ rất nhiều, xin chân thành cảm ơn ạ.",
    ),
    KeigoWordEntry(
        source_word="おととい",
        source_reading="おととい",
        meaning_vi="hôm kia",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="一昨日",
        canonical_reading="いっさくじつ",
        acceptable_variants=["一昨日", "いっさくじつ"],
        category="business_words",
        jlpt_level="N2",
        explanation_vi="Hôm kia lịch sự → 一昨日 (いっさくじつ)",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「一昨日お送りいたしましたメールをご確認いただけますでしょうか？」",
        example_vi="Quý vị có thể kiểm tra giúp tôi email đã gửi hôm kia được không ạ?",
    ),
    KeigoWordEntry(
        source_word="あさって",
        source_reading="あさって",
        meaning_vi="ngày kìa",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="明後日",
        canonical_reading="みょうごにち",
        acceptable_variants=["明後日", "みょうごにち"],
        category="business_words",
        jlpt_level="N2",
        explanation_vi="Ngày kìa lịch sự → 明後日 (みょうごにち)",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「明後日の午後にお時間をいただけますでしょうか？」",
        example_vi="Chiều ngày kìa quý vị có thể dành chút thời gian cho chúng tôi được không ạ?",
    ),
    KeigoWordEntry(
        source_word="今年",
        source_reading="ことし",
        meaning_vi="năm nay",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="本年",
        canonical_reading="ほんねん",
        acceptable_variants=["本年", "ほんねん"],
        category="business_words",
        jlpt_level="N3",
        explanation_vi="Năm nay trong văn phong công sở → 本年 (ほんねん)",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「本年もどうぞよろしくお願い申し上げます。」",
        example_vi="Năm nay cũng rất mong tiếp tục nhận được sự giúp đỡ của quý vị ạ.",
    ),
    KeigoWordEntry(
        source_word="去年",
        source_reading="きょねん",
        meaning_vi="năm ngoái",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="昨年",
        canonical_reading="さくねん",
        acceptable_variants=["昨年", "さくねん"],
        category="business_words",
        jlpt_level="N3",
        explanation_vi="Năm ngoái lịch sự → 昨年 (さくねん)",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「昨年に引き続き、ご愛顧いただきありがとうございます。」",
        example_vi="Nối tiếp năm ngoái, cảm ơn quý khách đã luôn tin tưởng ủng hộ ạ.",
    ),
    # --- Phó từ & Tính từ thương mại ---
    KeigoWordEntry(
        source_word="いい",
        source_reading="いい",
        meaning_vi="được / tốt",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="よろしい",
        canonical_reading="よろしい",
        acceptable_variants=["よろしい", "よろしいでしょうか", "結構です", "けっこうです"],
        category="business_words",
        jlpt_level="N5",
        explanation_vi="Có được không → よろしいでしょうか",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「こちらの内容でよろしいでしょうか？」",
        example_vi="Nội dung như thế này đã được chưa ạ?",
    ),
    KeigoWordEntry(
        source_word="ちょっと",
        source_reading="ちょっと",
        meaning_vi="một chút / một lát",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="少々",
        canonical_reading="しょうしょう",
        acceptable_variants=["少々", "しょうしょう", "少し", "しばらく"],
        category="business_words",
        jlpt_level="N4",
        explanation_vi="Xin đợi một chút → 少々お待ちください",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「確認いたしますので、少々お待ちいただけますでしょうか？」",
        example_vi="Tôi xin phép kiểm tra lại, quý khách vui lòng đợi một chút được không ạ?",
    ),
    KeigoWordEntry(
        source_word="すぐ",
        source_reading="すぐ",
        meaning_vi="ngay lập tức / gấp",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="至急",
        canonical_reading="しきゅう",
        acceptable_variants=["至急", "しきゅう", "ただちに", "早急に"],
        category="business_words",
        jlpt_level="N3",
        explanation_vi="Lập tức làm việc này ngay → 至急対応いたします",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「至急、確認して折り返しご連絡いたします。」",
        example_vi="Tôi sẽ kiểm tra khẩn cấp và gọi điện lại ngay cho quý vị ạ.",
    ),
    KeigoWordEntry(
        source_word="いくら",
        source_reading="いくら",
        meaning_vi="bao nhiêu tiền",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="おいくら",
        canonical_reading="おいくら",
        acceptable_variants=["おいくら", "いかほど"],
        category="business_words",
        jlpt_level="N4",
        explanation_vi="Giá tiền bao nhiêu ạ → おいくらでしょうか",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「こちらの商品の合計はおいくらになりますでしょうか？」",
        example_vi="Tổng tiền cho sản phẩm này là bao nhiêu vậy ạ?",
    ),
    KeigoWordEntry(
        source_word="すみません",
        source_reading="すみません",
        meaning_vi="xin lỗi / cảm kích",
        target_type="business",
        target_label_vi="Từ thương mại lịch sự (ビジネス語)",
        canonical="申し訳ございません",
        canonical_reading="もうしわけございません",
        acceptable_variants=["申し訳ございません", "申し訳ありません", "恐れ入ります"],
        category="business_words",
        jlpt_level="N4",
        explanation_vi="Xin lỗi khách hàng chuẩn mực công sở → 申し訳ございません",
        subject_hint_vi="💼 Từ xưng hô & Giao tiếp công sở",
        formula="Biến đổi từ vựng thương mại",
        example_ja="「ご不便をおかけして誠に申し訳ございません。」",
        example_vi="Chúng tôi vô cùng xin lỗi vì đã gây ra bất tiện này cho quý vị.",
    ),
]

# Combined Pool across all 5 practical categories
ALL_KEIGO_WORDS: list[KeigoWordEntry] = (
    SONKEIGO_IRREGULAR
    + KENJOUGO_IRREGULAR
    + RULE_BASED_KEIGO
    + NOUN_ADJECTIVE_PREFIXES
    + BUSINESS_WORDS
)

KEIGO_CATEGORY_MAP: dict[str, list[KeigoWordEntry]] = {
    "sonkeigo_irregular": SONKEIGO_IRREGULAR,
    "kenjougo_irregular": KENJOUGO_IRREGULAR,
    "rule_based": RULE_BASED_KEIGO,
    "noun_prefixes": NOUN_ADJECTIVE_PREFIXES,
    "business_words": BUSINESS_WORDS,
}


def get_all_keigo_vocab() -> list[KeigoWordEntry]:
    return ALL_KEIGO_WORDS


def get_sonkeigo_pool() -> list[KeigoWordEntry]:
    return SONKEIGO_IRREGULAR


def get_kenjougo_pool() -> list[KeigoWordEntry]:
    return KENJOUGO_IRREGULAR


def get_rule_based_pool() -> list[KeigoWordEntry]:
    return RULE_BASED_KEIGO


def get_prefix_vocab_pool() -> list[KeigoWordEntry]:
    return NOUN_ADJECTIVE_PREFIXES


def get_business_vocab_pool() -> list[KeigoWordEntry]:
    return BUSINESS_WORDS


def get_easy_keigo_vocab() -> list[KeigoWordEntry]:
    return ALL_KEIGO_WORDS


def get_normal_keigo_vocab() -> list[KeigoWordEntry]:
    return ALL_KEIGO_WORDS


def get_hard_keigo_vocab() -> list[KeigoWordEntry]:
    return ALL_KEIGO_WORDS


def get_keigo_by_category(category: str) -> list[KeigoWordEntry]:
    if not category or category == "all":
        return ALL_KEIGO_WORDS
    if category in KEIGO_CATEGORY_MAP:
        return KEIGO_CATEGORY_MAP[category]
    if category in ("sonkeigo", "sonkeigo_irregular"):
        return SONKEIGO_IRREGULAR
    if category in ("kenjougo", "kenjougo_irregular"):
        return KENJOUGO_IRREGULAR
    if category in ("rule", "rule_based"):
        return RULE_BASED_KEIGO
    if category in ("prefix", "prefixes", "noun_prefixes", "o_go"):
        return NOUN_ADJECTIVE_PREFIXES
    if category in ("business", "business_words"):
        return BUSINESS_WORDS
    return ALL_KEIGO_WORDS


def search_keigo(query: str) -> list[KeigoWordEntry]:
    if not query.strip():
        return ALL_KEIGO_WORDS
    q = query.lower().strip()
    primary = [
        k for k in ALL_KEIGO_WORDS
        if q in k.source_word.lower()
        or q in k.source_reading.lower()
        or q in k.canonical.lower()
        or q in k.canonical_reading.lower()
        or q in k.meaning_vi.lower()
        or any(q in syn.lower() for syn in k.acceptable_variants)
        or q in (k.triplet_sonkeigo or "").lower()
        or q in (k.triplet_kenjougo or "").lower()
        or q in (k.formula or "").lower()
    ]
    if primary:
        return primary
    return [
        k for k in ALL_KEIGO_WORDS
        if q in k.example_ja.lower()
        or q in k.example_vi.lower()
        or q in k.explanation_vi.lower()
    ]
