"""BCCWJ High-Frequency Daily-Life Japanese Vocabulary Pool (BCCWJ & Spoken Subtitles).

Curated from:
- Balanced Corpus of Contemporary Written Japanese (BCCWJ - NINJAL)
- Spoken Japanese Subtitles & Conversational Frequency Dataset (Wordfreq / OpenSubtitles)

Covers Tier 1 (Top 1,000 core words), Tier 2 (Top 1,001 - 3,000), and Tier 3 (Top 3,001 - 5,000)
spanning 5 communicative categories:
- action_verbs: Động từ hành động thiết yếu đời sống
- emotions_adj: Tính từ cảm xúc & trạng thái
- adverbs_mimetic: Phó từ & Từ tượng thanh / tượng hình (擬音語・擬態語)
- workplace_biz: Công sở, Thương mại & Báo cáo (Hou-Ren-So)
- daily_life: Sinh hoạt, Mua sắm & Dịch vụ
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class FrequencyWordEntry:
    rank: int  # Frequency ranking (1 = most common in Japanese language)
    word: str  # Kanji / Kana surface form
    reading: str  # Hiragana reading
    pos: str  # 'verb' | 'noun' | 'adj_i' | 'adj_na' | 'adverb' | 'phrase'
    category: str  # 'action_verbs' | 'emotions_adj' | 'adverbs_mimetic' | 'workplace_biz' | 'daily_life'
    meaning_vi: str  # Vietnamese meaning
    synonyms_vi: list[str] = field(default_factory=list)
    collocation_ja: str = ""  # Natural Japanese collocation
    collocation_vi: str = ""  # Vietnamese collocation translation
    example_ja: str = ""  # Conversational example sentence
    example_vi: str = ""  # Vietnamese sentence translation
    jlpt: str = "N4"  # JLPT level
    tier: int = 1  # 1: Top 1000, 2: Top 3000, 3: Top 5000
    frequency_score: float = 9.0  # Log-frequency score (higher = more frequent)
# =========================================================================
# 1. CORE ACTION VERBS (Động từ hành động & đời sống tần suất cao nhất)
# =========================================================================
CORE_ACTION_VERBS: list[FrequencyWordEntry] = [
    FrequencyWordEntry(
        rank=12,
        word="行く",
        reading="いく",
        pos="verb",
        category="action_verbs",
        meaning_vi="đi",
        synonyms_vi=['di chuyển', 'tới'],
        collocation_ja="学校に行く",
        collocation_vi="đi đến trường",
        example_ja="「明日、友達と一緒に映画を見に行きます。」",
        example_vi="Ngày mai tôi sẽ đi xem phim cùng với bạn.",
        jlpt="N5",
        tier=1,
        frequency_score=9.85,
    ),
    FrequencyWordEntry(
        rank=15,
        word="見る",
        reading="みる",
        pos="verb",
        category="action_verbs",
        meaning_vi="xem, nhìn",
        synonyms_vi=['quan sát', 'ngắm'],
        collocation_ja="テレビを見る",
        collocation_vi="xem TV",
        example_ja="「昨日、夜遅くまでアニメを見ていました。」",
        example_vi="Hôm qua tôi đã xem anime tới tận khuya.",
        jlpt="N5",
        tier=1,
        frequency_score=9.80,
    ),
    FrequencyWordEntry(
        rank=18,
        word="言う",
        reading="いう",
        pos="verb",
        category="action_verbs",
        meaning_vi="nói",
        synonyms_vi=['bảo', 'phát biểu'],
        collocation_ja="本当のことを言う",
        collocation_vi="nói sự thật",
        example_ja="「彼が言ったことは本当だと思います。」",
        example_vi="Tôi nghĩ điều anh ấy nói là thật.",
        jlpt="N5",
        tier=1,
        frequency_score=9.78,
    ),
    FrequencyWordEntry(
        rank=20,
        word="する",
        reading="する",
        pos="verb",
        category="action_verbs",
        meaning_vi="làm, thực hiện",
        synonyms_vi=['tiến hành'],
        collocation_ja="宿題をする",
        collocation_vi="làm bài tập",
        example_ja="「今夜は家でゆっくり勉強します。」",
        example_vi="Tối nay tôi sẽ ở nhà thong thả học bài.",
        jlpt="N5",
        tier=1,
        frequency_score=9.75,
    ),
    FrequencyWordEntry(
        rank=24,
        word="思う",
        reading="おもう",
        pos="verb",
        category="action_verbs",
        meaning_vi="nghĩ, cảm thấy",
        synonyms_vi=['cho rằng', 'ngỡ'],
        collocation_ja="そう思う",
        collocation_vi="nghĩ như vậy",
        example_ja="「この問題は少し難しいと思います。」",
        example_vi="Tôi nghĩ vấn đề này hơi khó một chút.",
        jlpt="N4",
        tier=1,
        frequency_score=9.70,
    ),
    FrequencyWordEntry(
        rank=28,
        word="来る",
        reading="くる",
        pos="verb",
        category="action_verbs",
        meaning_vi="đến, tới",
        synonyms_vi=['ghé qua'],
        collocation_ja="日本に来る",
        collocation_vi="đến Nhật Bản",
        example_ja="「去年、留学のために日本に来ました。」",
        example_vi="Năm ngoái tôi đã đến Nhật để đi du học.",
        jlpt="N5",
        tier=1,
        frequency_score=9.68,
    ),
    FrequencyWordEntry(
        rank=35,
        word="食べる",
        reading="たべる",
        pos="verb",
        category="action_verbs",
        meaning_vi="ăn",
        synonyms_vi=['dùng bữa', 'thưởng thức'],
        collocation_ja="ご飯を食べる",
        collocation_vi="ăn cơm",
        example_ja="「お昼休みに同僚とラーメンを食べました。」",
        example_vi="Giờ nghỉ trưa tôi đã đi ăn ramen cùng đồng nghiệp.",
        jlpt="N5",
        tier=1,
        frequency_score=9.60,
    ),
    FrequencyWordEntry(
        rank=39,
        word="飲む",
        reading="のむ",
        pos="verb",
        category="action_verbs",
        meaning_vi="uống",
        synonyms_vi=['dùng nước'],
        collocation_ja="お茶を飲む",
        collocation_vi="uống trà",
        example_ja="「毎朝、起きてすぐに温かいお茶を飲みます。」",
        example_vi="Mỗi sáng thức dậy tôi đều uống ngay một cốc trà ấm.",
        jlpt="N5",
        tier=1,
        frequency_score=9.55,
    ),
    FrequencyWordEntry(
        rank=45,
        word="聞く",
        reading="きく",
        pos="verb",
        category="action_verbs",
        meaning_vi="nghe, hỏi",
        synonyms_vi=['lắng nghe', 'hỏi han'],
        collocation_ja="音楽を聞く",
        collocation_vi="nghe nhạc",
        example_ja="「分からないことがあれば先生に聞いてください。」",
        example_vi="Nếu có điều gì không hiểu hãy hỏi giáo viên nhé.",
        jlpt="N5",
        tier=1,
        frequency_score=9.50,
    ),
    FrequencyWordEntry(
        rank=50,
        word="話す",
        reading="はなす",
        pos="verb",
        category="action_verbs",
        meaning_vi="nói chuyện, trò chuyện",
        synonyms_vi=['bàn luận', 'trao đổi'],
        collocation_ja="日本語で話す",
        collocation_vi="nói bằng tiếng Nhật",
        example_ja="「もっと上手に日本語で話せるようになりたいです。」",
        example_vi="Tôi muốn nói chuyện bằng tiếng Nhật giỏi hơn nữa.",
        jlpt="N5",
        tier=1,
        frequency_score=9.45,
    ),
    FrequencyWordEntry(
        rank=55,
        word="読む",
        reading="よむ",
        pos="verb",
        category="action_verbs",
        meaning_vi="đọc",
        synonyms_vi=['xem sách'],
        collocation_ja="本を読む",
        collocation_vi="đọc sách",
        example_ja="「寝る前に少しだけ本を読むのが習慣です。」",
        example_vi="Đọc một chút sách trước khi ngủ là thói quen của tôi.",
        jlpt="N5",
        tier=1,
        frequency_score=9.40,
    ),
    FrequencyWordEntry(
        rank=62,
        word="書く",
        reading="かく",
        pos="verb",
        category="action_verbs",
        meaning_vi="viết",
        synonyms_vi=['soạn thảo', 'ghi chép'],
        collocation_ja="日記を書く",
        collocation_vi="viết nhật ký",
        example_ja="「毎日、日本語で短い日記を書いています。」",
        example_vi="Mỗi ngày tôi đều viết một đoạn nhật ký ngắn bằng tiếng Nhật.",
        jlpt="N5",
        tier=1,
        frequency_score=9.35,
    ),
    FrequencyWordEntry(
        rank=70,
        word="買う",
        reading="かう",
        pos="verb",
        category="action_verbs",
        meaning_vi="mua",
        synonyms_vi=['sắm', 'tậu'],
        collocation_ja="買い出しに行く",
        collocation_vi="đi mua đồ",
        example_ja="「スーパーで新鮮な果物を買ってきました。」",
        example_vi="Tôi vừa mua ít hoa quả tươi ngon ở siêu thị về.",
        jlpt="N5",
        tier=1,
        frequency_score=9.30,
    ),
    FrequencyWordEntry(
        rank=82,
        word="待つ",
        reading="まつ",
        pos="verb",
        category="action_verbs",
        meaning_vi="chờ, đợi",
        synonyms_vi=['trông đợi', 'ngóng'],
        collocation_ja="駅で待つ",
        collocation_vi="đợi ở ga",
        example_ja="「改札口の前で友達を待っています。」",
        example_vi="Tôi đang đứng đợi bạn ở trước cửa soát vé.",
        jlpt="N5",
        tier=1,
        frequency_score=9.22,
    ),
    FrequencyWordEntry(
        rank=95,
        word="思い出す",
        reading="おもいだす",
        pos="verb",
        category="action_verbs",
        meaning_vi="nhớ ra, hồi tưởng",
        synonyms_vi=['nhớ lại', 'gợi nhớ'],
        collocation_ja="昔のことを思い出す",
        collocation_vi="nhớ lại chuyện xưa",
        example_ja="「この写真を見ると楽しかった旅行を思い出します。」",
        example_vi="Xem bức ảnh này làm tôi nhớ lại chuyến du lịch vui vẻ.",
        jlpt="N4",
        tier=1,
        frequency_score=9.15,
    ),
    FrequencyWordEntry(
        rank=110,
        word="届ける",
        reading="とどける",
        pos="verb",
        category="action_verbs",
        meaning_vi="giao đến, chuyển tới",
        synonyms_vi=['đưa tới', 'phát chuyển'],
        collocation_ja="荷物を届ける",
        collocation_vi="giao hành lý/hàng",
        example_ja="「明日、大切な書類をご自宅にお届けします。」",
        example_vi="Ngày mai tôi sẽ giao tài liệu quan trọng đến tận nhà quý khách.",
        jlpt="N3",
        tier=1,
        frequency_score=9.05,
    ),
    FrequencyWordEntry(
        rank=125,
        word="受け取る",
        reading="うけとる",
        pos="verb",
        category="action_verbs",
        meaning_vi="nhận lấy, tiếp nhận",
        synonyms_vi=['thu nhận', 'lĩnh'],
        collocation_ja="荷物を受け取る",
        collocation_vi="nhận bưu kiện",
        example_ja="「先ほど配達員から荷物を確かに受け取りました。」",
        example_vi="Tôi vừa mới nhận được bưu kiện từ shipper xong.",
        jlpt="N3",
        tier=1,
        frequency_score=8.98,
    ),
    FrequencyWordEntry(
        rank=140,
        word="片付ける",
        reading="かたづける",
        pos="verb",
        category="action_verbs",
        meaning_vi="dọn dẹp, thu dọn",
        synonyms_vi=['thu dọn', 'ngăn nắp'],
        collocation_ja="部屋を片付ける",
        collocation_vi="dọn dẹp phòng",
        example_ja="「週末に溜まった書類をきれいに片付けました。」",
        example_vi="Cuối tuần tôi đã dọn dẹp sạch sẽ đống tài liệu tồn đọng.",
        jlpt="N4",
        tier=1,
        frequency_score=8.90,
    ),
    FrequencyWordEntry(
        rank=165,
        word="諦める",
        reading="あきらめる",
        pos="verb",
        category="action_verbs",
        meaning_vi="bỏ cuộc, từ bỏ",
        synonyms_vi=['thôi', 'nản lòng'],
        collocation_ja="夢を諦めない",
        collocation_vi="không từ bỏ ước mơ",
        example_ja="「どんなに難しくても最後まで諦めないでください。」",
        example_vi="Dù có khó khăn thế nào xin cũng đừng bỏ cuộc giữa chừng.",
        jlpt="N3",
        tier=1,
        frequency_score=8.82,
    ),
    FrequencyWordEntry(
        rank=180,
        word="案内する",
        reading="あんないする",
        pos="verb",
        category="action_verbs",
        meaning_vi="hướng dẫn, chỉ đường",
        synonyms_vi=['dẫn đường', 'chỉ lối'],
        collocation_ja="街を案内する",
        collocation_vi="dẫn đi tham quan phố",
        example_ja="「日本へ来たら私が東京をご案内しますね。」",
        example_vi="Khi nào bạn sang Nhật, tôi sẽ dẫn bạn đi tham quan Tokyo nhé.",
        jlpt="N4",
        tier=1,
        frequency_score=8.78,
    ),
    FrequencyWordEntry(
        rank=205,
        word="断る",
        reading="ことわる",
        pos="verb",
        category="action_verbs",
        meaning_vi="từ chối",
        synonyms_vi=['khước từ', 'bác bỏ'],
        collocation_ja="誘いを断る",
        collocation_vi="từ chối lời mời",
        example_ja="「先約があったので丁寧にお断りしました。」",
        example_vi="Vì có hẹn trước nên tôi đã từ chối một cách lịch thiệp.",
        jlpt="N3",
        tier=1,
        frequency_score=8.70,
    ),
    FrequencyWordEntry(
        rank=230,
        word="見送る",
        reading="みおくる",
        pos="verb",
        category="action_verbs",
        meaning_vi="tiễn, tiễn đưa",
        synonyms_vi=['đưa tiễn', 'chia tay'],
        collocation_ja="空港で見送る",
        collocation_vi="tiễn ở sân bay",
        example_ja="「国へ帰る友達を空港まで見送りに行きました。」",
        example_vi="Tôi đã ra sân bay để tiễn người bạn về nước.",
        jlpt="N3",
        tier=1,
        frequency_score=8.65,
    ),
    FrequencyWordEntry(
        rank=260,
        word="迎える",
        reading="むかえる",
        pos="verb",
        category="action_verbs",
        meaning_vi="đón, chào đón",
        synonyms_vi=['tiếp đón', 'nghênh đón'],
        collocation_ja="笑顔で迎える",
        collocation_vi="đón chào với nụ cười",
        example_ja="「笑顔でお客様を気持ちよくお迎えしましょう。」",
        example_vi="Chúng ta hãy nở nụ cười đón tiếp khách hàng thật chu đáo.",
        jlpt="N3",
        tier=1,
        frequency_score=8.60,
    ),
    FrequencyWordEntry(
        rank=290,
        word="頼む",
        reading="たのむ",
        pos="verb",
        category="action_verbs",
        meaning_vi="nhờ vả, đặt món",
        synonyms_vi=['yêu cầu', 'nhờ cậy'],
        collocation_ja="お願いを頼む",
        collocation_vi="nhờ vả một việc",
        example_ja="「先輩に企画書のダブルチェックを頼みました。」",
        example_vi="Tôi đã nhờ tiền bối kiểm tra lại bản kế hoạch giúp mình.",
        jlpt="N4",
        tier=1,
        frequency_score=8.55,
    ),
    FrequencyWordEntry(
        rank=42,
        word="連絡する",
        reading="れんらくする",
        pos="verb",
        category="action_verbs",
        meaning_vi="liên lạc",
        synonyms_vi=['gọi điện', 'nhắn tin', 'thông báo'],
        collocation_ja="連絡を取る",
        collocation_vi="giữ liên lạc",
        example_ja="後でLINEで連絡するね！",
        example_vi="Lát nữa mình nhắn qua LINE cho cậu nhé!",
        jlpt="N4",
        tier=1,
        frequency_score=9.45,
    ),
    FrequencyWordEntry(
        rank=280,
        word="振り返る",
        reading="ふりかえる",
        pos="verb",
        category="action_verbs",
        meaning_vi="nhìn lại",
        synonyms_vi=['ngẫm lại', 'quay đầu nhìn'],
        collocation_ja="過去を振り返る",
        collocation_vi="nhìn lại quá khứ",
        example_ja="たまには自分の行動を振り返ることも大切です。",
        example_vi="Thỉnh thoảng nhìn nhận lại hành động của bản thân cũng rất quan trọng.",
        jlpt="N3",
        tier=1,
        frequency_score=8.70,
    ),
    FrequencyWordEntry(
        rank=220,
        word="申し込む",
        reading="もうしこむ",
        pos="verb",
        category="action_verbs",
        meaning_vi="đăng ký",
        synonyms_vi=['ứng tuyển', 'ngỏ lời'],
        collocation_ja="講座に申し込む",
        collocation_vi="đăng ký khóa học",
        example_ja="日本語スピーキング講座に申し込みました。",
        example_vi="Tôi đã đăng ký khóa học luyện nói tiếng Nhật.",
        jlpt="N3",
        tier=1,
        frequency_score=8.82,
    ),
    FrequencyWordEntry(
        rank=58,
        word="確認する",
        reading="かくにんする",
        pos="verb",
        category="action_verbs",
        meaning_vi="xác nhận",
        synonyms_vi=['kiểm tra lại', 'rà soát'],
        collocation_ja="スケジュールを確認する",
        collocation_vi="kiểm tra lịch trình",
        example_ja="念のためもう一度時間を確認しましょう。",
        example_vi="Để cho chắc chắn, chúng ta cùng kiểm tra lại giờ giấc nhé.",
        jlpt="N4",
        tier=1,
        frequency_score=9.38,
    ),
    FrequencyWordEntry(
        rank=145,
        word="相談する",
        reading="そうだんする",
        pos="verb",
        category="action_verbs",
        meaning_vi="thảo luận",
        synonyms_vi=['trao đổi', 'xin ý kiến', 'bàn bạc'],
        collocation_ja="上司に相談する",
        collocation_vi="trao đổi với cấp trên",
        example_ja="困ったことがあればいつでも相談してください。",
        example_vi="Nếu có khó khăn gì bạn cứ trao đổi với tôi bất cứ lúc nào nhé.",
        jlpt="N4",
        tier=1,
        frequency_score=9.05,
    ),
    FrequencyWordEntry(
        rank=380,
        word="乗り換える",
        reading="のりかえる",
        pos="verb",
        category="action_verbs",
        meaning_vi="chuyển tuyến",
        synonyms_vi=['đổi tàu', 'đổi xe'],
        collocation_ja="電車を乗り換える",
        collocation_vi="đổi tàu điện",
        example_ja="次の駅で山手線に乗り換えます。",
        example_vi="Ở ga tiếp theo chúng ta sẽ chuyển sang tuyến Yamanote.",
        jlpt="N4",
        tier=1,
        frequency_score=8.52,
    ),
    FrequencyWordEntry(
        rank=175,
        word="遅れる",
        reading="おくれる",
        pos="verb",
        category="action_verbs",
        meaning_vi="trễ",
        synonyms_vi=['muộn', 'chậm trễ'],
        collocation_ja="時間に遅れる",
        collocation_vi="đến muộn giờ",
        example_ja="事故で電車が15分遅れました。",
        example_vi="Do sự cố nên tàu đã bị trễ 15 phút.",
        jlpt="N4",
        tier=1,
        frequency_score=8.95,
    ),
    FrequencyWordEntry(
        rank=190,
        word="手伝う",
        reading="てつだう",
        pos="verb",
        category="action_verbs",
        meaning_vi="giúp đỡ",
        synonyms_vi=['phụ giúp', 'hỗ trợ'],
        collocation_ja="仕事を手伝う",
        collocation_vi="phụ giúp công việc",
        example_ja="何か手伝えることがあれば言ってね。",
        example_vi="Có việc gì cần phụ giúp thì cứ bảo mình nhé.",
        jlpt="N4",
        tier=1,
        frequency_score=8.91,
    ),
    FrequencyWordEntry(
        rank=250,
        word="誘う",
        reading="さそう",
        pos="verb",
        category="action_verbs",
        meaning_vi="rủ rê",
        synonyms_vi=['mời', 'rủ đi cùng'],
        collocation_ja="食事に誘う",
        collocation_vi="mời đi ăn cơm",
        example_ja="今夜ご飯でも食べに行かないと誘われました。",
        example_vi="Tôi được rủ tối nay đi ăn cơm cùng.",
        jlpt="N3",
        tier=1,
        frequency_score=8.75,
    ),
    FrequencyWordEntry(
        rank=430,
        word="片付く",
        reading="かたづく",
        pos="verb",
        category="action_verbs",
        meaning_vi="được giải quyết",
        synonyms_vi=['được dọn sạch', 'xong xuôi'],
        collocation_ja="仕事が片付く",
        collocation_vi="công việc được giải quyết xong",
        example_ja="ようやく急ぎの仕事が片付きました。",
        example_vi="Cuối cùng công việc gấp cũng đã được giải quyết xong xuôi.",
        jlpt="N3",
        tier=1,
        frequency_score=8.42,
    ),
]

# =========================================================================
# 2. EMOTIONS & EVALUATION ADJECTIVES (Tính từ cảm xúc & đánh giá)
# =========================================================================
CORE_EMOTION_ADJECTIVES: list[FrequencyWordEntry] = [
    FrequencyWordEntry(
        rank=35,
        word="嬉しい",
        reading="うれしい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="vui sướng, hạnh phúc",
        synonyms_vi=['vui vẻ', 'hân hoan'],
        collocation_ja="飛び上がるほど嬉しい",
        collocation_vi="vui đến mức nhảy cẫng lên",
        example_ja="「合格の知らせを聞いて本当に嬉しかったです！」",
        example_vi="Nghe tin thi đỗ tôi thật sự vô cùng vui sướng!",
        jlpt="N4",
        tier=1,
        frequency_score=9.48,
    ),
    FrequencyWordEntry(
        rank=48,
        word="悔しい",
        reading="くやしい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="tiếc nuối, cay cú",
        synonyms_vi=['ấm ức', 'bực bội vì thua'],
        collocation_ja="悔しい思いをする",
        collocation_vi="trải qua cảm giác cay cú tiếc nuối",
        example_ja="「あと1点足りなくて不合格になり本当に悔しいです。」",
        example_vi="Thiếu đúng 1 điểm mà trượt làm tôi thấy vô cùng tiếc nuối và cay cú.",
        jlpt="N3",
        tier=1,
        frequency_score=9.35,
    ),
    FrequencyWordEntry(
        rank=65,
        word="懐かしい",
        reading="なつかしい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="nhớ nhung, hoài niệm",
        synonyms_vi=['thân thương', 'bồi hồi'],
        collocation_ja="懐かしい曲",
        collocation_vi="bài hát hoài niệm",
        example_ja="「昔よく聴いていた曲を聴くと高校時代が懐かしいです。」",
        example_vi="Nghe lại bài hát xưa làm tôi thấy bồi hồi nhớ lại thời cấp ba.",
        jlpt="N3",
        tier=1,
        frequency_score=9.20,
    ),
    FrequencyWordEntry(
        rank=80,
        word="怪しい",
        reading="あやしい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="khả nghi, đáng ngờ",
        synonyms_vi=['mờ ám', 'kỳ lạ'],
        collocation_ja="怪しい人物",
        collocation_vi="kẻ khả nghi",
        example_ja="「夜道で後ろから怪しい人がついてきて怖かったです。」",
        example_vi="Đi đường tối có người khả nghi đi sau làm tôi rất sợ.",
        jlpt="N3",
        tier=1,
        frequency_score=9.10,
    ),
    FrequencyWordEntry(
        rank=105,
        word="羨ましい",
        reading="うらやましい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="ghen tị, ngưỡng mộ",
        synonyms_vi=['thèm được như thế', 'ước gì'],
        collocation_ja="才能が羨ましい",
        collocation_vi="ghen tị với tài năng",
        example_ja="「日本語をネイティブ並みに話せて本当に羨ましいです！」",
        example_vi="Nói tiếng Nhật lưu loát như người bản xứ làm mình ghen tị thật đấy!",
        jlpt="N3",
        tier=1,
        frequency_score=9.00,
    ),
    FrequencyWordEntry(
        rank=120,
        word="もったいない",
        reading="もったいない",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="lãng phí, uổng phí",
        synonyms_vi=['tiếc của', 'uổng công'],
        collocation_ja="時間を無駄にしてはもったいない",
        collocation_vi="lãng phí thời gian thật uổng",
        example_ja="「まだ美味しく食べられるのに捨てるのはもったいないよ。」",
        example_vi="Đồ ăn vẫn còn ngon mà vứt đi thì lãng phí quá.",
        jlpt="N3",
        tier=1,
        frequency_score=8.92,
    ),
    FrequencyWordEntry(
        rank=138,
        word="惜しい",
        reading="おしい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="tiếc, suýt soát",
        synonyms_vi=['uổng', 'chút xíu nữa'],
        collocation_ja="惜しいチャンスを逃す",
        collocation_vi="bỏ lỡ cơ hội đáng tiếc",
        example_ja="「あと1秒あれば勝てたのに、本当に惜しかったです！」",
        example_vi="Chỉ cần thêm 1 giây nữa là thắng rồi, tiếc hùi hụi luôn!",
        jlpt="N3",
        tier=1,
        frequency_score=8.85,
    ),
    FrequencyWordEntry(
        rank=155,
        word="面倒くさい",
        reading="めんどうくさい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="phiền phức, ngại làm",
        synonyms_vi=['lười biếng', 'rầy rà'],
        collocation_ja="手続きが面倒くさい",
        collocation_vi="thủ tục phiền phức",
        example_ja="「休みの日は料理を作るのが面倒くさくて外食します。」",
        example_vi="Ngày nghỉ lười nấu nướng nên tôi ra ngoài ăn tiệm.",
        jlpt="N3",
        tier=1,
        frequency_score=8.76,
    ),
    FrequencyWordEntry(
        rank=175,
        word="頼もしい",
        reading="たのもしい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="đáng tin cậy, vững chãi",
        synonyms_vi=['chỗ dựa tốt', 'vững vàng'],
        collocation_ja="頼もしい仲間",
        collocation_vi="người bạn đồng hành đáng tin",
        example_ja="「彼はいつもピンチの時に助けてくれる頼もしい先輩です。」",
        example_vi="Anh ấy là một tiền bối rất đáng tin cậy luôn giúp tôi lúc nguy cấp.",
        jlpt="N2",
        tier=1,
        frequency_score=8.76,
    ),
    FrequencyWordEntry(
        rank=195,
        word="素晴らしい",
        reading="すばらしい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="tuyệt vời, xuất sắc",
        synonyms_vi=['tuyệt đỉnh', 'hoàn hảo'],
        collocation_ja="素晴らしい成果",
        collocation_vi="thành quả tuyệt vời",
        example_ja="「本当に素晴らしいプレゼンテーションでした！」",
        example_vi="Đó thực sự là một bài thuyết trình vô cùng xuất sắc!",
        jlpt="N4",
        tier=1,
        frequency_score=8.70,
    ),
    FrequencyWordEntry(
        rank=275,
        word="恥ずかしい",
        reading="はずかしい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="xấu hổ",
        synonyms_vi=['ngượng ngùng', 'e thẹn'],
        collocation_ja="人前で恥ずかしい",
        collocation_vi="ngại ngùng trước đám đông",
        example_ja="人前で発表するとき少し恥ずかしかったです。",
        example_vi="Khi thuyết trình trước đám đông tôi cảm thấy hơi ngượng ngùng.",
        jlpt="N4",
        tier=1,
        frequency_score=8.71,
    ),
    FrequencyWordEntry(
        rank=180,
        word="詳しい",
        reading="くわしい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="am hiểu",
        synonyms_vi=['tường tận', 'chi tiết'],
        collocation_ja="パソコンに詳しい",
        collocation_vi="rất rành về máy tính",
        example_ja="彼はITの知識がとても詳しいです。",
        example_vi="Anh ấy rất am hiểu và có kiến thức sâu rộng về mảng IT.",
        jlpt="N3",
        tier=1,
        frequency_score=8.94,
    ),
    FrequencyWordEntry(
        rank=620,
        word="険しい",
        reading="けわしい",
        pos="adj_i",
        category="emotions_adj",
        meaning_vi="hiểm trở",
        synonyms_vi=['dốc đứng', 'nghiêm nghị'],
        collocation_ja="険しい山道",
        collocation_vi="đường núi hiểm trở",
        example_ja="山頂までの道はとても険しかったです。",
        example_vi="Đoạn đường leo lên đỉnh núi rất quanh co hiểm trở.",
        jlpt="N2",
        tier=2,
        frequency_score=8.15,
    ),
    FrequencyWordEntry(
        rank=215,
        word="苦手な",
        reading="にがてな",
        pos="adj_na",
        category="emotions_adj",
        meaning_vi="kém",
        synonyms_vi=['không giỏi', 'ngại'],
        collocation_ja="早起きが苦手",
        collocation_vi="ngại dậy sớm",
        example_ja="私は人前で話すのが少し苦手です。",
        example_vi="Tôi hơi ngại khi phải phát biểu trước đông người.",
        jlpt="N4",
        tier=1,
        frequency_score=8.84,
    ),
    FrequencyWordEntry(
        rank=205,
        word="得意な",
        reading="とくいな",
        pos="adj_na",
        category="emotions_adj",
        meaning_vi="giỏi",
        synonyms_vi=['sở trường', 'thế mạnh'],
        collocation_ja="料理が得意",
        collocation_vi="sở trường nấu ăn",
        example_ja="私の得意な料理はフォーです。",
        example_vi="Món ăn sở trường của tôi là món Phở.",
        jlpt="N4",
        tier=1,
        frequency_score=8.87,
    ),
    FrequencyWordEntry(
        rank=98,
        word="大切な",
        reading="たいせつな",
        pos="adj_na",
        category="emotions_adj",
        meaning_vi="quan trọng",
        synonyms_vi=['quý giá', 'thiết yếu'],
        collocation_ja="大切な約束",
        collocation_vi="lời hứa quan trọng",
        example_ja="家族と過ごす時間は私にとって一番大切です。",
        example_vi="Khoảng thời gian bên gia đình là điều quan trọng nhất với tôi.",
        jlpt="N4",
        tier=1,
        frequency_score=9.22,
    ),
    FrequencyWordEntry(
        rank=235,
        word="新鮮な",
        reading="しんせんな",
        pos="adj_na",
        category="emotions_adj",
        meaning_vi="tươi mới",
        synonyms_vi=['tươi ngon', 'trong lành'],
        collocation_ja="新鮮な魚",
        collocation_vi="cá tươi ngon",
        example_ja="朝市で新鮮な野菜を買ってきました。",
        example_vi="Tôi vừa ra chợ sớm mua được một mớ rau củ rất tươi ngon.",
        jlpt="N3",
        tier=1,
        frequency_score=8.79,
    ),
    FrequencyWordEntry(
        rank=420,
        word="快適な",
        reading="かいてきな",
        pos="adj_na",
        category="emotions_adj",
        meaning_vi="thoải mái",
        synonyms_vi=['dễ chịu', 'tiện nghi'],
        collocation_ja="快適なホテル",
        collocation_vi="khách sạn tiện nghi thoải mái",
        example_ja="この部屋は日当たりが良くてとても快適です。",
        example_vi="Căn phòng này đón nắng tốt nên ở rất thoải mái dễ chịu.",
        jlpt="N3",
        tier=1,
        frequency_score=8.45,
    ),
    FrequencyWordEntry(
        rank=150,
        word="不安な",
        reading="ふあんな",
        pos="adj_na",
        category="emotions_adj",
        meaning_vi="bất an",
        synonyms_vi=['lo lắng', 'lo âu'],
        collocation_ja="将来が不安",
        collocation_vi="lo lắng về tương lai",
        example_ja="初めての一人暮らしは少し不安でした。",
        example_vi="Lần đầu sống tự lập một mình tôi cảm thấy hơi lo lắng.",
        jlpt="N3",
        tier=1,
        frequency_score=9.02,
    ),
]

# =========================================================================
# 3. HIGH-FREQUENCY ADVERBS & MIMETIC WORDS (Phó từ & Tượng thanh tượng hình)
# =========================================================================
CORE_ADVERBS_MIMETIC: list[FrequencyWordEntry] = [
    FrequencyWordEntry(
        rank=40,
        word="やっぱり",
        reading="やっぱり",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="quả nhiên, đúng như dự đoán",
        synonyms_vi=['rốt cuộc', 'y như rằng'],
        collocation_ja="やっぱりそうだと思った",
        collocation_vi="quả nhiên đúng như mình nghĩ",
        example_ja="「いろいろ悩んだけど、やっぱり日本に行きたい！」",
        example_vi="Đắn đo bao nhiêu thứ, nhưng rốt cuộc mình vẫn muốn đi Nhật!",
        jlpt="N4",
        tier=1,
        frequency_score=9.35,
    ),
    FrequencyWordEntry(
        rank=58,
        word="ぺらぺら",
        reading="ぺらぺら",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="lưu loát, trôi chảy",
        synonyms_vi=['như gió', 'bắn như súng liên thanh'],
        collocation_ja="日本語をぺらぺら話す",
        collocation_vi="nói tiếng Nhật lưu loát",
        example_ja="「毎日練習して、1年後にはぺらぺら話せるようになります！」",
        example_vi="Luyện tập mỗi ngày, 1 năm sau tôi sẽ nói lưu loát trôi chảy!",
        jlpt="N3",
        tier=1,
        frequency_score=9.15,
    ),
    FrequencyWordEntry(
        rank=72,
        word="ぎりぎり",
        reading="ぎりぎり",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="sát nút, suýt soát",
        synonyms_vi=['vừa khít', 'trong gang tấc'],
        collocation_ja="ぎりぎり間に合う",
        collocation_vi="kịp sát nút",
        example_ja="「走って駅に向かい、終電にぎりぎり間に合いました！」",
        example_vi="Chạy thục mạng ra ga, tôi đã kịp chuyến tàu cuối sát nút!",
        jlpt="N3",
        tier=1,
        frequency_score=9.05,
    ),
    FrequencyWordEntry(
        rank=92,
        word="うっかり",
        reading="うっかり",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="lơ đãng, sơ ý",
        synonyms_vi=['bất cẩn', 'vô ý'],
        collocation_ja="うっかり忘れる",
        collocation_vi="lơ đãng quên khuấy mất",
        example_ja="「約束の時間をうっかり忘れてしまい大変申し訳ありません。」",
        example_vi="Tôi vô ý quên mất giờ hẹn, thành thật xin lỗi bạn.",
        jlpt="N3",
        tier=1,
        frequency_score=8.95,
    ),
    FrequencyWordEntry(
        rank=115,
        word="すっきり",
        reading="すっきり",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="sảng khoái, nhẹ nhõm",
        synonyms_vi=['gọn gàng', 'thông thoáng'],
        collocation_ja="気分がすっきりする",
        collocation_vi="tâm trạng sảng khoái",
        example_ja="「朝シャワーを浴びて気分がすっきりしました。」",
        example_vi="Sáng tắm vòi sen xong tâm trạng sảng khoái nhẹ nhõm hẳn.",
        jlpt="N3",
        tier=1,
        frequency_score=8.88,
    ),
    FrequencyWordEntry(
        rank=130,
        word="ぴったり",
        reading="ぴったり",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="vừa khít, chuẩn xác",
        synonyms_vi=['khớp', 'hoàn hảo'],
        collocation_ja="サイズがぴったり",
        collocation_vi="kích cỡ vừa khít",
        example_ja="「このスーツはオーダーメイドのようにサイズがぴったりです。」",
        example_vi="Bộ vest này vừa khít như đồ may đo riêng vậy.",
        jlpt="N4",
        tier=1,
        frequency_score=8.80,
    ),
    FrequencyWordEntry(
        rank=150,
        word="ばったり",
        reading="ばったり",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="tình cờ gặp, chạm mặt",
        synonyms_vi=['đột ngột', 'bất ngờ đụng độ'],
        collocation_ja="街でばったり会う",
        collocation_vi="tình cờ chạm mặt trên phố",
        example_ja="「渋谷のスクランブル交差点で昔の同僚にばったり会いました。」",
        example_vi="Tôi tình cờ chạm mặt người đồng nghiệp cũ ngay ngã tư Shibuya.",
        jlpt="N2",
        tier=1,
        frequency_score=8.75,
    ),
    FrequencyWordEntry(
        rank=170,
        word="わざわざ",
        reading="わざわざ",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="cất công, lặn lội",
        synonyms_vi=['không quản công sức', 'nhọc công'],
        collocation_ja="わざわざ来てくれる",
        collocation_vi="cất công đến tận nơi",
        example_ja="「雨の中、わざわざお越しいただき誠にありがとうございます。」",
        example_vi="Trời mưa mà quý khách đã cất công đến tận đây, chúng tôi vô cùng cảm ơn.",
        jlpt="N3",
        tier=1,
        frequency_score=8.70,
    ),
    FrequencyWordEntry(
        rank=190,
        word="どんどん",
        reading="どんどん",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="nhanh chóng, liên tục",
        synonyms_vi=['dồn dập', 'không ngừng nghỉ'],
        collocation_ja="どんどん質問する",
        collocation_vi="hỏi liên tục thoải mái",
        example_ja="「分からない点があれば、恥ずかしがらずにどんどん質問してください！」",
        example_vi="Có chỗ nào chưa rõ đừng ngại mà hãy cứ thoải mái hỏi liên tục nhé!",
        jlpt="N4",
        tier=1,
        frequency_score=8.65,
    ),
    FrequencyWordEntry(
        rank=210,
        word="だんだん",
        reading="だんだん",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="dần dần, từng chút một",
        synonyms_vi=['từ từ', 'theo thời gian'],
        collocation_ja="だんだん慣れる",
        collocation_vi="dần dần quen thuộc",
        example_ja="「最初は難しかった日本語も、だんだん聞き取れるようになってきました。」",
        example_vi="Tiếng Nhật ban đầu thấy khó, giờ tôi cũng dần dần nghe hiểu được rồi.",
        jlpt="N4",
        tier=1,
        frequency_score=8.55,
    ),
    FrequencyWordEntry(
        rank=210,
        word="ますます",
        reading="ますます",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="ngày càng",
        synonyms_vi=['càng ngày càng'],
        collocation_ja="ますます上達する",
        collocation_vi="ngày càng tiến bộ",
        example_ja="練習すればするほど、日本語がますます楽しくなります。",
        example_vi="Càng luyện tập nhiều thì học tiếng Nhật lại càng thấy vui.",
        jlpt="N3",
        tier=1,
        frequency_score=8.85,
    ),
    FrequencyWordEntry(
        rank=170,
        word="ついに",
        reading="ついに",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="cuối cùng thì",
        synonyms_vi=['rốt cuộc'],
        collocation_ja="ついに完成した",
        collocation_vi="cuối cùng đã hoàn thành",
        example_ja="1年間の努力が実を結び、ついに合格しました！",
        example_vi="Nỗ lực suốt một năm đã đơm hoa kết trái, cuối cùng tôi đã đỗ!",
        jlpt="N3",
        tier=1,
        frequency_score=8.96,
    ),
    FrequencyWordEntry(
        rank=135,
        word="しっかり",
        reading="しっかり",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="vững vàng",
        synonyms_vi=['chắc chắn', 'chu đáo'],
        collocation_ja="しっかり食べる",
        collocation_vi="ăn uống đầy đủ",
        example_ja="明日も早いから、今夜はしっかり寝てくださいね。",
        example_vi="Mai phải dậy sớm nên tối nay bạn nhớ ngủ thật đẫy giấc nhé.",
        jlpt="N4",
        tier=1,
        frequency_score=9.08,
    ),
    FrequencyWordEntry(
        rank=245,
        word="せっかく",
        reading="せっかく",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="đã mất công",
        synonyms_vi=['hiếm khi có dịp'],
        collocation_ja="せっかくの機会",
        collocation_vi="cơ hội quý giá",
        example_ja="せっかく日本に来たのだから、温泉に行きましょう！",
        example_vi="Đã cất công sang Nhật rồi thì nhất định phải đi tắm Onsen nhé!",
        jlpt="N3",
        tier=1,
        frequency_score=8.76,
    ),
    FrequencyWordEntry(
        rank=370,
        word="たまたま",
        reading="たまたま",
        pos="adverb",
        category="adverbs_mimetic",
        meaning_vi="ngẫu nhiên",
        synonyms_vi=['tình cờ'],
        collocation_ja="たまたま見つける",
        collocation_vi="tình cờ nhìn thấy",
        example_ja="本屋でたまたま面白い本を見つけました。",
        example_vi="Tôi tình cờ tìm thấy một cuốn sách rất hay ở hiệu sách.",
        jlpt="N3",
        tier=1,
        frequency_score=8.54,
    ),
]

# =========================================================================
# 4. WORKPLACE & BUSINESS VOCABULARY (Công sở, Thương mại & Hou-Ren-So)
# =========================================================================
CORE_WORKPLACE_WORDS: list[FrequencyWordEntry] = [
    FrequencyWordEntry(
        rank=60,
        word="確認",
        reading="かくにん",
        pos="noun",
        category="workplace_biz",
        meaning_vi="xác nhận, kiểm tra",
        synonyms_vi=['rà soát', 'kiểm chứng'],
        collocation_ja="ご確認をお願いします",
        collocation_vi="xin phiền quý khách kiểm tra lại",
        example_ja="「添付ファイルを送信いたしましたので、ご確認のほどよろしくお願いいたします。」",
        example_vi="Tôi đã gửi file đính kèm, kính mong quý vị kiểm tra giúp ạ.",
        jlpt="N4",
        tier=1,
        frequency_score=9.38,
    ),
    FrequencyWordEntry(
        rank=78,
        word="連絡",
        reading="れんらく",
        pos="noun",
        category="workplace_biz",
        meaning_vi="liên lạc, thông báo",
        synonyms_vi=['thông tri', 'nhắn tin'],
        collocation_ja="連絡を取り合う",
        collocation_vi="giữ liên lạc với nhau",
        example_ja="「何か変更がございましたら、すぐにご連絡させていただきます。」",
        example_vi="Nếu có bất kỳ thay đổi nào, tôi xin phép sẽ liên lạc thông báo ngay ạ.",
        jlpt="N4",
        tier=1,
        frequency_score=9.32,
    ),
    FrequencyWordEntry(
        rank=95,
        word="相談",
        reading="そうだん",
        pos="noun",
        category="workplace_biz",
        meaning_vi="thảo luận, trao đổi ý kiến",
        synonyms_vi=['bàn bạc', 'tham vấn'],
        collocation_ja="上司に相談する",
        collocation_vi="trao đổi với cấp trên",
        example_ja="「来期の予算について、一度上司にご相談させてください。」",
        example_vi="Về ngân sách kỳ tới, xin phép cho tôi được bàn bạc trao đổi với sếp một lần.",
        jlpt="N4",
        tier=1,
        frequency_score=9.15,
    ),
    FrequencyWordEntry(
        rank=112,
        word="報告",
        reading="ほうこく",
        pos="noun",
        category="workplace_biz",
        meaning_vi="báo cáo",
        synonyms_vi=['trình báo', 'thông báo kết quả'],
        collocation_ja="進捗を報告する",
        collocation_vi="báo cáo tiến độ",
        example_ja="「本日の会議の結果をまとめ次第、ご報告いたします。」",
        example_vi="Ngay khi tổng hợp xong kết quả cuộc họp hôm nay, tôi sẽ báo cáo lại ạ.",
        jlpt="N3",
        tier=1,
        frequency_score=9.08,
    ),
    FrequencyWordEntry(
        rank=135,
        word="お世話",
        reading="おせわ",
        pos="noun",
        category="workplace_biz",
        meaning_vi="giúp đỡ, chăm sóc",
        synonyms_vi=['chiếu cố', 'ủng hộ'],
        collocation_ja="いつもお世話になっております",
        collocation_vi="cảm ơn quý vị luôn giúp đỡ ủng hộ",
        example_ja="「平素は大変お世話になっております。株式会社ABCの田中です。」",
        example_vi="Xin chào quý công ty. Tôi là Tanaka đến từ công ty ABC.",
        jlpt="N4",
        tier=1,
        frequency_score=8.98,
    ),
    FrequencyWordEntry(
        rank=160,
        word="よろしくお願いします",
        reading="よろしくおねがいします",
        pos="phrase",
        category="workplace_biz",
        meaning_vi="rất mong được giúp đỡ, xin nhờ quý vị",
        synonyms_vi=['kính mong chiếu cố'],
        collocation_ja="今後ともよろしくお願いします",
        collocation_vi="từ nay về sau cũng rất mong được giúp đỡ",
        example_ja="「それでは本日の打ち合わせ、どうぞよろしくお願いいたします。」",
        example_vi="Vậy thì buổi họp trao đổi hôm nay, xin được nhờ quý vị giúp đỡ ạ.",
        jlpt="N5",
        tier=1,
        frequency_score=8.90,
    ),
    FrequencyWordEntry(
        rank=185,
        word="申し訳ございません",
        reading="もうしわけございません",
        pos="phrase",
        category="workplace_biz",
        meaning_vi="vô cùng xin lỗi, thành thật xin lỗi",
        synonyms_vi=['tạ lỗi'],
        collocation_ja="大変申し訳ございません",
        collocation_vi="thành thật vô cùng xin lỗi",
        example_ja="「ご返信が遅れまして、大変申し訳ございませんでした。」",
        example_vi="Thành thật vô cùng xin lỗi vì tôi đã phản hồi chậm trễ.",
        jlpt="N3",
        tier=1,
        frequency_score=8.80,
    ),
    FrequencyWordEntry(
        rank=210,
        word="御社",
        reading="おんしゃ",
        pos="noun",
        category="workplace_biz",
        meaning_vi="quý công ty (khi nói chuyện)",
        synonyms_vi=['bên anh', 'công ty quý đối tác'],
        collocation_ja="御社のご発展",
        collocation_vi="sự phát triển của quý công ty",
        example_ja="「御社と一緒にお仕事ができることを楽しみにしております。」",
        example_vi="Chúng tôi rất mong chờ có cơ hội được hợp tác làm việc cùng quý công ty.",
        jlpt="N3",
        tier=1,
        frequency_score=8.74,
    ),
    FrequencyWordEntry(
        rank=125,
        word="書類",
        reading="しょるい",
        pos="noun",
        category="workplace_biz",
        meaning_vi="tài liệu",
        synonyms_vi=['hồ sơ', 'giấy tờ'],
        collocation_ja="書類を提出する",
        collocation_vi="nộp hồ sơ tài liệu",
        example_ja="会議の前に書類に目を通しておいてください。",
        example_vi="Trước cuộc họp bạn hãy xem qua tập tài liệu này nhé.",
        jlpt="N4",
        tier=1,
        frequency_score=9.12,
    ),
    FrequencyWordEntry(
        rank=480,
        word="納期",
        reading="のうき",
        pos="noun",
        category="workplace_biz",
        meaning_vi="hạn giao hàng",
        synonyms_vi=['deadline', 'thời hạn giao việc'],
        collocation_ja="納期を守る",
        collocation_vi="đảm bảo đúng hạn giao",
        example_ja="クオリティを保ちながら納期に間に合わせます。",
        example_vi="Chúng tôi sẽ đảm bảo chất lượng và giao đúng thời hạn ạ.",
        jlpt="N2",
        tier=1,
        frequency_score=8.35,
    ),
    FrequencyWordEntry(
        rank=115,
        word="担当",
        reading="たんとう",
        pos="noun",
        category="workplace_biz",
        meaning_vi="phụ trách",
        synonyms_vi=['người chịu trách nhiệm'],
        collocation_ja="プロジェクトを担当する",
        collocation_vi="phụ trách dự án",
        example_ja="この案件は私が担当させていただきます。",
        example_vi="Dự án này sẽ do tôi trực tiếp phụ trách ạ.",
        jlpt="N3",
        tier=1,
        frequency_score=9.15,
    ),
    FrequencyWordEntry(
        rank=105,
        word="検討",
        reading="けんとう",
        pos="noun",
        category="workplace_biz",
        meaning_vi="xem xét",
        synonyms_vi=['cân nhắc', 'nghiên cứu'],
        collocation_ja="前向きに検討する",
        collocation_vi="tích cực xem xét",
        example_ja="ご提案いただいた件、社内で前向きに検討いたします。",
        example_vi="Về đề xuất của quý công ty, chúng tôi sẽ tích cực bàn bạc nội bộ.",
        jlpt="N3",
        tier=1,
        frequency_score=9.20,
    ),
    FrequencyWordEntry(
        rank=88,
        word="対応",
        reading="たいおう",
        pos="noun",
        category="workplace_biz",
        meaning_vi="xử lý",
        synonyms_vi=['đối ứng', 'giải quyết'],
        collocation_ja="迅速に対応する",
        collocation_vi="xử lý nhanh chóng",
        example_ja="お客様からのご質問に迅速に対応いたします。",
        example_vi="Chúng tôi sẽ giải đáp nhanh chóng thắc mắc của khách hàng.",
        jlpt="N3",
        tier=1,
        frequency_score=9.28,
    ),
    FrequencyWordEntry(
        rank=270,
        word="打ち合わせ",
        reading="うちあわせ",
        pos="noun",
        category="workplace_biz",
        meaning_vi="cuộc họp trao đổi",
        synonyms_vi=['buổi thảo luận', 'họp bàn'],
        collocation_ja="打ち合わせを行う",
        collocation_vi="tiến hành cuộc họp trao đổi",
        example_ja="明日の午後2時からクライアントと打ち合わせがあります。",
        example_vi="2 giờ chiều mai tôi có buổi họp trao đổi cùng khách hàng.",
        jlpt="N3",
        tier=1,
        frequency_score=8.71,
    ),
    FrequencyWordEntry(
        rank=590,
        word="議事録",
        reading="ぎじろく",
        pos="noun",
        category="workplace_biz",
        meaning_vi="biên bản cuộc họp",
        synonyms_vi=['bản ghi chép họp'],
        collocation_ja="議事録を作成する",
        collocation_vi="soạn biên bản cuộc họp",
        example_ja="本日の会議の議事録をまとめてメールで共有します。",
        example_vi="Tôi sẽ tổng hợp biên bản họp hôm nay và gửi qua email cho mọi người.",
        jlpt="N2",
        tier=2,
        frequency_score=8.20,
    ),
    FrequencyWordEntry(
        rank=360,
        word="見積もり",
        reading="みつもり",
        pos="noun",
        category="workplace_biz",
        meaning_vi="báo giá",
        synonyms_vi=['bản ước tính chi phí'],
        collocation_ja="見積もりを出す",
        collocation_vi="lập bản báo giá",
        example_ja="本日中にお見積もり書を作成してお送りいたします。",
        example_vi="Tôi sẽ hoàn thành bản báo giá và gửi cho quý khách trong hôm nay.",
        jlpt="N3",
        tier=1,
        frequency_score=8.56,
    ),
    FrequencyWordEntry(
        rank=380,
        word="請求書",
        reading="せいきゅうしょ",
        pos="noun",
        category="workplace_biz",
        meaning_vi="hóa đơn thanh toán",
        synonyms_vi=['giấy đòi tiền'],
        collocation_ja="請求書を発行する",
        collocation_vi="xuất hóa đơn thanh toán",
        example_ja="月末までに請求書をお送りいただけますでしょうか？",
        example_vi="Quý công ty gửi hóa đơn thanh toán trước cuối tháng giúp tôi nhé?",
        jlpt="N3",
        tier=1,
        frequency_score=8.52,
    ),
    FrequencyWordEntry(
        rank=130,
        word="契約",
        reading="けいやく",
        pos="noun",
        category="workplace_biz",
        meaning_vi="hợp đồng",
        synonyms_vi=['giao kèo', 'ký kết'],
        collocation_ja="契約を結ぶ",
        collocation_vi="ký kết hợp đồng",
        example_ja="無事に新しい取引先と契約を結ぶことができました。",
        example_vi="Chúng tôi đã thuận lợi ký kết hợp đồng với đối tác mới.",
        jlpt="N3",
        tier=1,
        frequency_score=9.10,
    ),
    FrequencyWordEntry(
        rank=410,
        word="進捗",
        reading="しんちょく",
        pos="noun",
        category="workplace_biz",
        meaning_vi="tiến độ",
        synonyms_vi=['tình hình tiến triển'],
        collocation_ja="進捗を報告する",
        collocation_vi="báo cáo tiến độ",
        example_ja="現在の進捗状況についてご報告させていただきます。",
        example_vi="Tôi xin phép được báo cáo về tiến độ công việc hiện tại.",
        jlpt="N2",
        tier=1,
        frequency_score=8.48,
    ),
    FrequencyWordEntry(
        rank=340,
        word="残業",
        reading="ざんぎょう",
        pos="noun",
        category="workplace_biz",
        meaning_vi="làm thêm giờ",
        synonyms_vi=['tăng ca', 'OT'],
        collocation_ja="残業をする",
        collocation_vi="làm thêm giờ",
        example_ja="今日は納期が近いので1時間だけ残業します。",
        example_vi="Hôm nay sắp đến hạn giao việc nên tôi làm thêm 1 tiếng.",
        jlpt="N3",
        tier=1,
        frequency_score=8.59,
    ),
    FrequencyWordEntry(
        rank=290,
        word="出張",
        reading="しゅっちょう",
        pos="noun",
        category="workplace_biz",
        meaning_vi="đi công tác",
        synonyms_vi=['chuyến công tác'],
        collocation_ja="出張に行く",
        collocation_vi="đi công tác xa",
        example_ja="来週の月曜日から3日間、大阪へ出張に行きます。",
        example_vi="Từ thứ Hai tuần sau tôi sẽ đi công tác ở Osaka 3 ngày.",
        jlpt="N4",
        tier=1,
        frequency_score=8.68,
    ),
    FrequencyWordEntry(
        rank=460,
        word="名刺",
        reading="めいし",
        pos="noun",
        category="workplace_biz",
        meaning_vi="danh thiếp",
        synonyms_vi=['card visit'],
        collocation_ja="名刺を交換する",
        collocation_vi="trao đổi danh thiếp",
        example_ja="初めまして、名刺を交換させていただけますか？",
        example_vi="Lần đầu gặp mặt, xin phép được trao đổi danh thiếp cùng quý vị ạ?",
        jlpt="N3",
        tier=1,
        frequency_score=8.38,
    ),
    FrequencyWordEntry(
        rank=620,
        word="引き継ぎ",
        reading="ひきつぎ",
        pos="noun",
        category="workplace_biz",
        meaning_vi="bàn giao công việc",
        synonyms_vi=['chuyển giao nhiệm vụ'],
        collocation_ja="業務を引き継ぐ",
        collocation_vi="chuyển giao công việc",
        example_ja="有給休暇を取る前にしっかり引き継ぎをしておきます。",
        example_vi="Trước khi nghỉ phép tôi sẽ bàn giao công việc thật chu đáo.",
        jlpt="N2",
        tier=2,
        frequency_score=8.15,
    ),
]

# =========================================================================
# 5. CORE DAILY LIFE & SERVICE (Sinh hoạt, Mua sắm & Dịch vụ)
# =========================================================================
CORE_DAILY_LIFE_WORDS: list[FrequencyWordEntry] = [
    FrequencyWordEntry(
        rank=490,
        word="お会計",
        reading="おかいけい",
        pos="noun",
        category="daily_life",
        meaning_vi="thanh toán",
        synonyms_vi=['tính tiền', 'hóa đơn'],
        collocation_ja="お会計をお願いする",
        collocation_vi="gọi tính tiền",
        example_ja="すみません、お会計をお願いします。",
        example_vi="Xin lỗi, làm ơn tính tiền giúp tôi với ạ.",
        jlpt="N4",
        tier=1,
        frequency_score=8.33,
    ),
    FrequencyWordEntry(
        rank=320,
        word="割引",
        reading="わりびき",
        pos="noun",
        category="daily_life",
        meaning_vi="giảm giá",
        synonyms_vi=['chiết khấu', 'khuyến mãi'],
        collocation_ja="割引クーポン",
        collocation_vi="mã giảm giá khuyến mãi",
        example_ja="このクーポンを使うと20パーセント割引になります。",
        example_vi="Dùng mã giảm giá này bạn sẽ được giảm 20%.",
        jlpt="N3",
        tier=1,
        frequency_score=8.62,
    ),
    FrequencyWordEntry(
        rank=160,
        word="予約",
        reading="よやく",
        pos="noun",
        category="daily_life",
        meaning_vi="đặt chỗ",
        synonyms_vi=['đặt bàn', 'booking'],
        collocation_ja="席を予約する",
        collocation_vi="đặt trước bàn ăn",
        example_ja="金曜日の夜7時にレストランを予約しました。",
        example_vi="Tôi đã đặt bàn ở nhà hàng lúc 7 giờ tối thứ Sáu.",
        jlpt="N4",
        tier=1,
        frequency_score=8.98,
    ),
    FrequencyWordEntry(
        rank=410,
        word="領収書",
        reading="りょうしゅうしょ",
        pos="noun",
        category="daily_life",
        meaning_vi="hóa đơn đỏ",
        synonyms_vi=['hóa đơn thanh toán', 'biên lai'],
        collocation_ja="領収書をもらう",
        collocation_vi="xin cấp hóa đơn đỏ",
        example_ja="会社名義で領収書をいただけますでしょうか？",
        example_vi="Cho tôi xin hóa đơn đỏ ghi tên công ty được không ạ?",
        jlpt="N3",
        tier=1,
        frequency_score=8.48,
    ),
    FrequencyWordEntry(
        rank=175,
        word="注文",
        reading="ちゅうもん",
        pos="noun",
        category="daily_life",
        meaning_vi="gọi món",
        synonyms_vi=['đặt hàng', 'order'],
        collocation_ja="注文を取る",
        collocation_vi="nhận order gọi món",
        example_ja="ご注文が決まりましたらお呼びください。",
        example_vi="Khi nào quý khách chọn xong món xin hãy gọi tôi nhé ạ.",
        jlpt="N4",
        tier=1,
        frequency_score=8.95,
    ),
    FrequencyWordEntry(
        rank=350,
        word="営業時間",
        reading="えいぎょうじかん",
        pos="noun",
        category="daily_life",
        meaning_vi="giờ mở cửa",
        synonyms_vi=['thời gian làm việc'],
        collocation_ja="営業時間を調べる",
        collocation_vi="tra cứu giờ mở cửa",
        example_ja="このカフェの営業時間は夜10時までです。",
        example_vi="Quán cà phê này mở cửa phục vụ đến 10 giờ tối.",
        jlpt="N4",
        tier=1,
        frequency_score=8.58,
    ),
    FrequencyWordEntry(
        rank=580,
        word="定休日",
        reading="ていきゅうび",
        pos="noun",
        category="daily_life",
        meaning_vi="ngày nghỉ định kỳ",
        synonyms_vi=['ngày đóng cửa'],
        collocation_ja="毎週月曜日が定休日",
        collocation_vi="nghỉ cố định vào thứ Hai",
        example_ja="あのお店は水曜日が定休日なので気をつけてね。",
        example_vi="Quán đó đóng cửa cố định vào thứ Tư nên bạn lưu ý nhé.",
        jlpt="N3",
        tier=2,
        frequency_score=8.22,
    ),
    FrequencyWordEntry(
        rank=370,
        word="在庫",
        reading="ざいこ",
        pos="noun",
        category="daily_life",
        meaning_vi="hàng tồn kho",
        synonyms_vi=['hàng có sẵn'],
        collocation_ja="在庫を確認する",
        collocation_vi="kiểm tra hàng trong kho",
        example_ja="あいにくこちらの商品の在庫は切れております。",
        example_vi="Rất tiếc sản phẩm mẫu này hiện tại trong kho đã hết hàng ạ.",
        jlpt="N3",
        tier=1,
        frequency_score=8.54,
    ),
    FrequencyWordEntry(
        rank=650,
        word="禁煙席",
        reading="きんえんせき",
        pos="noun",
        category="daily_life",
        meaning_vi="ghế không hút thuốc",
        synonyms_vi=['khu vực cấm thuốc'],
        collocation_ja="禁煙席を希望する",
        collocation_vi="chọn bàn không hút thuốc",
        example_ja="2名ですが、禁煙席は空いていますでしょうか？",
        example_vi="Chúng tôi đi 2 người, bàn khu vực không hút thuốc còn trống không ạ?",
        jlpt="N4",
        tier=2,
        frequency_score=8.10,
    ),
    FrequencyWordEntry(
        rank=680,
        word="試着",
        reading="しちゃく",
        pos="noun",
        category="daily_life",
        meaning_vi="mặc thử đồ",
        synonyms_vi=['thử quần áo'],
        collocation_ja="試着室に入る",
        collocation_vi="vào phòng thử đồ",
        example_ja="この服を着てみたいのですが、試着してもいいですか？",
        example_vi="Tôi muốn mặc thử chiếc áo này xem có vừa không được chứ ạ?",
        jlpt="N3",
        tier=2,
        frequency_score=8.05,
    ),
    FrequencyWordEntry(
        rank=590,
        word="配送料",
        reading="はいそうりょう",
        pos="noun",
        category="daily_life",
        meaning_vi="phí vận chuyển",
        synonyms_vi=['tiền ship', 'cước gửi'],
        collocation_ja="配送料が無料",
        collocation_vi="miễn phí vận chuyển",
        example_ja="5,000円以上のお買い上げで配送料が無料になります。",
        example_vi="Đơn hàng trên 5.000 Yên sẽ được miễn phí vận chuyển.",
        jlpt="N3",
        tier=2,
        frequency_score=8.20,
    ),
    FrequencyWordEntry(
        rank=540,
        word="返品",
        reading="へんぴん",
        pos="noun",
        category="daily_life",
        meaning_vi="đổi trả hàng",
        synonyms_vi=['trả lại đồ đã mua'],
        collocation_ja="商品を返品する",
        collocation_vi="đổi trả sản phẩm",
        example_ja="レシートがあれば1週間以内なら返品可能です。",
        example_vi="Nếu còn giữ hóa đơn mua hàng thì có thể đổi trả trong vòng 1 tuần.",
        jlpt="N3",
        tier=2,
        frequency_score=8.25,
    ),
    FrequencyWordEntry(
        rank=610,
        word="終電",
        reading="しゅうでん",
        pos="noun",
        category="daily_life",
        meaning_vi="chuyến tàu cuối",
        synonyms_vi=['chuyến xe chót'],
        collocation_ja="終電を逃す",
        collocation_vi="lỡ chuyến tàu cuối cùng",
        example_ja="終電に乗り遅れないように急いで駅に向かいました。",
        example_vi="Để không bị lỡ chuyến tàu cuối tôi đã vội vàng chạy ra ga.",
        jlpt="N3",
        tier=2,
        frequency_score=8.16,
    ),
    FrequencyWordEntry(
        rank=560,
        word="忘れ物",
        reading="わすれもの",
        pos="noun",
        category="daily_life",
        meaning_vi="đồ bỏ quên",
        synonyms_vi=['vật đánh rơi'],
        collocation_ja="忘れ物を届ける",
        collocation_vi="giao đồ bỏ quên cho quầy",
        example_ja="電車の中に傘を忘れ物をしてしまいました。",
        example_vi="Tôi lỡ bỏ quên cây dù ở trên tàu điện mất rồi.",
        jlpt="N4",
        tier=2,
        frequency_score=8.23,
    ),
    FrequencyWordEntry(
        rank=640,
        word="両替",
        reading="りょうがえ",
        pos="noun",
        category="daily_life",
        meaning_vi="đổi tiền",
        synonyms_vi=['đổi ngoại tệ', 'đổi tiền lẻ'],
        collocation_ja="外貨を両替する",
        collocation_vi="đổi ngoại tệ",
        example_ja="空港の両替所で日本円をベトナムドンに両替しました。",
        example_vi="Tôi đã đổi tiền Yên sang Đồng Việt Nam tại quầy đổi tiền ở sân bay.",
        jlpt="N4",
        tier=2,
        frequency_score=8.12,
    ),
]

# Combined High-Frequency Dataset (Dynamic load with static fallback)
_DATASET_FILE = Path(__file__).resolve().parent / "data" / "bccwj_frequency_3000.json"


def _load_dynamic_dataset() -> list[FrequencyWordEntry]:
    if _DATASET_FILE.exists():
        try:
            with open(_DATASET_FILE, "r", encoding="utf-8") as f:
                raw_data = json.load(f)
            entries = []
            for item in raw_data:
                entries.append(
                    FrequencyWordEntry(
                        rank=item["rank"],
                        word=item["word"],
                        reading=item["reading"],
                        pos=item["pos"],
                        category=item["category"],
                        meaning_vi=item["meaning_vi"],
                        synonyms_vi=item.get("synonyms_vi", [item["meaning_vi"]]),
                        collocation_ja=item.get("collocation_ja", ""),
                        collocation_vi=item.get("collocation_vi", ""),
                        example_ja=item.get("example_ja", ""),
                        example_vi=item.get("example_vi", ""),
                        jlpt=item.get("jlpt", "N4"),
                        tier=item.get("tier", 1),
                        frequency_score=item.get("frequency_score", 8.0),
                    )
                )
            if len(entries) >= 500:
                return entries
        except Exception:
            pass

    # Fallback to in-code 106 seed entries
    return (
        CORE_ACTION_VERBS
        + CORE_EMOTION_ADJECTIVES
        + CORE_ADVERBS_MIMETIC
        + CORE_WORKPLACE_WORDS
        + CORE_DAILY_LIFE_WORDS
    )


BCCWJ_FREQUENCY_WORDS: list[FrequencyWordEntry] = _load_dynamic_dataset()

CATEGORY_WORDS_MAP: dict[str, list[FrequencyWordEntry]] = {
    "action_verbs": [w for w in BCCWJ_FREQUENCY_WORDS if w.category == "action_verbs"],
    "emotions_adj": [w for w in BCCWJ_FREQUENCY_WORDS if w.category == "emotions_adj"],
    "adverbs_mimetic": [w for w in BCCWJ_FREQUENCY_WORDS if w.category == "adverbs_mimetic"],
    "workplace_biz": [w for w in BCCWJ_FREQUENCY_WORDS if w.category == "workplace_biz"],
    "daily_life": [w for w in BCCWJ_FREQUENCY_WORDS if w.category == "daily_life"],
}

TIER_WORDS_MAP: dict[int, list[FrequencyWordEntry]] = {
    1: [w for w in BCCWJ_FREQUENCY_WORDS if w.tier == 1],
    2: [w for w in BCCWJ_FREQUENCY_WORDS if w.tier == 2],
    3: [w for w in BCCWJ_FREQUENCY_WORDS if w.tier == 3],
}


def get_all_frequency_words() -> list[FrequencyWordEntry]:
    return BCCWJ_FREQUENCY_WORDS


def get_words_by_tier(tier: int) -> list[FrequencyWordEntry]:
    return TIER_WORDS_MAP.get(tier, [w for w in BCCWJ_FREQUENCY_WORDS if w.tier == tier])


def get_words_by_category(category: str) -> list[FrequencyWordEntry]:
    if not category or category == "all":
        return BCCWJ_FREQUENCY_WORDS
    return CATEGORY_WORDS_MAP.get(category, BCCWJ_FREQUENCY_WORDS)


def search_frequency_words(query: str) -> list[FrequencyWordEntry]:
    if not query.strip():
        return BCCWJ_FREQUENCY_WORDS
    q = query.lower().strip()
    return [
        w for w in BCCWJ_FREQUENCY_WORDS
        if q in w.word.lower()
        or q in w.reading.lower()
        or q in w.meaning_vi.lower()
        or any(q in syn.lower() for syn in w.synonyms_vi)
        or q in w.collocation_ja.lower()
        or q in w.example_ja.lower()
    ]

