"""Seed tasks repository for Survival Speaking & Speech Recovery (Deterministic Zero-Cost Fallback).

Contains rich banks of:
- SEED_CIRCUMLOCUTION_TASKS (Taboo Game: Quên từ -> diễn giải bản chất)
- SEED_SURVIVAL_SCENARIOS (Kịch bản cứu nguy khi đàm thoại bị nghẽn)
"""

from __future__ import annotations

from app.domains.survival.contracts import (
    CircumlocutionTask,
    RepairStrategy,
    SocialRelationship,
    SurvivalDifficulty,
    SurvivalHintTier,
    SurvivalScenarioTask,
    SurvivalVocabularyItem,
)

SEED_CIRCUMLOCUTION_TASKS: list[CircumlocutionTask] = [
    CircumlocutionTask(
        id="circ_microwave",
        target_word="電子レンジ",
        reading_hiragana="でんしれんじ",
        romaji="denshirenji",
        vietnamese_meaning="Lò vi sóng",
        category="Đồ gia dụng (家電)",
        genus="台所にある家電製品",
        differentia="電波を使って冷たい食べ物や飲み物を一瞬で温める箱",
        forbidden_words=["電子レンジ", "レンジ", "でんしれんじ", "microwave"],
        taboo_lemmas=["電子レンジ", "レンジ", "microwave"],
        difficulty=SurvivalDifficulty.EASY,
        time_limit_seconds=5,
        tier_hints=[
            SurvivalHintTier(tier=0, title="Không gợi ý", content="Tự diễn giải bằng tiếng Nhật trong 5 giây mà không dùng từ cấm."),
            SurvivalHintTier(tier=1, title="Chức năng (機能)", content="Thiết bị làm nóng thức ăn hoặc cơm nguội cực nhanh bằng sóng điện."),
            SurvivalHintTier(tier=2, title="Chủng loại & Vị trí (種類・場所)", content="Một đồ điện gia dụng (家電) đặt trong nhà bếp hoặc phòng nghỉ công ty."),
            SurvivalHintTier(tier=3, title="Khung câu mở đầu", content="何て言うか、台所にある機械で、冷たいご飯を______するための物です。"),
            SurvivalHintTier(tier=4, title="Câu mẫu chuẩn bản xứ", content="冷たくなった料理やご飯をチンして、すぐに温かくするための家電製品です。"),
        ],
        sample_explanations=[
            "冷たくなった料理やご飯を入れて、ボタンを押して温める台所の機械です。",
            "お弁当を温かくするときに使う四角い家電です。",
            "料理を作らない人でも、これがあればコンビニのお弁当を温められます。",
        ],
        suggested_vocabulary=[
            SurvivalVocabularyItem(term="温める", reading="あたためる", romaji="atatameru", meaning_vi="làm nóng, hâm nóng"),
            SurvivalVocabularyItem(term="家電製品", reading="かでんせいひん", romaji="kadenseihin", meaning_vi="thiết bị điện gia dụng"),
            SurvivalVocabularyItem(term="チンする", reading="ちんする", romaji="chinsuru", meaning_vi="quay lò vi sóng (tiếng lóng)"),
        ],
        semantic_anchors=["温める", "料理", "ご飯", "台所", "キッチン", "弁当", "チン", "家電"],
    ),
    CircumlocutionTask(
        id="circ_umbrella",
        target_word="折りたたみ傘",
        reading_hiragana="おりたたみがさ",
        romaji="oritatamigasa",
        vietnamese_meaning="Cây dù xếp / Ô gấp",
        category="Vật dụng hàng ngày (日用品)",
        genus="雨を防ぐ持ち運び用の道具",
        differentia="小さくたたんでカバンに入れられる雨具",
        forbidden_words=["折りたたみ傘", "折り畳み傘", "おりたたみがさ", "折りたたみ", "umbrella"],
        taboo_lemmas=["折りたたみ傘", "折り畳み傘", "おりたたみがさ", "折りたたみ"],
        difficulty=SurvivalDifficulty.EASY,
        time_limit_seconds=5,
        tier_hints=[
            SurvivalHintTier(tier=0, title="Không gợi ý", content="Tự diễn giải bằng tiếng Nhật trong 5 giây mà không dùng từ cấm."),
            SurvivalHintTier(tier=1, title="Chức năng (機能)", content="Che mưa khi ra ngoài đường, dùng xong có thể gấp gọn lại."),
            SurvivalHintTier(tier=2, title="Chủng loại & Kích thước", content="Đồ dùng che mưa nhỏ gọn, thường bỏ sẵn trong túi xách hoặc ba lô."),
            SurvivalHintTier(tier=3, title="Khung câu mở đầu", content="雨が降った時に頭の上にかざすやつで、小さくしてカバンに______です。"),
            SurvivalHintTier(tier=4, title="Câu mẫu chuẩn bản xứ", content="雨が降った時に濡れないようにさすもので、小さく丸めてカバンにしまえる道具です。"),
        ],
        sample_explanations=[
            "雨が降った時に濡れないようにさすもので、小さくたたんでカバンに入れられる道具です。",
            "普通の傘より小さくて、カバンの中にいつも入れておける雨具です。",
        ],
        suggested_vocabulary=[
            SurvivalVocabularyItem(term="濡れる", reading="ぬれる", romaji="nureru", meaning_vi="bị ướt"),
            SurvivalVocabularyItem(term="さす", reading="さす", romaji="sasu", meaning_vi="giương ô, che dù"),
            SurvivalVocabularyItem(term="持ち運ぶ", reading="もちはこぶ", romaji="mochihakobu", meaning_vi="mang theo bên mình"),
        ],
        semantic_anchors=["雨", "濡れない", "カバン", "さす", "小さい", "天気"],
    ),
    CircumlocutionTask(
        id="circ_warikan",
        target_word="割り勘",
        reading_hiragana="わりかん",
        romaji="warikan",
        vietnamese_meaning="Chia đều tiền ăn uống (Campuchia)",
        category="Văn hóa & Ăn uống (食文化・習慣)",
        genus="飲み会や食事の支払い方法",
        differentia="誰か一人が奢るのではなく全員で金額を等しく分けて払うこと",
        forbidden_words=["割り勘", "わりかん", "割りかん", "split bill"],
        taboo_lemmas=["割り勘", "わりかん", "割りかん"],
        difficulty=SurvivalDifficulty.MEDIUM,
        time_limit_seconds=5,
        tier_hints=[
            SurvivalHintTier(tier=0, title="Không gợi ý", content="Tự diễn giải bằng tiếng Nhật trong 5 giây."),
            SurvivalHintTier(tier=1, title="Bản chất (本質)", content="Cách thanh toán tiền khi đi ăn nhậu cùng bạn bè: chia đều theo đầu người."),
            SurvivalHintTier(tier=2, title="Bối cảnh (場面)", content="Sau khi ăn xong ở quán nhậu (居酒屋), không ai bao ai mà chia đều."),
            SurvivalHintTier(tier=3, title="Khung câu mở đầu", content="ご飯を食べた後に、一人が全部払うんじゃなくて、みんなで______することです。"),
            SurvivalHintTier(tier=4, title="Câu mẫu chuẩn bản xứ", content="食事代を誰か一人が奢るんじゃなくて、人数で同じ金額に分けて払うやり方です。"),
        ],
        sample_explanations=[
            "友達とご飯を食べた時に、合計の金額を人数で同じ分だけ分けて支払うことです。",
            "一人が奢るんじゃなくて、みんなで平らに払うことです。",
        ],
        suggested_vocabulary=[
            SurvivalVocabularyItem(term="奢る", reading="おごる", romaji="ogoru", meaning_vi="khao, bao tiền"),
            SurvivalVocabularyItem(term="分けて払う", reading="わけてはらう", romaji="wakete harau", meaning_vi="chia tiền ra trả"),
            SurvivalVocabularyItem(term="人数で", reading="にんずうで", romaji="ninzuu de", meaning_vi="chia theo số người"),
        ],
        semantic_anchors=["払う", "お金", "分ける", "奢る", "食事", "人数", "友達"],
    ),
    CircumlocutionTask(
        id="circ_teikiken",
        target_word="定期券",
        reading_hiragana="ていきけん",
        romaji="teikiken",
        vietnamese_meaning="Vé tháng tàu xe / Thẻ Commuter pass",
        category="Giao thông & Đời sống (交通)",
        genus="電車の乗車券",
        differentia="一定の期間、決まった区間を何回でも乗れるチケット",
        forbidden_words=["定期券", "定期", "ていきけん", "ていき", "pass"],
        taboo_lemmas=["定期券", "定期", "ていきけん"],
        difficulty=SurvivalDifficulty.MEDIUM,
        time_limit_seconds=5,
        tier_hints=[
            SurvivalHintTier(tier=0, title="Không gợi ý", content="Tự diễn giải trong 5 giây."),
            SurvivalHintTier(tier=1, title="Chức năng (機能)", content="Thẻ dùng để đi tàu/xe buýt giữa nhà và công ty/trường học không giới hạn số lần."),
            SurvivalHintTier(tier=2, title="Thời hạn (期間)", content="Thường mua theo 1 tháng, 3 tháng hoặc 6 tháng."),
            SurvivalHintTier(tier=3, title="Khung câu mở đầu", content="家から会社までの決まった駅の間を、1ヶ月間______乗れるカードです。"),
            SurvivalHintTier(tier=4, title="Câu mẫu chuẩn bản xứ", content="通勤や通学のために、決まった区間の電車に1ヶ月とか何回でも乗れるチケットです。"),
        ],
        sample_explanations=[
            "家から会社や学校までの間、決められた期間なら何回電車に乗ってもいいパスです。",
            "毎日会社に行く人が、改札でタッチする1ヶ月分の電車の切符です。",
        ],
        suggested_vocabulary=[
            SurvivalVocabularyItem(term="決まった区間", reading="きまったくかん", romaji="kimatta kukan", meaning_vi="đoạn đường / ga cố định"),
            SurvivalVocabularyItem(term="何回でも", reading="なんかいでも", romaji="nankai demo", meaning_vi="bao nhiêu lần cũng được"),
            SurvivalVocabularyItem(term="通勤する", reading="つうきんする", romaji="tsuukin suru", meaning_vi="đi làm hàng ngày"),
        ],
        semantic_anchors=["電車", "乗る", "駅", "会社", "学校", "何回も", "1ヶ月", "区間"],
    ),
    CircumlocutionTask(
        id="circ_futsukayoi",
        target_word="二日酔い",
        reading_hiragana="ふつかよい",
        romaji="futsukayoi",
        vietnamese_meaning="Say nguội / Cảm giác chếnh choáng sau khi say rượu hôm trước (Hangover)",
        category="Sức khỏe & Đời sống (健康・生活)",
        genus="身体の不調状態",
        differentia="前日にお酒を飲みすぎて翌朝に頭痛や吐き気がすること",
        forbidden_words=["二日酔い", "ふつかよい", "hangover"],
        taboo_lemmas=["二日酔い", "ふつかよい"],
        difficulty=SurvivalDifficulty.MEDIUM,
        time_limit_seconds=5,
        tier_hints=[
            SurvivalHintTier(tier=0, title="Không gợi ý", content="Tự diễn giải trong 5 giây."),
            SurvivalHintTier(tier=1, title="Nguyên nhân (原因)", content="Hôm qua uống quá nhiều bia rượu, sáng hôm sau bị đau đầu buồn nôn."),
            SurvivalHintTier(tier=2, title="Triệu chứng (症状)", content="Đầu ong ong, bụng khó chịu, không muốn ăn gì sau một đêm nhậu."),
            SurvivalHintTier(tier=3, title="Khung câu mở đầu", content="昨日の夜にお酒をたくさん飲みすぎて、次の日の朝に______状態です。"),
            SurvivalHintTier(tier=4, title="Câu mẫu chuẩn bản xứ", content="前の晩にお酒を飲みすぎたせいで、翌朝になっても頭が痛くて気持ち悪い状態のことです。"),
        ],
        sample_explanations=[
            "前の日にお酒を飲みすぎて、次の日の朝に頭がガンガンして起きられない状態のことです。",
            "ビールや日本酒を飲みすぎた次の日に、気分が悪くなることです。",
        ],
        suggested_vocabulary=[
            SurvivalVocabularyItem(term="お酒を飲みすぎる", reading="おさけをのみすぎる", romaji="osake o nomisugiru", meaning_vi="uống quá nhiều rượu"),
            SurvivalVocabularyItem(term="気持ち悪い", reading="きもちわるい", romaji="kimochi warui", meaning_vi="khó chịu, buồn nôn"),
            SurvivalVocabularyItem(term="次の日の朝", reading="つぎのひのあさ", romaji="tsugi no hi no asa", meaning_vi="sáng hôm sau"),
        ],
        semantic_anchors=["お酒", "飲む", "次の日", "朝", "頭痛", "頭が痛い", "気持ち悪い"],
    ),
    CircumlocutionTask(
        id="circ_shuden",
        target_word="終電",
        reading_hiragana="しゅうでん",
        romaji="shuuden",
        vietnamese_meaning="Chuyến tàu cuối cùng trong đêm (Last train)",
        category="Giao thông & Đời sống đêm (交通・夜)",
        genus="電車の運行便",
        differentia="その日の夜に走る一番最後の電車で、逃すと帰れなくなるもの",
        forbidden_words=["終電", "しゅうでん", "最終電車", "last train"],
        taboo_lemmas=["終電", "しゅうでん", "最終電車"],
        difficulty=SurvivalDifficulty.EASY,
        time_limit_seconds=5,
        tier_hints=[
            SurvivalHintTier(tier=0, title="Không gợi ý", content="Tự diễn giải trong 5 giây."),
            SurvivalHintTier(tier=1, title="Tính chất (性質)", content="Chuyến tàu cuối cùng trong ngày, nếu trễ thì phải đi taxi hoặc ở quán net."),
            SurvivalHintTier(tier=2, title="Bối cảnh (場面)", content="Khi đi nhậu đêm, mọi người hay nhìn đồng hồ và giục: Sắp đến giờ rồi kìa!"),
            SurvivalHintTier(tier=3, title="Khung câu mở đầu", content="夜遅くまで飲んでいる時に、これに乗らないと家に______一番最後の電車です。"),
            SurvivalHintTier(tier=4, title="Câu mẫu chuẩn bản xứ", content="その日の夜に走る一番最後の電車で、乗り遅れたら朝まで帰れなくなるやつです。"),
        ],
        sample_explanations=[
            "その日走る一番最後の電車で、逃すとタクシーで帰るか漫画喫茶に泊まるしかなくなります。",
            "夜遅くの飲み会で、みんなが慌てて駅に走って乗る最後の電車です。",
        ],
        suggested_vocabulary=[
            SurvivalVocabularyItem(term="一番最後", reading="いちばんさいご", romaji="ichiban saigo", meaning_vi="chuyến cuối cùng"),
            SurvivalVocabularyItem(term="乗り遅れる", reading="のりおくれる", romaji="noriokureru", meaning_vi="lỡ tàu, trễ chuyến"),
            SurvivalVocabularyItem(term="帰れなくなる", reading="かえれなくなる", romaji="kaerenaku naru", meaning_vi="không về được nhà"),
        ],
        semantic_anchors=["電車", "夜", "最後", "乗り遅れる", "帰る", "駅", "深夜"],
    ),
]

SEED_SURVIVAL_SCENARIOS: list[SurvivalScenarioTask] = [
    SurvivalScenarioTask(
        id="scen_boss_sudden_question",
        context="workplace_meeting",
        context_title_vi="Cuộc họp bất ngờ với cấp trên (Workplace)",
        relationship=SocialRelationship.BUSINESS,
        problem_description_vi="Trong cuộc họp, Trưởng phòng bất ngờ chỉ định bạn phát biểu quan điểm về dự án mới. Bạn cần 3-5 giây để xâu chuỗi suy nghĩ.",
        npc_utterance_ja="田中さん、今回のマーケティング戦略の改善案について、何か意見はある？",
        npc_utterance_reading="たなかさん、こんかいのまーけてぃんぐせんりゃくのかいぜんあんについて、なにかいけんはある？",
        recommended_strategy=RepairStrategy.BUYING_TIME,
        suggested_repair_phrases=[
            "そうですね…少々考えをまとめさせていただきますので、少しお時間いただけますでしょうか。",
            "ええと、非常に重要なポイントですね。少し整理させてください。",
            "はい、そうですね…私の考えといたしましては…",
        ],
        difficulty=SurvivalDifficulty.MEDIUM,
        time_limit_seconds=5,
        tier_hints=[
            SurvivalHintTier(tier=0, title="Không gợi ý", content="Phản xạ câu giờ lịch sự ngay lập tức trong 5 giây."),
            SurvivalHintTier(tier=1, title="Chiến lược", content="Dùng cụm đệm xin phép sắp xếp lại ý nghĩ thay vì im bặt."),
            SurvivalHintTier(tier=2, title="Cụm từ cứu cánh", content="そうですね…少々考えをまとめさせていただきます..."),
            SurvivalHintTier(tier=3, title="Khung câu ứng biến", content="そうですね…ええと、私の考えといたしましては、少し______させていただけますでしょうか。"),
            SurvivalHintTier(tier=4, title="Câu mẫu chuẩn bản xứ", content="そうですね…非常に興味深い点だと思います。少し考えをまとめさせていただいてもよろしいでしょうか。"),
        ],
        suggested_vocabulary=[
            SurvivalVocabularyItem(term="考えをまとめる", reading="かんがえをまとめる", romaji="kangae o matomeru", meaning_vi="sắp xếp lại suy nghĩ"),
            SurvivalVocabularyItem(term="少々お時間をいただく", reading="しょうしょうおじかんをいただく", romaji="shoushou ojikan o itadaku", meaning_vi="xin một chút thời gian"),
            SurvivalVocabularyItem(term="〜といたしましては", reading="〜といたしましては", romaji="~ to itashimashite wa", meaning_vi="về phía tôi thì... (keigo)"),
        ],
    ),
    SurvivalScenarioTask(
        id="scen_client_speaking_too_fast",
        context="business_phone",
        context_title_vi="Điện thoại đối tác nói quá nhanh (Business Call)",
        relationship=SocialRelationship.BUSINESS,
        problem_description_vi="Khách hàng nói một tràng dài rất nhanh qua điện thoại và bạn không nghe kịp các con số cũng như thời hạn bàn giao.",
        npc_utterance_ja="例の納品スケジュールの件ですが、来週火曜の午前中までに修正データをサーバーにアップロードいただけますか？",
        npc_utterance_reading="れいののうひんすけじゅーるのけんですが、らいしゅうかようのごぜんちゅうまでにしゅうせいデータをさーばーにあっぷろーどいただけますか？",
        recommended_strategy=RepairStrategy.ASKING_REPETITION,
        suggested_repair_phrases=[
            "大変恐れ入りますが、お電話が少し遠いようでして、もう一度お願いできますでしょうか。",
            "申し訳ございません、聞き取れませんでしたので、もう一度ゆっくりおっしゃっていただけますか。",
            "恐縮ですが、納期の日時をもう一度確認させていただけますでしょうか。",
        ],
        difficulty=SurvivalDifficulty.HARD,
        time_limit_seconds=5,
        tier_hints=[
            SurvivalHintTier(tier=0, title="Không gợi ý", content="Phản xạ xin nhắc lại bằng Keigo chuẩn mực."),
            SurvivalHintTier(tier=1, title="Chiến lược", content="Viện cớ đường truyền điện thoại không rõ (電話が遠い) để xin đối tác nói chậm lại."),
            SurvivalHintTier(tier=2, title="Cụm từ cứu cánh", content="大変恐れ入りますが、もう一度おっしゃっていただけますか？"),
            SurvivalHintTier(tier=3, title="Khung câu ứng biến", content="申し訳ございません、少しお声が聞き取りにくかったので、もう一度______でしょうか。"),
            SurvivalHintTier(tier=4, title="Câu mẫu chuẩn bản xứ", content="大変恐れ入ります、電波の状態が少し悪いようでして、もう一度ゆっくりお願いできますでしょうか。"),
        ],
        suggested_vocabulary=[
            SurvivalVocabularyItem(term="大変恐れ入りますが", reading="たいへんおそれいりますが", romaji="taihen osoreirimasu ga", meaning_vi="vô cùng xin lỗi nhưng mà..."),
            SurvivalVocabularyItem(term="お電話が遠い", reading="おでんわがとおい", romaji="odenwa ga tooi", meaning_vi="tiếng điện thoại bị nhỏ/khó nghe"),
            SurvivalVocabularyItem(term="おっしゃる", reading="おっしゃる", romaji="ossharu", meaning_vi="nói (tôn kính ngữ của 言う)"),
        ],
    ),
    SurvivalScenarioTask(
        id="scen_friend_fast_slang",
        context="casual_chat",
        context_title_vi="Bạn bè nói tiếng lóng quá lướt (Casual Chat)",
        relationship=SocialRelationship.CASUAL,
        problem_description_vi="Người bạn Nhật nói lướt một câu tiếng lóng bạn chưa nghe bao giờ. Bạn muốn hỏi lại tự nhiên không bị gượng gạo.",
        npc_utterance_ja="昨日のイベント、マジでエグかったよね！あんなの見たことないわ。",
        npc_utterance_reading="きのうのいべんと、まじでえぐかったよね！あんなのみたことないわ。",
        recommended_strategy=RepairStrategy.ASKING_CLARIFICATION,
        suggested_repair_phrases=[
            "え、ごめん、エグいってどういう意味？いい意味？",
            "ちょっと聞き取れなかった！もう一回言って？",
            "え、それってすごかったってこと？",
        ],
        difficulty=SurvivalDifficulty.EASY,
        time_limit_seconds=5,
        tier_hints=[
            SurvivalHintTier(tier=0, title="Không gợi ý", content="Phản xạ hỏi lại bạn bè tự nhiên."),
            SurvivalHintTier(tier=1, title="Chiến lược", content="Hỏi thẳng nghĩa từ đó theo kiểu bạn bè thân mật."),
            SurvivalHintTier(tier=2, title="Cụm từ cứu cánh", content="え、それってどういうこと？"),
            SurvivalHintTier(tier=3, title="Khung câu ứng biến", content="ごめん、今の単語よくわかんなかったんだけど、______って意味？"),
            SurvivalHintTier(tier=4, title="Câu mẫu chuẩn bản xứ", content="え、ごめん、エグいってどういう意味？めっちゃヤバかったってこと？"),
        ],
        suggested_vocabulary=[
            SurvivalVocabularyItem(term="どういう意味？", reading="どういういみ？", romaji="dou iu imi?", meaning_vi="nghĩa là sao vậy?"),
            SurvivalVocabularyItem(term="聞き取れなかった", reading="ききとれなかった", romaji="kikitorenakatta", meaning_vi="tớ chưa nghe kịp"),
        ],
    ),
    SurvivalScenarioTask(
        id="scen_self_repair_particle",
        context="restaurant_order",
        context_title_vi="Lỡ nói nhầm trong quán ăn (Self-Correction)",
        relationship=SocialRelationship.POLITE,
        problem_description_vi="Bạn gọi món nhưng lỡ nói nhầm số lượng '1 người' thay vì '1 phần cơm', bạn cần đính chính tức thì.",
        npc_utterance_ja="ご注文はお決まりでしょうか？",
        npc_utterance_reading="ごちゅうもんはおきまりでしょうか？",
        recommended_strategy=RepairStrategy.SELF_CORRECTION,
        suggested_repair_phrases=[
            "ラーメンを一人…あ、違います、一杯お願いします。",
            "あ、すみません、言い直しますと、ラーメン一つでお願いします。",
            "あ、間違えました、ラーメン一つください。",
        ],
        difficulty=SurvivalDifficulty.EASY,
        time_limit_seconds=5,
        tier_hints=[
            SurvivalHintTier(tier=0, title="Không gợi ý", content="Phản xạ tự sửa lời nói."),
            SurvivalHintTier(tier=1, title="Chiến lược", content="Dùng 'あ、違います' hoặc 'あ、間違えました' rồi nói lại từ đúng."),
            SurvivalHintTier(tier=2, title="Cụm từ cứu cánh", content="あ、違います、〜じゃなくて〜"),
            SurvivalHintTier(tier=3, title="Khung câu ứng biến", content="あ、すみません、間違えました。______をお願いします。"),
            SurvivalHintTier(tier=4, title="Câu mẫu chuẩn bản xứ", content="ラーメン一人…あ、違います、一杯お願いします！"),
        ],
        suggested_vocabulary=[
            SurvivalVocabularyItem(term="あ、違います", reading="あ、ちがいます", romaji="a, chigaimasu", meaning_vi="à, không phải, nhầm ạ"),
            SurvivalVocabularyItem(term="言い直すと", reading="いいなおすと", romaji="iinaosu to", meaning_vi="nói lại cho đúng thì là..."),
        ],
    ),
]

SURVIVAL_TOPICS: list[dict[str, str]] = [
    {"id": "all", "label_vi": "Tất cả chủ đề", "label_ja": "すべて", "icon": "Sparkles"},
    {"id": "kitchen", "label_vi": "Đồ gia dụng & Bếp", "label_ja": "家電・キッチン", "icon": "Coffee"},
    {"id": "food", "label_vi": "Ẩm thực & Quán nhậu", "label_ja": "グルメ・居酒屋", "icon": "Utensils"},
    {"id": "workplace", "label_vi": "Công sở & Phỏng vấn", "label_ja": "ビジネス・面接", "icon": "Briefcase"},
    {"id": "transport", "label_vi": "Giao thông & Đi lại", "label_ja": "交通・電車", "icon": "Plane"},
    {"id": "daily", "label_vi": "Đời sống thường ngày", "label_ja": "日常生活", "icon": "ShoppingBag"},
]
