import type { IconName } from '../components/icons/Icon'

export interface GuideItem {
  id: string
  category: 'workflow' | 'practice' | 'intelligence' | 'library' | 'zen' | 'settings'
  title: string
  subtitle: string
  route?: string
  icon: IconName
  badge: string
  badgeTone: 'accent' | 'ai' | 'register' | 'success' | 'warning' | 'neutral' | 'grammar' | 'vocabulary'
  purpose: string
  whenToUse: string
  howToUse: string[]
  proTips: string[]
  pitfalls?: string[]
  synergy: string
}

export const GUIDE_ITEMS: GuideItem[] = [
  /* =========================================================================
   * CATEGORY: WORKFLOW (Hành Trình Học Chuẩn Mẫu)
   * ========================================================================= */
  {
    id: 'daily-workflow',
    category: 'workflow',
    title: 'Hành Trình Học Mẫu 5 Bước Hằng Ngày (Daily Playbook)',
    subtitle: 'Khung phương pháp khoa học 30–45 phút mỗi ngày giúp tiến bộ vượt bậc mà không quá tải.',
    route: '/',
    icon: 'target',
    badge: 'Khuyên Dùng',
    badgeTone: 'accent',
    purpose: 'Cung cấp luồng học khép kín từ nhận diện mục tiêu, thực hành trọng tâm, sửa lỗi sâu, thu thập từ vựng cho đến sát hạch định kỳ.',
    whenToUse: 'Bắt đầu mỗi buổi học tiếng Nhật hằng ngày.',
    howToUse: [
      'Bước 1: Bảng Điều Khiển (/) — Điểm danh giữ Streak, xem nhiệm vụ ngày và bài tập AI đề xuất.',
      'Bước 2: Trí Tuệ Viết (/intelligence) — Kiểm tra Kế hoạch 70/20/10 để biết hôm nay cần ưu tiên khắc phục lỗi nào.',
      'Bước 3: Thực hành Luyện Tập (/practice) hoặc Rewrite Lab (/rewrite-lab) — Giải quyết dứt điểm các bài tập trong kế hoạch.',
      'Bước 4: Sổ Từ Vựng (/vocabulary) & Trí Nhớ AI (/memory) — Ôn tập lại từ vựng hay vừa được AI trích xuất tự động.',
      'Bước 5: Đấu Trường Boss (/intelligence) — 1–2 lần mỗi tuần, làm bài sát hạch không trợ giúp để chứng nhận Master.',
    ],
    proTips: [
      'Duy trì tối thiểu 3 bài viết/ngày để giữ thuật toán thích ứng luôn được cập nhật dữ liệu mới nhất.',
      'Bật âm thanh Zen Soundscape và Pomodoro Zen Tea Timer để duy trì trạng thái tập trung sâu.',
    ],
    synergy: 'Dữ liệu từ mọi bài tập bạn hoàn thành sẽ tự động chảy về Bảng Điều Khiển và Lộ Trình học.',
  },
  {
    id: 'streak-gamification',
    category: 'workflow',
    title: 'Hệ Thống Gamification, Streak & Nhiệm Vụ Ngày',
    subtitle: 'Tạo động lực luyện viết đều đặn thông qua XP, cấp độ, chuỗi ngày và nhiệm vụ hàng ngày.',
    route: '/',
    icon: 'flame',
    badge: 'Động Lực',
    badgeTone: 'warning',
    purpose: 'Biến việc luyện viết tiếng Nhật thành thói quen không thể bỏ dở với hệ thống tính điểm XP minh bạch và bảo lưu chuỗi ngày.',
    whenToUse: 'Theo dõi mỗi khi hoàn thành bài tập hoặc muốn duy trì chuỗi học liên tục.',
    howToUse: [
      'Hoàn thành ít nhất 1 bài viết mỗi ngày trước 23:59 (theo múi giờ địa phương) để giữ Streak.',
      'Thực hiện Nhiệm vụ AI hằng ngày (Daily Mission) hiển thị trên Bảng điều khiển để nhận lượng XP thưởng lớn.',
      'Tích lũy XP để tăng cấp độ (Level) từ Tập Sự (N5) lên Bậc Thầy Viết Lách (N1).',
    ],
    proTips: [
      'Nếu bận rộn, chỉ cần hoàn thành 1 câu dịch ngắn trong Luyện Tập (2 phút) là chuỗi Streak của bạn đã được bảo vệ an toàn.',
    ],
    synergy: 'XP và Streak liên kết trực tiếp với tiến trình hoàn thành mục tiêu trong Lộ Trình (/journey).',
  },

  /* =========================================================================
   * CATEGORY: PRACTICE (Hệ Thống 7 Phòng Luyện Viết)
   * ========================================================================= */
  {
    id: 'practice-translation',
    category: 'practice',
    title: 'Luyện Tập Dịch Câu (Vietnamese → Japanese Translation)',
    subtitle: 'Thực hành dịch câu Việt – Nhật có AI chấm điểm chi tiết 6 chiều và trợ giảng Socratic.',
    route: '/practice',
    icon: 'practice',
    badge: 'Cốt Lõi',
    badgeTone: 'grammar',
    purpose: 'Rèn cấu trúc ngữ pháp, trợ từ, từ vựng và chuyển ngữ chính xác từ suy nghĩ tiếng Việt sang câu tiếng Nhật chuẩn mực.',
    whenToUse: 'Hằng ngày; khi mới bắt đầu buổi học hoặc cần ôn luyện các mẫu ngữ pháp theo JLPT N5–N1.',
    howToUse: [
      'Đọc kỹ đề bài tiếng Việt và các yêu cầu về thể câu (Lịch sự Desu/Masu, Thân mật, hoặc Thương mại).',
      'Tự viết câu tiếng Nhật hoàn chỉnh vào ô soạn thảo.',
      'Nếu bị tắc ý, nhấp nút "Gợi ý" để mở Thang gợi ý 3 tầng: Tầng 1 (Từ khóa) → Tầng 2 (Khung cấu trúc) → Tầng 3 (Dàn ý câu).',
      'Bấm "Nộp bài" để nhận phân tích 5 tầng AI: Ngữ nghĩa, Ngữ pháp, Độ tự nhiên, Sửa lỗi và Giải thích chi tiết.',
    ],
    proTips: [
      'Hạn chế bấm nút "Xem đáp án" nếu chưa thử tự viết ít nhất 2 lần. Não bộ chỉ ghi nhớ sâu khi tự thân suy nghĩ.',
      'Sau khi nhận điểm, đọc kỹ mục "Từ vựng được phát hiện" để lưu các cụm từ hay vào sổ tay.',
    ],
    pitfalls: ['Không nên dịch từng từ theo ngữ pháp tiếng Việt (Word-by-word) mà hãy hình dung cấu trúc chuẩn của người Nhật.'],
    synergy: 'Các lỗi sai tại đây sẽ tự động được thu nạp vào Studio Trí Tuệ Viết (/intelligence) để lên lịch ôn lại.',
  },
  {
    id: 'rewrite-lab',
    category: 'practice',
    title: 'Phòng Sửa Câu (Self-Correction & Rewrite Lab)',
    subtitle: 'Tự nhận diện lỗi, đối chiếu 4 biến thể và khám phá 6 phong cách biến đổi câu tiếng Nhật.',
    route: '/rewrite-lab',
    icon: 'sparkles',
    badge: 'Nâng Cao',
    badgeTone: 'accent',
    purpose: 'Giúp người học chuyển từ trạng thái "biết câu sai nhờ người khác sửa" sang "tự phát hiện và tự nâng cấp câu viết của chính mình".',
    whenToUse: 'Khi vừa viết xong một câu tiếng Nhật còn vụng về, hoặc khi muốn luyện khả năng linh hoạt biến hóa phong cách.',
    howToUse: [
      '1. Thang tự sửa 6 nấc: Đọc câu gợi ý của AI, lần theo từng nấc manh mối (Vị trí lỗi → Loại lỗi → Gợi ý hướng sửa) để tự sửa lại.',
      '2. Đối chiếu 4 biến thể: So sánh Câu gốc vs Bản sửa tối thiểu vs Bản tự nhiên vs Bản kính ngữ, sau đó bắt buộc viết Câu tổng hợp.',
      '3. 6 Chế độ viết lại (Rewrite Modes): Khám phá cùng một câu dưới 6 góc độ: Trang trọng Kính ngữ, Súc tích, Tinh tế, Học thuật, Giàu cảm xúc, Thân mật.',
      '4. Chuyển giao bối cảnh mới (Transfer Check): Áp dụng cấu trúc vừa học vào một tình huống hoàn toàn mới để kiểm tra độ hiểu sâu.',
    ],
    proTips: [
      'Tận dụng công cụ So sánh khác biệt ngữ pháp (Linguistic Diff) để thấy rõ từng trợ từ hoặc đuôi câu được người Nhật thay đổi ra sao.',
    ],
    synergy: 'Thực hành tại Rewrite Lab giúp tăng điểm Chuyển di bối cảnh (Contextual Transfer) trong Đấu trường Boss.',
  },
  {
    id: 'free-writing',
    category: 'practice',
    title: 'Viết Tự Do (Free Writing & Discourse Studio)',
    subtitle: 'Luyện viết đoạn văn dài, nhật ký, bài luận mở có AI chấm điểm mạch lạc và bố cục thông tin.',
    route: '/free-writing',
    icon: 'write',
    badge: 'Sáng Tạo',
    badgeTone: 'register',
    purpose: 'Phát triển năng lực viết văn bản dài (100–500 ký tự) với kết nối câu mượt mà, liên kết đoạn (Discourse Cohesion) chặt chẽ.',
    whenToUse: 'Khi muốn luyện viết bài luận JLPT N2/N1, viết nhật ký, chia sẻ quan điểm, hoặc viết email tự do.',
    howToUse: [
      'Chọn chủ đề gợi ý hoặc tự đặt đề tài yêu thích.',
      'Sử dụng bộ đếm ký tự và thời gian để kiểm soát dung lượng bài viết.',
      'Nộp bài để nhận báo cáo phân tích mạch lạc đoạn văn: Sử dụng liên từ (Soshite, Shikashi, Soreyue), tính nhất quán của văn phong, và cách ngắt đoạn.',
    ],
    proTips: [
      'Chia bài viết thành cấu trúc 3 phần rõ ràng: Mở bài (Nêu vấn đề) → Thân bài (Lý do/Dẫn chứng) → Kết luận (Quan điểm).',
    ],
    synergy: 'Cung cấp bằng chứng viết tự do (Criterion 4) bắt buộc để đạt chứng nhận Master trong Đấu trường Boss.',
  },
  {
    id: 'scenario-missions',
    category: 'practice',
    title: 'Nhiệm Vụ Tình Huống Thực Tế (Real-World Writing Missions)',
    subtitle: '23 nghiệp vụ viết tiếng Nhật thực tế trong công sở, thương mại, học thuật và đời sống.',
    route: '/scenario',
    icon: 'briefcase',
    badge: 'Ứng Dụng',
    badgeTone: 'success',
    purpose: 'Chuẩn bị cho người học khả năng viết giải quyết công việc thực tế (Email xin lỗi đối tác, Báo cáo sự cố Hou-Ren-So, Đơn xin nghỉ phép, Thư khiếu nại).',
    whenToUse: 'Khi chuẩn bị đi làm công ty Nhật, phỏng vấn, hoặc muốn rèn kỹ năng giao tiếp công sở quy chuẩn.',
    howToUse: [
      'Chọn 1 trong 4 danh mục: Doanh nghiệp B2B, Học thuật, Đời sống, hoặc Nghiệp vụ xã hội.',
      'Chọn Chế độ nhập vai: Song ngữ (Bilingual), 100% Tiếng Nhật (Chuẩn immersion), hoặc Mô phỏng Hộp thư đến (In-Basket Simulation).',
      'Tuân thủ bảng Ràng buộc bắt buộc (Required Constraints) và tránh các Điều cấm kỵ (Forbidden Patterns).',
      'Nhận đánh giá 10 chiều năng lực thực tế sau khi nộp bài.',
    ],
    proTips: [
      'Khi viết email công việc, luôn bắt đầu bằng câu chào tiêu chuẩn (Osewa ni natte orimasu) và kết thúc bằng câu chào trân trọng.',
    ],
    synergy: 'Kết quả nhiệm vụ có thể chuyển tiếp trực tiếp sang phòng Mô Phỏng Hội Thoại để tiếp tục đối thoại với đối tác.',
  },
  {
    id: 'simulation-chat',
    category: 'practice',
    title: 'Mô Phỏng Hội Thoại AI (Interactive Writing Simulation)',
    subtitle: 'Nhập vai đối thoại nhiều lượt theo thời gian thực cùng các nhân vật AI Persona sinh động.',
    route: '/simulation',
    icon: 'simulation',
    badge: 'Tương Tác',
    badgeTone: 'accent',
    purpose: 'Rèn luyện phản xạ đối đáp tiếng Nhật tức thì trong các tình huống đàm phán, phỏng vấn, hoặc xử lý tình huống khẩn cấp.',
    whenToUse: 'Khi muốn trải nghiệm cảm giác giao tiếp thực tế với đối tác, đồng nghiệp hoặc cấp trên người Nhật.',
    howToUse: [
      'Chọn kịch bản mô phỏng (ví dụ: Giải trình tiến độ với Trưởng phòng Yamada, Khiếu nại giao dịch với bộ phận CSKH).',
      'Đọc tin nhắn của nhân vật AI và gõ phản hồi của bạn bằng tiếng Nhật.',
      'Theo dõi Biểu đồ cảm xúc & Mức độ hài lòng của Persona qua từng lượt đối thoại.',
      'Kết thúc buổi mô phỏng để nhận bản tổng kết kỹ năng ứng biến và chỉ số thành công.',
    ],
    proTips: [
      'Chú ý quan sát thái độ của đối phương để điều chỉnh mức độ trang trọng (Keigo) phù hợp.',
    ],
    synergy: 'Rèn luyện khả năng Thích ứng ngữ cảnh (Contextual Adaptability) trong mô hình làm chủ 8 chiều.',
  },
  {
    id: 'challenge-mode',
    category: 'practice',
    title: 'Thử Thách Phản Xạ Viết (Writing Challenges)',
    subtitle: 'Rèn tốc độ và sự chính xác dưới áp lực đồng hồ đếm ngược với tiêu chuẩn nghiêm ngặt.',
    route: '/challenge',
    icon: 'challenge',
    badge: 'Tốc Độ',
    badgeTone: 'warning',
    purpose: 'Phá vỡ thói quen chần chừ, rèn phản xạ viết tiếng Nhật nhanh và chính xác dưới áp lực thời gian tương tự các kỳ thi JLPT.',
    whenToUse: 'Khi muốn tự kiểm tra tốc độ viết hoặc tham gia thử thách lấy thưởng XP hàng ngày.',
    howToUse: [
      'Chọn thời lượng thử thách (3 phút, 5 phút, hoặc 10 phút).',
      'Tập trung cao độ viết câu chuẩn xác trước khi đồng hồ đếm ngược về 0.',
      'Đạt điểm chuẩn tối thiểu để nhận huy hiệu chiến thắng và phần thưởng XP danh dự.',
    ],
    proTips: [
      'Dành 30 giây cuối cùng để quét nhanh lại các lỗi trợ từ kinh điển (は/が, に/で, を).',
    ],
    synergy: 'Thử thách rèn luyện tâm lý vững vàng trước khi bước vào Đấu Trường Boss.',
  },
  {
    id: 'kanji-studio',
    category: 'practice',
    title: 'Luyện Chữ Hán Kanji (Kanji Stroke & Calligraphy Studio)',
    subtitle: 'Bảng vẽ số nhận diện nét bút thuận, tra cứu Hán Việt, âm On/Kun, bộ thủ và 2.136 chữ Jouyou.',
    route: '/kanji',
    icon: 'write',
    badge: 'Nền Tảng',
    badgeTone: 'neutral',
    purpose: 'Củng cố nền tảng chữ Hán, nhớ mặt chữ sâu hơn qua việc trực tiếp viết đúng thứ tự nét bút (Stroke Order) thay vì chỉ gõ bàn phím.',
    whenToUse: 'Khi gặp từ mới chứa chữ Kanji khó nhớ, hoặc muốn rèn nét chữ đẹp và đúng chuẩn thư pháp.',
    howToUse: [
      'Tra cứu chữ Kanji theo chữ Hán, âm Hán Việt hoặc cấp độ JLPT (N5 → N1).',
      'Xem hoạt họa thứ tự nét bút thuận từng nét một.',
      'Sử dụng chuột hoặc bút cảm ứng vẽ trực tiếp trên Bảng vẽ số để hệ thống chấm độ chính xác từng nét.',
      'Học thêm các từ ghép phổ biến và bộ thủ cấu thành chữ Hán đó.',
    ],
    proTips: [
      'Quy tắc vàng viết Kanji: Trái trước phải sau, trên trước dưới sau, ngang trước sổ sau, ngoài trước trong sau rồi mới đóng.',
    ],
    synergy: 'Hiểu rõ chữ Hán giúp ghi nhớ từ vựng trong Sổ Từ Vựng (/vocabulary) nhanh gấp 3 lần.',
  },

  /* =========================================================================
   * CATEGORY: INTELLIGENCE (Đầu Não Trí Tuệ & Đấu Trường Boss)
   * ========================================================================= */
  {
    id: 'boss-assessment',
    category: 'intelligence',
    title: 'Đấu Trường Đánh Giá Boss (Boss Writing Arena)',
    subtitle: 'Sát hạch năng lực viết thực chất trong môi trường không gợi ý, không từ điển dịch ngữ.',
    route: '/intelligence',
    icon: 'trophy',
    badge: 'Tối Cao',
    badgeTone: 'accent',
    purpose: 'Thước đo tối thượng chứng minh người học có thực sự viết được tiếng Nhật trong đời thực hay không, tránh tình trạng điểm ảo do dựa dẫm vào gợi ý.',
    whenToUse: 'Định kỳ 1–2 lần/tuần hoặc sau khi hoàn thành 1 chu kỳ học tập để nâng hạng Master.',
    howToUse: [
      'Vào Trí Tuệ Viết (/intelligence) → Tab "🏆 Làm Chủ & Boss Assessment" → Bấm "Bước Vào Đấu Trường Boss".',
      'Đọc kỹ tình huống thực tế, đối tượng giao tiếp, bảng ràng buộc và cạm bẫy tâm lý (Adversarial Traps).',
      'Viết bài hoàn toàn tự thân trong thời gian giới hạn (15–30 phút). Tuyệt đối không có nút gợi ý hay công cụ dịch trợ giúp.',
      'Nộp bài để nhận Hồ sơ thẩm định 8 chiều và nghiên cứu 3 Tầng Văn Bản Mẫu (*Minimal Fix*, *Native Polish*, *Business Keigo*).',
    ],
    proTips: [
      'Đọc kỹ mục "Điều cấm kỵ" trước khi đặt bút để tránh bị trừ điểm oan.',
      'Nếu bị chẩn đoán có kỹ năng Thoái trào (Regressed), hãy quay lại Lộ trình 70/20/10 để luyện bài phục hồi ngay.',
    ],
    pitfalls: ['Không nên tra từ điển ngoài trong lúc làm bài Boss vì mục tiêu là kiểm tra trí nhớ nội tại của bạn.'],
    synergy: 'Vượt qua bài Boss là điều kiện tiên quyết (Criterion 5) để mở khóa chứng nhận Master 8 chiều.',
  },
  {
    id: 'mastery-5-criteria',
    category: 'intelligence',
    title: 'Mô Hình 8 Chiều & 5 Tiêu Chuẩn Chứng Nhận Master',
    subtitle: 'Mô hình đánh giá 8 chiều năng lực độc lập với 5 tiêu chuẩn bằng chứng nghiêm ngặt.',
    route: '/intelligence',
    icon: 'target',
    badge: 'Thẩm Định',
    badgeTone: 'grammar',
    purpose: 'Đảm bảo một kỹ năng chỉ được công nhận là "Làm Chủ" (Mastered) khi có đầy đủ bằng chứng khoa học, không quy đổi cào bằng về một con số chung chung.',
    whenToUse: 'Xem xét bất cứ lúc nào trên Ma trận 8 chiều năng lực tại trang Trí Tuệ Viết.',
    howToUse: [
      'Bấm nút "Xem 5 Tiêu Chí Master ℹ" dưới mỗi thẻ kỹ năng để kiểm tra tiến độ của 5 tiêu chuẩn:',
      '• Tiêu chuẩn 1: Sử dụng đúng lặp lại (≥ 3 lần).',
      '• Tiêu chuẩn 2: Ghi nhớ có độ trễ (Khoảng cách không mắc lỗi ≥ 3–5 ngày).',
      '• Tiêu chuẩn 3: Chuyển di bối cảnh mới (Đúng trên ≥ 3 bối cảnh khác nhau).',
      '• Tiêu chuẩn 4: Bằng chứng viết tự do (Tỷ lệ đúng ≥ 50% trong Free Writing).',
      '• Tiêu chuẩn 5: Bằng chứng thực tế / Boss (Đạt chuẩn trong nhiệm vụ thực tế hoặc Đấu trường Boss).',
    ],
    proTips: [
      'Kỹ năng có thể bị "Thoái trào" (Regressed) nếu bạn tái phát lỗi sau khi đã đạt Master. Hệ thống sẽ tự động hạ bậc để nhắc bạn ôn lại.',
    ],
    synergy: 'Định hình toàn bộ thuật toán phân bổ bài tập của Kế Hoạch 70/20/10.',
  },
  {
    id: 'adaptive-curriculum-702010',
    category: 'intelligence',
    title: 'Kế Hoạch Viết Thích Ứng 70 / 20 / 10 & Fatigue Guard',
    subtitle: 'Phân bổ bài tập khoa học theo tỷ lệ 70% lỗi dai dẳng, 20% củng cố, 10% mở rộng với bộ chống mệt mỏi.',
    route: '/intelligence',
    icon: 'list',
    badge: 'Cá Nhân Hóa',
    badgeTone: 'success',
    purpose: 'Giải quyết bài toán "Hôm nay tôi nên viết gì?" bằng cách tự động lên kế hoạch 4 bài tập tối ưu nhất cho từng người học.',
    whenToUse: 'Đầu mỗi buổi học hằng ngày.',
    howToUse: [
      'Vào Trí Tuệ Viết → Tab "📅 Kế hoạch 70/20/10".',
      'Xem danh sách các bài tập được giao hôm nay (Có tag 70% Điểm yếu, 20% Củng cố, 10% Mở rộng).',
      'Bấm nút "Bắt đầu làm bài" trên từng thẻ để nhảy thẳng đến phòng thực hành tương ứng.',
      'Sau khi hoàn thành các nhiệm vụ, bấm "Hoàn thành buổi học" để nhận bản tường trình AI Debrief và xoay vòng chu kỳ 8 bối cảnh.',
    ],
    proTips: [
      'Bộ bảo vệ chống mệt mỏi não bộ (Fatigue Guard) đảm bảo bạn không bao giờ phải làm 2 bài tập liên tiếp có cùng dạng lỗi hoặc cùng phong cách.',
    ],
    synergy: 'Tự động lấy dữ liệu từ bảng điểm yếu và kết quả thi Boss để xếp thứ tự ưu tiên.',
  },
  {
    id: 'weakness-fingerprint',
    category: 'intelligence',
    title: 'Điểm Yếu 5 Chiều & Vòng Đời 7 Trạng Thái',
    subtitle: 'Chẩn đoán dấu vân tay lỗi viết, tìm nguyên nhân gốc rễ và theo dõi vòng đời khắc phục lỗi.',
    route: '/intelligence',
    icon: 'search',
    badge: 'Chẩn Đoán',
    badgeTone: 'warning',
    purpose: 'Giúp người học nhìn thấu bản chất các lỗi sai cố hữu (Trợ từ, Chia động từ, Lẫn lộn thể thân mật/lịch sự, Dịch thô tiếng Việt).',
    whenToUse: 'Khi muốn nghiên cứu sâu nguyên nhân vì sao mình liên tục mắc một lỗi cụ thể.',
    howToUse: [
      'Vào Trí Tuệ Viết → Tab "🎯 Điểm yếu & Vòng đời".',
      'Xem Bảng chẩn đoán AI chuyên sâu: Nguyên nhân tâm lý, Cặp đối chiếu Đúng/Sai và Hành động khắc phục.',
      'Theo dõi Vòng đời lỗi qua 7 trạng thái: Mới xuất hiện → Đã ghi nhận → Mục tiêu ưu tiên → Đang tiến bộ → Ổn định → Làm chủ → Tái phát.',
      'Bấm nút "Luyện ngay" cạnh lỗi để mở phiên luyện tập chuyên sâu 4 giai đoạn.',
    ],
    proTips: [
      'Chú ý các lỗi có trạng thái "Tái phát" (Recurrent) vì đây là các lỗi bạn tưởng đã biết nhưng thực chất vẫn chưa làm chủ.',
    ],
    synergy: 'Cung cấp dữ liệu gốc cho Động cơ tính điểm ưu tiên WritingPriorityEngine.',
  },
  {
    id: 'expression-collocation',
    category: 'intelligence',
    title: 'Trí Tuệ Biểu Đạt, Collocation & Rada Lỗi Dịch Thô (L1)',
    subtitle: 'Bản đồ kết hợp từ tự nhiên, phát hiện lạm dụng từ và thang biến đổi 5 cấp độ kính ngữ.',
    route: '/intelligence',
    icon: 'sparkles',
    badge: 'Tự Nhiên',
    badgeTone: 'register',
    purpose: 'Nâng cấp câu viết từ "Đúng ngữ pháp nhưng gượng gạo" thành "Chuẩn phong cách tự nhiên như người bản xứ".',
    whenToUse: 'Khi bạn muốn tìm các cụm từ đi liền tự nhiên (Collocation) hoặc nghi ngờ câu của mình bị ảnh hưởng bởi văn phong tiếng Việt.',
    howToUse: [
      'Vào Trí Tuệ Viết → Tab "✨ Biểu đạt & Collocation".',
      'Tra cứu Bản đồ Collocation cho từ gốc (Base Word) để xem người Nhật hay ghép từ đó với trợ từ và động từ nào.',
      'Kiểm tra Rada lặp từ (Overuse Radar) để tìm các từ bạn đang dùng quá nhiều và xem từ thay thế tương đương.',
      'Sử dụng Thang chuyển đổi kính ngữ 5 bậc: Chuyển đổi qua lại giữa Casual → Polite → Formal → Business → Highly Formal.',
    ],
    proTips: [
      'Lỗi dịch thô (L1 Transfer) thường xuất phát từ việc dịch trực tiếp các cụm từ tiếng Việt như "có nhiều vấn đề", "tôi nghĩ là" mà không dùng cấu trúc chuyên dụng của tiếng Nhật.',
    ],
    synergy: 'Giúp cải thiện trực tiếp điểm số Tự nhiên (Naturalness) và Văn phong (Register) trong mọi bài nộp.',
  },

  /* =========================================================================
   * CATEGORY: LIBRARY & PROGRESS (Kho Tư Liệu & Tiến Độ Học Tập)
   * ========================================================================= */
  {
    id: 'learning-journey',
    category: 'library',
    title: 'Lộ Trình Chinh Phục (Learning Journey & Milestones)',
    subtitle: 'Bản đồ mục tiêu dài hạn: Mục tiêu lớn → Cột mốc Milestones → Mục tiêu chi tiết Objectives.',
    route: '/journey',
    icon: 'journey',
    badge: 'Dài Hạn',
    badgeTone: 'accent',
    purpose: 'Vạch rõ con đường từ trình độ hiện tại đến mục tiêu mong muốn (JLPT N3/N2/N1, Tiếng Nhật thương mại, Du học).',
    whenToUse: 'Định kỳ hằng tuần để kiểm tra xem mình đã đi được bao xa trên hành trình tổng thể.',
    howToUse: [
      'Tạo Lộ trình mới với Mục tiêu, Cấp độ xuất phát và Trình độ hướng tới.',
      'Mỗi Cột mốc (Milestone) bao gồm 3–5 Mục tiêu nhỏ (Objectives) với tiêu chuẩn vượt qua rõ ràng.',
      'Hoàn thành bài tập để hệ thống tự động ghi nhận bằng chứng và thăng hạng mục tiêu.',
    ],
    proTips: [
      'Nếu cảm thấy bị dậm chân tại chỗ, hãy bấm "Tái lập lộ trình" để AI tính toán lại các mục tiêu phù hợp với phong độ hiện tại.',
    ],
    synergy: 'Nhận phần thưởng XP lớn mỗi khi mở khóa thành công một Cột mốc mới.',
  },
  {
    id: 'vocabulary-bank',
    category: 'library',
    title: 'Sổ Từ Vựng Thông Minh (Personal Vocabulary Bank)',
    subtitle: 'Tự động trích xuất, phân loại JLPT và theo dõi độ quen thuộc của từ vựng từ chính bài viết của bạn.',
    route: '/vocabulary',
    icon: 'vocabulary',
    badge: 'Tích Lũy',
    badgeTone: 'grammar',
    purpose: 'Xây dựng vốn từ vựng chủ động (Active Vocabulary) — tức là những từ bạn thực sự biết cách dùng trong câu văn, thay vì chỉ học vẹt danh sách từ thụ động.',
    whenToUse: 'Sau mỗi buổi viết hoặc khi cần ôn lại các từ vựng đã từng sử dụng.',
    howToUse: [
      'Xem danh sách từ vựng được AI tự động thu thập từ các bài nộp của bạn.',
      'Lọc từ vựng theo Cấp độ JLPT (N5–N1), Chủ đề, hoặc Trạng thái quen thuộc (Mới học, Đang nhớ, Thành thạo).',
      'Bấm vào từng từ để xem chi tiết: Nguồn gốc phát hiện (từ bài tập nào), câu ví dụ mẫu và ghi chú sắc thái.',
    ],
    proTips: [
      'Sử dụng công cụ Tra cứu từ vựng AI tức thì trên thanh Header để hỏi nhanh cách dùng từ ngữ cảnh bất kỳ lúc nào.',
    ],
    synergy: 'Từ vựng trong sổ tay sẽ được AI ưu tiên đưa vào các bài tập tạo mới trong Luyện Tập (/practice).',
  },
  {
    id: 'learner-memory',
    category: 'library',
    title: 'Trí Nhớ Gia Sư AI (Learner Memory Bank)',
    subtitle: 'Hồ sơ ghi nhớ thói quen, phong cách, điểm mạnh và mục tiêu cá nhân của gia sư AI.',
    route: '/memory',
    icon: 'memory',
    badge: 'Cá Nhân Hóa',
    badgeTone: 'register',
    purpose: 'Giúp gia sư AI "nhớ" bạn là ai: bạn thích chủ đề gì, hay mắc lỗi ở đâu, đang nhắm đến mục tiêu nào để không bao giờ hỏi lại những thông tin cũ.',
    whenToUse: 'Xem xét định kỳ hoặc chỉnh sửa khi mục tiêu học tập của bạn thay đổi.',
    howToUse: [
      'AI tự động trích xuất các ký ức học tập từ quá trình bạn viết bài.',
      'Xem danh sách các khối ký ức được phân loại: Phong cách học, Lĩnh vực quan tâm, Điểm yếu cần chú ý, Mục tiêu JLPT.',
      'Bạn có thể bật/tắt hoặc xóa bỏ các ký ức không còn phù hợp.',
    ],
    proTips: [
      'Bạn có thể bật/tắt quyền truy cập Trí Nhớ AI trong trang Cài Đặt (/settings).',
    ],
    synergy: 'Ký ức AI được truyền thẳng vào Prompt của mọi bài tập tạo mới và phiên mô phỏng hội thoại.',
  },
  {
    id: 'analytics-dashboard',
    category: 'library',
    title: 'Báo Cáo Phân Tích Học Tập (Learning Analytics)',
    subtitle: 'Biểu đồ trực quan về sản lượng ký tự đã viết, thời gian thực hành và xu hướng tiến bộ.',
    route: '/analytics',
    icon: 'analytics',
    badge: 'Thống Kê',
    badgeTone: 'neutral',
    purpose: 'Cung cấp cái nhìn toàn cảnh bằng dữ liệu thực tế về sự chăm chỉ và tốc độ tiến bộ của bạn theo thời gian.',
    whenToUse: 'Tổng kết cuối tuần hoặc cuối tháng.',
    howToUse: [
      'Xem biểu đồ phân bố điểm số theo thời gian (7 ngày, 30 ngày, toàn thời gian).',
      'Theo dõi tổng số từ/ký tự đã viết và số giờ học thực tế.',
      'Xem phân bố bài tập theo các dạng kỹ năng để biết mình có đang học lệch hay không.',
    ],
    proTips: ['Đặt mục tiêu duy trì đường cong tiến bộ điểm số tăng đều đặn qua từng tuần.'],
    synergy: 'Dữ liệu phân tích giúp bạn điều chỉnh thời lượng luyện tập trong Lộ Trình.',
  },
  {
    id: 'ai-quality-benchmark',
    category: 'library',
    title: 'Giám Sát Chất Lượng AI (AI Quality & Golden Benchmark)',
    subtitle: 'Bảng theo dõi độ chính xác, tính nhất quán, độ trễ và 107 ca kiểm thử chuẩn mực.',
    route: '/ai-quality',
    icon: 'target',
    badge: 'Chuyên Sâu',
    badgeTone: 'neutral',
    purpose: 'Minh bạch hóa chất lượng của các mô hình AI đang phục vụ bạn, đảm bảo mọi phản hồi chấm điểm đều đạt chuẩn sư phạm cao nhất.',
    whenToUse: 'Dành cho người học muốn kiểm tra độ tin cậy của AI hoặc so sánh hiệu năng giữa Gemini, Groq và Ollama.',
    howToUse: [
      'Xem tỷ lệ phản hồi hợp lệ và độ trễ trung bình của các mô hình AI.',
      'Xem kết quả kiểm thử trên Bộ dữ liệu vàng (Golden Benchmark 107 test cases).',
      'Kiểm tra phiên bản các Prompt hệ thống đang hoạt động.',
    ],
    proTips: ['Nếu thấy phản hồi AI chậm, hãy thử chuyển sang Groq Cloud trên thanh Header để có tốc độ phản hồi cực nhanh.'],
    synergy: 'Bảo chứng chất lượng cho toàn bộ hệ thống đánh giá và trợ giảng AI.',
  },

  /* =========================================================================
   * CATEGORY: ZEN & PRODUCTIVITY (Công Cụ Thiền Zen & Năng Suất)
   * ========================================================================= */
  {
    id: 'global-furigana',
    category: 'zen',
    title: 'Bộ Điều Chỉnh Furigana Toàn Cầu (Global Furigana)',
    subtitle: '4 chế độ thông minh hiển thị cách đọc Hiragana trên đầu chữ Hán Kanji.',
    icon: 'eye',
    badge: 'Hỗ Trợ Đọc',
    badgeTone: 'grammar',
    purpose: 'Giúp người học ở mọi cấp độ không bị gián đoạn bài viết vì quên cách đọc một chữ Kanji.',
    whenToUse: 'Tùy chỉnh ngay trên thanh Header TopBar bất kỳ lúc nào.',
    howToUse: [
      'Nhấp nút Furigana trên Header để chuyển đổi 4 chế độ:',
      '• Bật Tất Cả: Hiện Furigana cho toàn bộ chữ Kanji.',
      '• Chỉ Từ Khó JLPT: Chỉ hiện cách đọc cho các chữ Kanji cao hơn cấp độ JLPT hiện tại của bạn.',
      '• Tắt Toàn Bộ: Ẩn Furigana để rèn khả năng tự đọc mặt chữ Kanji.',
      '• Mặc Định: Giữ nguyên cách hiển thị gốc.',
    ],
    proTips: ['Khi chuẩn bị thi JLPT, hãy chuyển sang chế độ "Chỉ từ khó" hoặc "Tắt" để rèn phản xạ nhận diện chữ Hán.'],
    synergy: 'Áp dụng đồng bộ trên toàn bộ bài tập, đoạn văn giải thích và kết quả chấm điểm.',
  },
  {
    id: 'zen-tea-timer',
    category: 'zen',
    title: 'Đồng Hồ Trà Đạo (Zen Tea Timer & Pomodoro)',
    subtitle: 'Đếm ngược các phiên viết sâu 5 - 15 - 25 phút giúp loại bỏ xao nhãng.',
    icon: 'clock',
    badge: 'Tập Trung',
    badgeTone: 'accent',
    purpose: 'Ứng dụng nguyên lý Pomodoro và tinh thần Trà đạo Nhật Bản để đưa người học vào trạng thái Dòng chảy viết sâu (Deep Writing Flow).',
    whenToUse: 'Bật trước khi bắt đầu một bài viết tự do, bài dịch dài hoặc nhiệm vụ tình huống.',
    howToUse: [
      'Nhấp vào biểu tượng Ấm Trà trên thanh Header.',
      'Chọn thời lượng phiên viết: 5 phút (Khởi động), 15 phút (Luyện tập tiêu chuẩn), hoặc 25 phút (Viết sâu).',
      'Khi hết giờ, âm thanh chuông chùa thanh tịnh sẽ nhẹ nhàng nhắc bạn nghỉ ngơi và thư giãn.',
    ],
    proTips: ['Trong suốt phiên Trà đạo, hãy cam kết không chuyển tab trình duyệt và không kiểm tra điện thoại.'],
    synergy: 'Ghi nhận thời gian học tập thực tế vào Báo Cáo Phân Tích (/analytics).',
  },
  {
    id: 'zen-soundscape',
    category: 'zen',
    title: 'Âm Thanh Tĩnh Tâm (Zen Soundscape Player)',
    subtitle: '4 không gian âm thanh thư giãn chuẩn Nhật Bản hỗ trợ tối đa cho việc tư duy viết lách.',
    icon: 'sparkles',
    badge: 'Thư Giãn',
    badgeTone: 'success',
    purpose: 'Tạo môi trường âm thanh êm dịu, che lấp tiếng ồn xung quanh và kích hoạt sóng não Alpha tăng cường trí nhớ.',
    whenToUse: 'Bật khi đang suy nghĩ câu chữ hoặc muốn giải tỏa căng thẳng trong lúc học.',
    howToUse: [
      'Nhấp vào biểu tượng Sóng Âm trên thanh Header.',
      'Chọn 1 trong 4 không gian âm thanh:',
      '• 🌧️ Mưa Kyoto (Kyoto Rain): Tiếng mưa rơi êm đềm trên mái hiên gỗ.',
      '• ⛩️ Suối Đền Chùa (Temple Stream): Tiếng nước róc rách thanh tịnh tại đền cổ.',
      '• 🎋 Rừng Tre Arashiyama (Bamboo Wind): Tiếng gió rì rào qua rặng tre xanh ngọc.',
      '• ⌨️ Bàn Phím Cơ Cổ Điển (Mechanical Keyboard): Tiếng gõ phím nhịp nhàng kích thích cảm hứng viết.',
      'Điều chỉnh âm lượng vừa phải phù hợp với sở thích.',
    ],
    proTips: ['Kết hợp đeo tai nghe và chọn không gian "Mưa Kyoto" khi luyện viết vào ban đêm.'],
    synergy: 'Giúp duy trì năng lượng và hạn chế mệt mỏi trong các buổi học kéo dài.',
  },
  {
    id: 'shodo-ink-cursor',
    category: 'zen',
    title: 'Bút Mực Thư Pháp (Shodo Ink Brush Cursor)',
    subtitle: 'Hiệu ứng nét mực truyền thống mềm mại bay bổng theo từng chuyển động chuột.',
    icon: 'write',
    badge: 'Nghệ Thuật',
    badgeTone: 'neutral',
    purpose: 'Mang không gian văn hóa nghệ thuật Thư pháp Shodo Nhật Bản vào từng thao tác sử dụng phần mềm.',
    whenToUse: 'Bật/tắt bằng nút Cọ Mực trên Header theo sở thích cá nhân.',
    howToUse: [
      'Nhấp vào biểu tượng Cọ Mực trên Header để kích hoạt hiệu ứng vệt mực.',
      'Di chuyển chuột để trải nghiệm cảm giác như đang cầm bút lông lướt trên giấy Washi truyền thống.',
    ],
    proTips: ['Rất thích hợp khi luyện tập trong phòng Luyện Chữ Hán Kanji (/kanji).'],
    synergy: 'Nâng cao tính thẩm mỹ và cảm hứng văn hóa Nhật Bản.',
  },
  {
    id: 'topbar-vocab-lookup',
    category: 'zen',
    title: 'Tra Cứu Từ Vựng AI Tức Thì (Instant AI Vocab Lookup)',
    subtitle: 'Tra cứu nhanh cách dùng từ, sắc thái và câu ví dụ trực tiếp trên Header mà không cần rời trang.',
    icon: 'search',
    badge: 'Tra Cứu',
    badgeTone: 'vocabulary',
    purpose: 'Giải quyết ngay lập tức thắc mắc "Từ này dùng trong câu như thế nào?" ngay khi đang viết mà không làm đứt mạch cảm xúc.',
    whenToUse: 'Bất kỳ lúc nào bạn cần tìm một từ vựng tiếng Nhật phù hợp với ý nghĩ của mình.',
    howToUse: [
      'Nhấp nút Kính Lúp trên thanh Header (hoặc dùng phím tắt).',
      'Gõ từ tiếng Việt hoặc tiếng Nhật cần tra cứu (ví dụ: "xin lỗi trang trọng", "hủy hẹn", "bận rộn").',
      'AI sẽ giải thích sắc thái, đưa ra từ tương đương chuẩn nhất và gợi ý 3 câu ví dụ thực tế.',
      'Bấm nút "Lưu vào Sổ từ vựng" để lưu lại nếu thích.',
    ],
    proTips: ['Bạn có thể tra cứu theo cụm ý nghĩa bằng tiếng Việt thay vì chỉ tra từ đơn lẻ.'],
    synergy: 'Từ vựng tra cứu được lưu trực tiếp vào Sổ Từ Vựng cá nhân (/vocabulary).',
  },
  {
    id: 'seasons-themes',
    category: 'zen',
    title: 'Chuyển Đổi 4 Mùa Nhật Bản & Giao Diện Sáng/Tối',
    subtitle: 'Tùy biến bảng màu giao diện theo 4 mùa: Xuân (Sakura), Hạ (Tre ngọc), Thu (Lá phong), Đông (Tuyết bạc).',
    icon: 'sun',
    badge: 'Giao Diện',
    badgeTone: 'register',
    purpose: 'Mang lại trải nghiệm thị giác tươi mới, êm dịu cho mắt và gắn liền với vẻ đẹp thiên nhiên bốn mùa của xứ sở mặt trời mọc.',
    whenToUse: 'Thay đổi theo tâm trạng hoặc mùa thực tế trong năm.',
    howToUse: [
      'Nhấp nút Biểu tượng Mùa trên Header để chọn: Xuân 🌸, Hạ 🎋, Thu 🍁, Đông ❄️.',
      'Nhấp nút Mặt trời/Mặt trăng để chuyển đổi giữa chế độ Sáng (Light) và Tối (Dark).',
    ],
    proTips: ['Chế độ Tối (Dark Mode) kết hợp Mùa Thu Lá Phong mang lại cảm giác cực kỳ ấm áp và dịu mắt khi học ban đêm.'],
    synergy: 'Tự động ghi nhớ thiết lập giao diện cho những lần đăng nhập sau.',
  },

  /* =========================================================================
   * CATEGORY: SETTINGS (Cấu Hình AI & Thiết Lập Cá Nhân)
   * ========================================================================= */
  {
    id: 'ai-provider-settings',
    category: 'settings',
    title: 'Cấu Hình Nhà Cung Cấp AI & Bảo Mật Khóa API',
    subtitle: 'Hỗ trợ linh hoạt Google Gemini, Groq Cloud và Local Ollama với cơ chế che khóa an toàn.',
    route: '/settings',
    icon: 'settings',
    badge: 'Hệ Thống',
    badgeTone: 'neutral',
    purpose: 'Cho phép người học tự do lựa chọn động cơ AI phù hợp với nhu cầu và tốc độ mong muốn.',
    whenToUse: 'Khi cài đặt ban đầu hoặc muốn đổi nhà cung cấp AI.',
    howToUse: [
      'Vào Cài Đặt (/settings) → Khóa API & Nhà cung cấp.',
      'Điền API Key của Google Gemini hoặc Groq Cloud (khóa được mã hóa và chỉ hiển thị dạng ẩn `AIza****1234`).',
      'Hoặc chọn Ollama nếu muốn chạy mô hình AI offline hoàn toàn trên máy tính cá nhân.',
      'Chuyển đổi Model AI trực tiếp trên Header TopBar bất kỳ lúc nào.',
    ],
    proTips: [
      'Google Gemini cho khả năng giải thích ngữ pháp tiếng Việt rất sâu và mượt mà.',
      'Groq Cloud cho tốc độ phản hồi cực kỳ nhanh (dưới 1 giây), rất lý tưởng cho chế độ Mô Phỏng Hội Thoại.',
    ],
    synergy: 'Quyết định động cơ AI xử lý cho toàn bộ các bài tập trong ứng dụng.',
  },
]
